### ISSUE TITLE
No structures will spawn

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#10]
Just quickly have checked how my PRs gets merged and I noticed (but didn't tested anything) the structures can't spawn as the code has diverged at some point.

You clearly don't longer need the SurfaceGenerator (superseded by OverworldGenerator) and to see the structures spawn you need to instantiate the StructurePopulator in the OverworldGenerator constructor.

**Comment by TekkitCommando** [comment]
Thank you :)

**Comment by mastercoms** [comment]
Are dungeons considered structures? I was testing Glowstone++ earlier and in the console it logged a dungeon spawn. I am not sure if it actually created the dungeon in the world or not, though.

**Comment by jimmikaelkael** [comment]
Dungeons is considered as a structure just because it uses the building features that the structures uses. Otherwise it's not saved, so no it's not fully a structure.

I guess you've seen it before because the complete Overworld world generator wasn't pulled at that time.

**Comment by mastercoms** [comment]
Ah. Well I am planning on changing the world gen a bit so I might fix it.

**Comment by jimmikaelkael** [comment]
What are you planning to change ?

**Comment by mastercoms** [comment]
I am planning on making world gen even prettier.

**Comment by jimmikaelkael** [comment]
I did not expected you to tell me it's to make it look ugly :) 
Details ?

**Comment by mastercoms** [comment]
I want to play around with the noise settings, and maybe even give people more customization like they would get with TerrainControl, which uses NMS and does not work with Glowstone.

**Comment by deathcap** [comment]
@jimmikaelkael Aha, I was confused about that merge conflict. Adding StructurePopulator to OverworldGenerator does indeed fix structure generation. Cheers!

```
18:21:13 [INFO] dungeon generated: -2545,5,-646
18:21:30 [INFO] structure in chunk -143,-26
18:21:34 [INFO] dungeon generated: -2384,40,-443
18:24:26 [INFO] dungeon generated: -2320,66,-236
```

![2015-04-09_18 25 29](https://cloud.githubusercontent.com/assets/5897956/7080437/fdf65668-dee6-11e4-9341-149096dd23cf.png)

anything else?

@mastercoms Sounds cool, adding more configurability and flexibility. Also could be worth looking into the parameters in http://minecraft.gamepedia.com/Customized and maybe also new biomes added by other plugins e.g. https://github.com/ExtrabiomesXL/ExtrabiomesXL/ (open source, a Creative Commons Attribution-ShareAlike 3.0 Unported License — adds new blocks, but they have/had a "classic mode" https://github.com/ExtrabiomesXL/ExtrabiomesXL/wiki/Frequently-Asked-Questions#classicmode using no custom blocks).

**Comment by mastercoms** [comment]
@deathcap I have begun my first changes to world management in  #12. I am trying to restructure world code to scale better before adding on more features/configurability.

**Comment by jimmikaelkael** [comment]
@deathcap If you look at the class OverworldGenerator there's already bunch of static fields I planned to link with world customization, complying with http://minecraft.gamepedia.com/Customized
