### ISSUE TITLE
Console filled with '>'

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#100]
I am running Glowstone++ 1.8.8-SNAPSHOT and everytime something is printed to the console hundreds of `>` signs follow. How can I fix this? Is it a server misconfiguration?

**Comment by mastercoms** [comment]
What Java version are you using?
What OS?
Any plugin installed?

**Comment by mhsjlw** [comment]
Java version: 8
OS: Ubuntu 14.04
Plugins: None, fresh install of glowstone++

**Comment by mastercoms** [comment]
Are you using a start script or starting with java -jar glowstone++.jar?

**Comment by mhsjlw** [comment]
Start script

**Comment by mastercoms** [comment]
What is your start script?

**Comment by mhsjlw** [comment]
`java -Xmx512 -Xms512 -jar minecraft.jar nogui &`

**Comment by mastercoms** [comment]
Try just having `java -Xmx512 -Xms512 -jar minecraft.jar`

**Comment by mhsjlw** [comment]
Sorry, I forgot the `eval` that I have in my script:

```
eval "java -Xmx${heap} -Xms${heap} -jar minecraft.jar nogui &"
main_pid=$!
```

**Comment by mhsjlw** [comment]
I do that to get the process id so I can kill it later

**Comment by mastercoms** [comment]
Well just try and see if changing it to the script mentioned prior fixes the issue.

**Comment by mhsjlw** [comment]
Ok, sure.

**Comment by mhsjlw** [comment]
That fixed the issue. But I need to use the main_pid. Is there a way I can disable the `>`?

**Comment by mastercoms** [comment]
Is `&` there for a reason in your script?

**Comment by mhsjlw** [comment]
To bind the `eval` to the PID

**Comment by mastercoms** [comment]
Ah, ok. Will removing `nogui` solve the issue?

**Comment by mhsjlw** [comment]
I'm not sure, I'll try

**Comment by mhsjlw** [comment]
It didn't

**Comment by mastercoms** [comment]
I found an alternative to your script.

run
```bash
kill `ps -A -o pid,cmd|grep "java -Xmx512 -Xms512 -jar minecraft.jar" | grep -v grep |head -n 1 | awk '{print $1}'`
```

**Comment by mhsjlw** [comment]
Wow, thanks!

**Comment by mhsjlw** [comment]
I am actually writing a buildpack that lets you host a minecraft server for free on heroku using glowstone++ because of the preformance. If you are interested, check it out https://github.com/mhsjlw/minecraft-buildpack

**Comment by mastercoms** [comment]
Oh cool!

**Comment by TekkitCommando** [comment]
@mhsjlw Looks cool :)

**Comment by mhsjlw** [comment]
@TekkitCommando It will be awesome when it is done because then everyone will be able to get a minecraft server running their software of choice for free! No one has to pay for hosting ever again!

**Comment by TekkitCommando** [comment]
@mhsjlw Thats a very awesome goal :) Good luck!

**Comment by mhsjlw** [comment]
@TekkitCommando Thank you very much! If you'd like you can try it out yourself, the instructions are in the README.md file!

**Comment by TekkitCommando** [comment]
@mhsjlw Ok sweet! I might try it out this week sometime :)

**Comment by mhsjlw** [comment]
If possible, someone should add a config line that lets you tell the server if you want to use the '>' or not.

**Comment by mastercoms** [comment]
Or maybe even customize what you want it to be.

**Comment by mhsjlw** [comment]
That could work too.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/9c2d62d7936203ae6897ccc20abe6ed98e023660
