### ISSUE TITLE
Water doesn't go away after removing it

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#102]
When you place water normally in Minecraft when the main source block is removed the water slowly flows away. In Glowstone, more source blocks are made which cannot be picked up by a bucket therefore creating water that can't ever be removed.

**Comment by mastercoms** [comment]
I am working on fixing liquids in the liquid-redux branch. You can use it by downloading the jar from circleci.

**Comment by mastercoms** [comment]
Here: https://circleci.com/gh/GlowstonePlusPlus/GlowstonePlusPlus/391#artifacts

Please tell me if it works for you.

**Comment by mhsjlw** [comment]
Sorry for the very, very late response but it does in fact work. I'll close the issue.
