### ISSUE TITLE
Can't Launch

### ISSUE THREAD

**Issue by SMASH-DIAMOND** [GlowstoneMC/Glowstone#1023]
Title: It won't Launch

Glowstone build: #2018.9.0

I am Having Issues launching. Here is the photo
![image](https://user-images.githubusercontent.com/45404735/52587877-bd297800-2e00-11e9-9fc9-b7d276e30d7e.png)

**Comment by VaiTon** [comment]
From what I can see the file glowstone.jar is missing. Are you sure you put it in the right folder?

**Comment by SMASH-DIAMOND** [comment]
Yes
![image](https://user-images.githubusercontent.com/45404735/52593431-940fe400-2e0e-11e9-9022-c6afcfe79b61.png)

**Comment by SMASH-DIAMOND** [comment]
![image](https://user-images.githubusercontent.com/45404735/52593550-d802e900-2e0e-11e9-91b8-e4f222786786.png)

**Comment by Pr0methean** [comment]
The bug seems to be in start.command, which means it belongs on the GlowstoneMC/docs repo. Would someone with admin on both repos please transfer it?
