### ISSUE TITLE
[1.13-Hack] Build failed because of Bukkit imports?

### ISSUE THREAD

**Issue by GMatrixGames** [GlowstoneMC/Glowstone#1045]
Title: [1.13-Hack] Build failed because of Bukkit imports?

Glowstone git id: 5d2b9a4

Not much explanation, just maven not able to compile it.

---

https://dev.matrixdevteam.ml/ci/job/GlowstoneMC/103/console

**Comment by mastercoms** [comment]
This is an incomplete branch that is not expected to compile.
