### ISSUE TITLE
Error: Could not find or load main class net.glowstone.GlowServer

### ISSUE THREAD

**Issue by pirate** [GlowstoneMC/Glowstone#1046]
Glowstone build: `glowstone-2018.10.0-20190604.011214-85.jar`

Fresh install on Ubuntu 19.04 with the correct java version:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.19.04.2-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

Whenever I try launching glowstone it errors out immediately:
```bash
$ java -Xms1G -Xmx1G -XX:+UseG1GC -jar /opt/minecraft/minecraft-glowstone.jar
Error: Could not find or load main class net.glowstone.GlowServer
```

I've confirmed other java programs work fine on this system, so it doesn't seem to be a java setup issue.  I've also confirmed the file was downloaded correctly, the jar file has the correct size and contains real data.
I've also confirmed that it's a problem specific to the latest version, launching an older version of glowstone works fine.
```bash
$ java -Xms1G -Xmx1G -XX:+UseG1GC -jar /opt/minecraft/old-glowstone.jar
01:54:11 [INFO] This server is running Glowstone version 2017.11.0-SNAPSHOT.65c58a9 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
01:54:11 [INFO] Recipes: 307 shaped, 63 shapeless, 26 furnace, 10 dynamic, 44 fuels.
01:54:11 [INFO] Scanning plugins...
01:54:11 [INFO] Preparing spawn for world...
01:54:14 [INFO] Preparing spawn for world: 0%
01:54:15 [INFO] Preparing spawn for world: 2%
...
```

**Comment by mastercoms** [comment]
Could you launch with the `-Xdiag` option and share the output here?

**Comment by pirate** [comment]
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.19.04.2-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

$ java -Xms1G -Xmx1G -XX:+UseG1GC -Xdiag -jar glowstone-2018.10.0-20190604.011214-85.jar
Error: Could not find or load main class net.glowstone.GlowServer
java.lang.ClassNotFoundException: net.glowstone.GlowServer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by mastercoms** [comment]
Could you test running your own Maven build of Glowstone from source?

**Comment by pirate** [comment]
FYI this is reproducible in docker, which means it's very likely not an issue specific to my system.

Put `glowstone-2018.10.0-20190604.011214-85.jar` in a directory and create this file next to it:
`docker-compose.yml`:
```
version: '3'

services:
    java:
        image: openjdk:8
        command: bash -c "cd /opt/minecraft && java -Xms1G -Xmx1G -jar glowstone-2018.10.0-20190604.011214-85.jar"
        volumes:
            - ./:/opt/minecraft
```
Then run `docker-compose up`.
```bash
$ docker-compose up
Recreating 1221_java_1 ... done
Attaching to 1221_java_1
java_1  | Error: Could not find or load main class net.glowstone.GlowServer
1221_java_1 exited with code 1
```

I don't have the bandwidth to compile it from source at the moment, but given it's globally reproducible it shouldn't be hard for someone else to do so.  
If no one else has time I'll try to do it sometime next month when I'm back from travel.

**Comment by mastercoms** [comment]
Where are you downloading this file from?

**Comment by mastercoms** [comment]
We found the cause of this issue on our build server and it has been fixed. Thank you for reporting this to us!
