### ISSUE TITLE
Sorta off topic but... 

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#105]
How long have you been designing websites @mastercoms and did you make Circuitsoft one? and is that a registered non profit or business I think I saw it somewhere but im not 100% sure. I feel like I did.

**Comment by mastercoms** [comment]
I have been designing websites for 3 years and I did make the CircuitSoft one. We're registering as a non profit, but we have not yet. If you would like to continue with this discussion, I can be reached at circuitsoft @ openmailbox.org.
