### ISSUE TITLE
What can I do to help?

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#107]
I used the first glowstone version for a little bit and was very interested in this new server software. Now I've got a little more experience in java (Still I'm only about half experienced in it) and I want to find a way to help glowstone++. Do you guys have any ideas?

**Comment by mastercoms** [comment]
Well, look at the issues here, or at GlowstoneMC (test the issues to see if they are still relevant), and see if you can fix them. Then, make a pull request for your fix. You can also look at the code and if you see something fishy/hacky or something that can improved upon, do that. There are also a bunch of TODOs in the code: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/search?utf8=%E2%9C%93&q=TODO

**Comment by codekilla747** [comment]
@mastercoms so i found that flint and steel doesn't dectect if a block is flammable or not, so can I work on that?

```Java
   @Override
    public boolean onToolRightClick(GlowPlayer player, ItemStack holding, GlowBlock target, BlockFace face, Vector clickedLoc) {
        switch (target.getType()) {
            case TNT:
                fireTnt(target);
                return true;
            case OBSIDIAN:
                fireNetherPortal();
                return true;
            // TODO: check for non-flammable blocks
            default:
                return setBlockOnFire(player, target, face, holding, clickedLoc);
        }
    }
```

**Comment by mastercoms** [comment]
Yeah, that would be great! Use this method to check: https://github.com/GlowstonePlusPlus/Glowkit/blob/bukkit%2Bglowkit/src/main/java/org/bukkit/Material.java#L948

**Comment by codekilla747** [comment]
@mastercoms So should I do this in my own fork of the project?

**Comment by mastercoms** [comment]
Yep, just press fork, and create a new branch in your fork. Then, when you make changes, GitHub will pop up with a prompt to merge it using a pull request.
