### ISSUE TITLE
UUID lookups do not thread

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone#111]
Is it possible to fetch player's UUID in another thread? It hangs the server when typing in a random username. 
##

**Comment by mastercoms** [comment]
Yep, totally possible, but I'm rewriting Glowstone++, so someone else will have to do it.

**Comment by codekilla747** [comment]
Wait, @mastercoms you're completely rewriting glowstone++?

**Comment by TekkitCommando** [comment]
Woot!

**Comment by mastercoms** [comment]
Yep, JSON based item definitions, tickless server, and the server is based on events, services, and modular components.

**Comment by codekilla747** [comment]
@mastercoms That sounds awesome! Are you coding that in your own fork?

**Comment by mastercoms** [comment]
I am coding it in a new repository, on my computer. Once it is fairly done, I will upload it.

**Comment by kamcio96** [comment]
Will it implement SpongeAPI?

**Comment by TekkitCommando** [comment]
I don't see why not, Sponge API support was one of the features of G++ and a recode shouldn't get rid of that idea.

**Comment by DefinitlyEvil** [comment]
@mastercoms Tickless will be crazy, how do you synchronize objects?

**Comment by TekkitCommando** [comment]
I wonder the same thing but I'm sure whatever idea he has it's a good one

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Many years ago people thought about multi-threaded server it means no ticks but they are unable to do that.

**Comment by kamcio96** [comment]
Ofc it is possible :smile:

**Comment by DefinitlyEvil** [comment]
@kamcio96 Okay. >~<

**Comment by mastercoms** [comment]
It will be like the LInux tickless kernel. For things that can't use the new system to do repeatable actions using services and events, Glowstone++ will only tick those actions when necessary.  And yes, I am basing the recode off of Sponge.

**Comment by DefinitlyEvil** [comment]
Awesome!

**Comment by codekilla747** [comment]
I might make a Linux build designed to run a minecraft server

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Dec 3, 2015 at 3:47 AM -0800, "mastercoms" <notifications@github.com<mailto:notifications@github.com>> wrote:


It will be like the LInux tickless kernel. For things that can't use the new system to do repeatable actions using services and events, Glowstone++ will only tick those actions when necessary. And yes, I am basing the recode off of Sponge.

-

**Comment by DefinitlyEvil** [comment]
@codekilla747 Omg!

**Comment by kamcio96** [comment]
@mastercoms 
"base from scratch" was Glowstone point ;)
 Do you have idea how use both of Bukkit and SpongeAPI?
I suggest to write it only with SpongeAPI and then write bridge (SpongeAPI has more events);

**Comment by DefinitlyEvil** [comment]
@kamcio96 You mean only support Sponge plugin and make a Bukkit bridge to Sponge?

**Comment by mastercoms** [comment]
@kamcio96 There are a few things missing from SpongeAPI, like https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/ProtocolMinecraftVersion.java

**Comment by kamcio96** [comment]
@DefinitlyEvil yes
@mastercoms so we can compile that one class :smiling_imp:

**Comment by gabizou** [comment]
> @kamcio96 There are a few things missing from SpongeAPI, like https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/ProtocolMinecraftVersion.java which is in SpongeCommon

Sorry, but why is it necessary to expose the protocol version in an API?

**Comment by mastercoms** [comment]
@gabizou Not saying it should be in the API, just saying we need it for our project, and it is missing if we only use Sponge API.

@kamcio96 It just seems like it is a better idea to fork SpongeVanilla, and put our stuff in it, instead of rewriting everything.

**Comment by kamcio96** [comment]
@mastercoms So now I don't understand you. You want fork SpongeVanilla and do what? Glowstone is alone project. Adding minecraft code is pointless.

**Comment by TekkitCommando** [comment]
@mastercoms yes sponge vanilla is the best idea by far! Not worth making from scratch

**Comment by gabizou** [comment]
> Not saying it should be in the API, just saying we need it for our project, and it is missing if we only use Sponge API.

That summarizes what is commonly known as "implementation detail." If you need it for implementation, then it's included in the implementation. I don't see much of a problem since the API doesn't have a care in the world about it.

**Comment by kamcio96** [comment]
@gabizou you are right
@TekkitCommando why making from scratch is bad idea? one mojang change (eg protect theirs files) and we have to write it again. And we can add more and more functions to server and plugins.

**Comment by Tzky** [comment]
> I suggest to write it only in SpongeAPI and then write a bridge (SpongeAPI has more events);

There already is an incomplete bridge between Bukkit and SpongeAPI. It's a Sponge plugin named Pore.

**Comment by TekkitCommando** [comment]
@kamcio96 Not that it's a bad idea, I mean G++ and Glowstone were founded on from scratch code. I am saying that if some of the features mastercoms wants is already present in SpongeVanilla why not use it. I didn't know that Sponge uses Minecraft code. I thought they were doing things from scratch as well

**Comment by kamcio96** [comment]
@TekkitCommando unfortunately not :/

**Comment by Tzky** [comment]
Sponge is based on the Vanilla server or Forge. Depends wether you choose SpongeForge or SpongeVanilla. We're *not* writing a complete client/server from scratch.

**Comment by TekkitCommando** [comment]
@Tzky So we've heard.

**Comment by mastercoms** [comment]
> That summarizes what is commonly known as "implementation detail." If you need it for implementation, then it's included in the implementation. I don't see much of a problem since the API doesn't have a care in the world about it.

Yes, which is why I was saying we should also use the implementation. I'm not saying Sponge API needs to expose these features, just that we need to use the implementation, and not just the API, unless we want to rewrite a lot of code that is already done in SpongeCommon. There is no problem with Sponge, just a problem with us.

> Also, this transitively means forking SpongeCommon as a majority of the implementation resides there (SpongeCommon exists as a buffer of the "common" implementation that can be shared between both Vanilla and Forge). In this context however, it explicitly is using Minecraft's objects as much as possible to piggy back not having to write new objects/implementation.

Yes, I was planning on forking SpongeCommon as well, though I was not aware that Sponge used Mojang's code. In that case, we will not be forking SpongeVanilla.

Though, I am still thinking about forking SpongeCommon, since it has some handy Sponge implementations.

**Comment by Tzky** [comment]
You are aware that SpongeVanilla won't run without SpongeCommon and viceversa, right? SpongeCommon is just the shared code between SpongeForge and SpongeVanilla. 

SpongeCommon still hooks into the Mojang server.

**Comment by mastercoms** [comment]
But we can replace SpongeVanilla with our own code so SpongeCommon works right? And I guess we can modify the SpongeCommon code that hooks into the Mojang server with our own code.

**Comment by gabizou** [comment]
> And I guess we can modify the SpongeCommon code that hooks into the Mojang server with our own code.

The only implementations you could use would be implementations that have no reliance on a Mojang class. A large majority of the classes in both Common and Vanilla/Forge use what is called Mixins. With Mixins, we can apply our interfaces onto Mojang's, which allows us to cast back and forth from API to Minecraft classes. This is the issue that you'd likely see when you try to work with only SpongeAPI and a from scratch implementation with no Mojang code.

**Comment by Zidane** [comment]
Fortunately, many of the implementation classes in SpongeCommon, beyond Mixins, are reusable since the implementation of them won't vary much between implementations.

Also, thanks for considering us! If you have any API feedback, be sure to throw us an issue on our repos.

**Comment by liach** [comment]
Can a implementation work without mixins, but just implement the interfaces from Sponge API?

**Comment by TekkitCommando** [comment]
@Zidane Thank you for making the API xD

**Comment by mastercoms** [comment]
@Zidane Ok, thanks for the help. I'll be sure to do so if I find anything, but so far, Sponge looks solid (I mean, squishy and cute)!

**Comment by Zidane** [comment]
@liach

Yes it can. Mixins is a Mumfrey/Sponge technology that simply is one method of making the base Minecraft objects implement our interfaces. Another solution is to do patches ala Forge.

If you are doing your own server implementation, you can easily *just* implement the interfaces on your implementation objects. This is the cleanest method since you don't have to deal with someone else's implementation and therefore rigging it into your own :p.

**Comment by TekkitCommando** [comment]
@Zidane Thanks for being so helpful :)

**Comment by Zidane** [comment]
@TekkitCommando 

No problem.

**Comment by mastercoms** [comment]
@Zidane Yes, thank you for the help. I finally understand completely how to use Sponge.

**Comment by kamcio96** [comment]
@mastercoms
What would be the final form of the GlowstonePlusPlus?

**Comment by mastercoms** [comment]
@kamcio96 Our own implementation of Sponge.

**Comment by kamcio96** [comment]
@mastercoms Great decision. :smile: How can we help? When are you going to start doing something on Github?
I really hope that game loop will be asynchronous :wink:

**Comment by jimmikaelkael** [comment]
I'd really wish this project can resume to a very active state. I mainly stopped to contribute by fear to see them going through waste (and because I started to develop an indie game early 2015).

**Comment by mastercoms** [comment]
I have a problem with implementing entity.living.Player. I can't implement the get and getOrCreate methods from  data.value.mutable.CompositeValueStore.

**Comment by gabizou** [comment]
A little rundown of the structure of the Data API and Player in this context:
`CompositeValueStore` is the generic definition of being able to contain anything that is a `ValueContainer`. `DataHolder` specifies that it is able to contain `DataManipulator`s by the class generic:

``` java
public interface DataHolder extends DataSerializable, PropertyHolder, CompositeValueStore<DataHolder, DataManipulator<?, ?>> {
```

`Entity` extends `DataHolder` because this is how the entire Data API works.

So, in reality, your `SunPlayer` just simply needs to implement all the Data API methods much as the methods are overriden in [`MixinDataHolder`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/data/MixinDataHolder.java#L52), ideally, `SunPlayer` is extending some form of `SunEntity` of sorts, where those methods are implemented in their entirety.

**Comment by kamcio96** [comment]
@mastercoms any changes with SpongeAPI?

**Comment by mastercoms** [comment]
https://gitter.im/GlowstonePlusPlus/GlowstonePlusPlus?at=56715bc02f6e4bb04ea7274c

**Comment by mastercoms** [comment]
I added some caching to offline UUID lookups, but I'm still working on threading the online requests.

**Comment by mastercoms** [comment]
I'm not sure about threading online requests, because in what scenario would the main thread not need to wait for the lookup to be done?

**Comment by mastercoms** [comment]
Will be fixed with https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/pull/205

**Comment by kamcio96** [comment]
```GlowServer``` has ```OfflinePlayer getOfflinePlayer(String name)```. It isn't possible to do it in that method.
We should add something like ```void getOfflinePlayer(String name, PlayerLookupCallback cb)```.

**Comment by mastercoms** [comment]
Yes.

**Comment by gdude2002** [comment]
#205 was merged, does that not fix this ticket?

**Comment by mastercoms** [comment]
No.

**Comment by mastercoms** [comment]
@gdude2002 Player lookup is still blocking.

**Comment by kaenganxt** [comment]
#604 partially fixed this issue. API methods for non-blocking lookups are now provided (e.g. `GlowServer#getOfflinePlayerAsync(String name)`, which returns a `CompletableFuture<OfflinePlayer>`).

Internal lookups (for example the whitelist or op command) still use blocking calls but can be replaced in the future.

**Comment by ethsmith** [comment]
Holy crap this is old. Back when this was made, Deathcap was still working on Glowstone++ and I was still a member of the G++ org.

**Comment by aramperes** [comment]
The main issue I see with migrating commands to use the non-blocking methods is the command return values. Command handlers are called synchronously and expect a boolean return value (for success/failure).

This isn't a big concern because the return value isn't used as of now, but we may need to use them for command blocks. Should we just ignore this problem for now, and extend the command API later for asynchronous support?
