### ISSUE TITLE
Is there a list of supported plugins for G++?

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#112]
Well, the title pretty much says everything.

**Comment by mastercoms** [comment]
We have [a list](https://docs.google.com/spreadsheets/d/11dumpB7MydS_KBWxwosZVnnA3cDPXfsAbEWM9WLmmdI/edit#gid=1336219743&vpid=A2), but nothing is on it. The original project has [a list](https://docs.google.com/spreadsheets/d/1_dvf1v7OjmP0RcL2gTWOdnBYbYut5cHYKMUpRWlUrx8/edit), and we haven't broken compatibility with any plugins, so you can use that.
