### ISSUE TITLE
does not work in linux aarch64

### ISSUE THREAD

**Issue by LinuxoidLinuxoidovich** [GlowstoneMC/Glowstone#1138]
Error: Invalid or corrupt jarfile glowstone-2.jar
Help me please.

**Comment by ghost** [comment]
I've tested it on Neoverse-N1 running Ubuntu 22.04, and I've encountered no issue, can you please provide which branch & version of Linux are you using exactly? and which branch & version of Java are you using?

Also try redownloading the Jar file, it might resolve the issue.

**Comment by mastercoms** [comment]
Closing for now, seems to be an unrelated issue
