### ISSUE TITLE
Spamming BlockUpdateMessage when player connects

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone#114]
Server spamming BlockUpdateMessage when player connects. 
Tons of them never stops.

**Comment by mastercoms** [comment]
Not happening for me. Can you help me reproduce this?

**Comment by DefinitlyEvil** [comment]
I captured message translation in Dragonet and it just spammed me. xD Maybe my fork is too old?

**Comment by mastercoms** [comment]
This bug has never happened in my memory. Perhaps it is something with Dragonet.

**Comment by DefinitlyEvil** [comment]
But I'bve never changed game logic before, and it was spamming block updates at random place.

**Comment by mastercoms** [comment]
As it seems like this bug cannot be reproduced, I am closing the issue.
