### ISSUE TITLE
A bunch of errors when launching eclipse

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#116]
I'm trying to help with the project and I'm trying to set up eclipse. After I import the project, I get tons of errors, mainly with org.apache.commons. This is the first time for me actually using git on my PC so I need some help.

**Comment by MOMOTHEREAL** [comment]
You need to setup Maven. Maven is used to build projects with its dependencies, and you will need to:
1. Download and Install Maven 3, by making sure to update the appropriate System variables for Maven and the JDK version 8.
2. Import Glowstone++ as a Maven project by using the m2eclipse plugin.

Also make sure that you forked the repository on first hand and using the `--recursive` option to clonse Glowkit as well.

**Comment by codekilla747** [comment]
Alright, ill give it a go
