### ISSUE TITLE
More errors in eclipse after installing maven to start developing!

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#119]
![image](https://cloud.githubusercontent.com/assets/16041839/11800412/346c4568-a2aa-11e5-9f9d-7e787c70fbf5.png)ERRORS EVERYWHERE!!!!!!!!

I've got maven installed after hours of fussing with it, and now eclipse is going crazy with a bunch of stuff that I know can't be wrong because it passes the builds on CircleCi. I did have some whitespace problems on my pull request, which it noticed and I fixed, but now all of these errors I know are fixed already. Does anyone know about how to fix this crap!

**Comment by MOMOTHEREAL** [comment]
I have the same problem with Glowkit with IntelliJ. I don't really know why, but it passes so I just ignore them.

**Comment by codekilla747** [comment]
So i should be able to rebuild glowstone++ even with these errors?

**Comment by MOMOTHEREAL** [comment]
For me it works at least, unless you bring some modifications to Glowkit as well.
To build the project, I use `setup.sh`, it gets some errors with Glowkit from time to time, but the build is successful and the server is functional.

**Comment by jimmikaelkael** [comment]
You can disable the checkstyles.

**Comment by codekilla747** [comment]
I can still develop, I just have to use that setup.sh script like @MOMOTHEREAL said.

@jimmikaelkael I think I already installed a plugin that does that, still not working. I'll just deal with it.

**Comment by jimmikaelkael** [comment]
I may not have spoken clearly enough: you need to disable the checkstyle config in the pom.xml

**Comment by codekilla747** [comment]
@jimmikaelkael Disabling the checkstyle cleared most of the errors but I still have a bunch (One of those is in the pom.xml, not related to the checkstyle)
