### ISSUE TITLE
Multiple Version Compatibility or compatibility with ProtocolSupport

### ISSUE THREAD

**Issue by quickplot** [GlowstoneMC/Glowstone#123]
It would be great if multiversion compatibility could be implemented either by having this plugin work https://github.com/ProtocolSupport/ProtocolSupport or making a custom implementation of it.  This would allow 1.7 clients and other clients to join a Glowstone++ server.

The error you get when you try and run the latest development build of ProtocolSupport is:
2015/12/16 11:47:45 [INFO] PluginTypeDetector: found 1 Bukkit, 0 Sponge, 0 Forge, 0 Canary, 0 unknown plugins (total 1)
2015/12/16 11:47:45 [INFO] Set PluginClassLoader as parallel capable
2015/12/16 11:47:45 [WARNING] java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/MinecraftServer
2015/12/16 11:47:45 [WARNING]   at protocolsupport.injector.NettyInjector.inject(NettyInjector.java:19)
2015/12/16 11:47:45 [WARNING]   at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:18)
2015/12/16 11:47:45 [WARNING]   at net.glowstone.GlowServer.loadPlugins(GlowServer.java:733)
2015/12/16 11:47:45 [WARNING]   at net.glowstone.GlowServer.start(GlowServer.java:475)
2015/12/16 11:47:45 [WARNING]   at net.glowstone.GlowServer.run(GlowServer.java:132)
2015/12/16 11:47:45 [WARNING]   at net.glowstone.GlowServer.main(GlowServer.java:107)
2015/12/16 11:47:45 [WARNING] Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.MinecraftServer
2015/12/16 11:47:45 [WARNING]   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
2015/12/16 11:47:45 [WARNING]   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
2015/12/16 11:47:45 [WARNING]   at java.lang.ClassLoader.loadClass(Unknown Source)
2015/12/16 11:47:45 [WARNING]   at java.lang.ClassLoader.loadClass(Unknown Source)
2015/12/16 11:47:45 [WARNING]   ... 6 more
2015/12/16 11:47:45 [INFO] The server is shutting down...

**Comment by mastercoms** [comment]
We can't make ProtocolSupport work, as it uses Mojang code, as shown by the error: `java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.MinecraftServer`

I will see what I can do in regards to adding support for this within Glowstone++ itself.

**Comment by mastercoms** [comment]
1.7.10 rejects our packets if we allow it to connect.
