### ISSUE TITLE
Glowstone++ is missing a vanilla-like End generator

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#124]
Actually, we are missing a generator for TheEnd dimension.
I'll try to provide that generator asap.

**Comment by mastercoms** [comment]
Ok, thank you! It's good seeing you here again!

**Comment by mastercoms** [comment]
Closed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/68e72bc178d6b2448eaf8d9d88dfa5d1f9437445
