### ISSUE TITLE
How can we implement blocks that can/can't be pushed by pistons?

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#125]
I am currently implementing the piston function into G++, but I need an input for this. Certain solid blocks, such as anvils, barriers, bedrock and portal blocks, as well as Tile Entities (block entities) cannot be pushed by pistons in Vanilla Minecraft.

How could we implement this? Easy solutions would include a "PistonAction" enum, or a GlowBlock boolean value, or a "GlowImmovable" interface.

**Comment by jimmikaelkael** [comment]
It may be a totally bad idea, but what about the materialValues.yml ?
We could have a default pistonMoveable set to false and an override to true in the target materials.

I'm not really sure it suits your needs...

**Comment by MOMOTHEREAL** [comment]
How can I access values from `materialValues.yml`? Also, I would think we could set it to `true` by default if we are going for a setting named `pistonMoveable` (or `pistonImmovable` set to `false` by default).

We also need to think of a volatile way to resolve this so it can work with Tile Entities as well. (Hence the idea of an empty interface). Although this would mean implementing the immovable blocks as well.

**Comment by jimmikaelkael** [comment]
Yeah I shifted the true/false logic you're right.

You get it like that: GlowBlock.getMaterialValues().isPistonMovable() for example
And you implement the isPistonMovable method in glowstone.block.BuiltinMaterialValueManager
The only real advantage to put this in the materialValue.yml would be server customization. However as I've said above I'm sure it's the best way to get this functionality implemented.

We should wait to hear what @mastercoms thinks about this.

**Comment by mastercoms** [comment]
Well, I think the materialValues route would be good, but I was thinking about replacing a lot of the item definition stuff with JSON based item definitions.

**Comment by MOMOTHEREAL** [comment]
On second thought, I don't think we should rely on a boolean value for this. In fact, some blocks will simply not move, but some will break when pushed, and some won't drop anything but vanish instead.

This leaves us with 4 possible values (examples): `false`, `true`, `break` (the block "disappears" when pushed, such as liquids and fire) and `drop` (the block breaks when pushed and drops something, such as redstone and doors).

**Comment by mastercoms** [comment]
I guess we can use a byte. 0 would be pushable, 1 would be immovable, 2 would disappear, and 3 would drop.

**Comment by deathcap** [comment]
There is an enum in Bukkit for this, [PistonMoveReaction](https://github.com/GlowstonePlusPlus/Glowkit/blob/bukkit%2Bglowkit/src/main/java/org/bukkit/block/PistonMoveReaction.java):

```java
public enum PistonMoveReaction {

    /**
     * Indicates that the block can be pushed or pulled.
     */
    MOVE(0),
    /**
     * Indicates the block is fragile and will break if pushed on.
     */
    BREAK(1),
    /**
     * Indicates that the block will resist being pushed or pulled.
     */
    BLOCK(2);
```

**Comment by mastercoms** [comment]
Use this: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/block/GlowBlock.java#L434
