### ISSUE TITLE
Spawn location acting oddly.

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#128]
When doing my tests on TheEnd dimension generation I noticed the that the spawn location is quite strange.
The GlowWord class is calling TheEndGenerator.getFixedSpawnLocation method when the world is generated which I then logged to see that my generator was returning a valid spawn location (I mean on ground).

However when I teleport to TheEnd dimension (I use Multiverse to be able to teleport), it spawns me elsewhere, not at the spawn location given by my generator. The worst is that it's dropping me right in the air (something near 100 as Y) and I fall on the ground and die of course...

Any idea ?

**Comment by mastercoms** [comment]
Spawn locations are weird in general. We should definitely look into improving how we check for safe spawn locations, or how we tell plugins about them.

**Comment by jimmikaelkael** [comment]
Ah yeah, it's defintely general and I've changed the title accordingly. I didn't noticed at first but I definitely pop often either in the air either in ground :)

But beside that @mastercoms I meant I was questionning about world data saves as the generators are returning something different than what's being used by multiverse as a spawn point.

**Comment by mastercoms** [comment]
I've been meaning to look at world IO, as users are reporting chunk IO errors, and other things, so I think we're in need of some fixing there. I'll also see stuff about spawning.

Would you happen to know how multiverse gets the spawn point?

**Comment by jimmikaelkael** [comment]
@mastercoms just checked MultiverseCore's DestinationFactory class, They are calling bukkit World.getSpawnLocation() method.

**Comment by mastercoms** [comment]
getFixedSpawnLocation is not implemented by OverworldGenerator, so spawn will not be safe for that. For the other generators, the world was getting the ChunkGenerator, and not the GlowChunkGenerator, so it was getting the null spawn location.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/ae912e8bb9aba10a84e2b82a2828e8fa5fed51a5

**Comment by jimmikaelkael** [comment]
@mastercoms Great, I'm glad it's fixed.
However you removed the canSpawn override in the OverworldGenerator when it should be left: it just checks you ever spawn on grass to mimic vanilla behavior.

**Comment by mastercoms** [comment]
I believe you can also spawn on leaves, and the default method checks for liquid, as well as other things.

**Comment by jimmikaelkael** [comment]
Yeah, but I think vanilla intentionally prevents you to spawn on sand for example to avoid spawning in deserts where the difficulty is high where you're a no stuff.

**Comment by mastercoms** [comment]
Then we can add sand to the blacklist. (after I test it)

**Comment by mastercoms** [comment]
It seems like you can spawn on sand. https://www.youtube.com/watch?v=zWj3dMVUOkA

**Comment by jimmikaelkael** [comment]
Yeah, you're right it seems I used wrong informations.
