### ISSUE TITLE
Glowstone++ is missing a superflat generator

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#129]
Not the most difficult to implement, but we're missing one.
I'll try to provide that superflat generator and it should be fairly easy to do that quickly :)

**Comment by codekilla747** [comment]
Yay! I noticed that when using multiverse to try and make a superflat world.

**Comment by MOMOTHEREAL** [comment]
Would this feature also provide a utility for custom Superflat worlds (Sandstone superflat, Snow superflat, etc instead of the standart Grass/Dirt/Bedrock)?

**Comment by jimmikaelkael** [comment]
Not yet, but this can be planned and would be easy to support.
The overworld/nether/theend generators already have some variables (actually private) that reflects what vanilla uses to customize world generations.

**Comment by mastercoms** [comment]
I have been meaning to add world customization, but before I can do that, I want to introduce a new configuration system.

**Comment by jimmikaelkael** [comment]
@mastercoms sounds great!
