### ISSUE TITLE
Add missing Minecraft commands

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#13]
Bukkit added server commands up to 1.7, but Spigot's Bukkit update for 1.8 removed all commands from the API because they instead pass through to the official Minecraft server. Glowstone can't do this obviously, so it relies on the commands in the API project, but they aren't updated for any new 1.8 features. Glowkit may have already added some; need to check. Full command list:

http://minecraft.gamepedia.com/Commands
- [x] /achievement
- [x] /ban
- [x] /ban-ip
- [x] /banlist
- [ ] /blockdata
- [x] /clear
- [ ] /clone
- [ ] /debug
- [x] /defaultgamemode
- [x] /deop
- [x] /difficulty
- [x] /effect
- [x] /enchant
- [ ] /entitydata
- [ ] /execute
- [x] /fill
- [x] /gamemode
- [x] /gamerule
- [x] /give
- [x] /help
- [x] /kick
- [x] /kill
- [x] /list
- [x] /me
- [x] /op
- [x] /pardon
- [x] /particle
- [ ] /playsound
- [x] /publish
- [ ] /replaceitem
- [x] /save-all
- [x] /save-off
- [x] /save-on
- [x] /say
- [x] /scoreboard
- [x] /seed
- [x] /setblock
- [x] /setidletimeout
- [x] /setworldspawn
- [x] /spawnpoint
- [x] /spreadplayers
- [ ] /stats
- [x] /stop
- [x] /summon
- [x] /tell
- [x] /tellraw
- [x] /testfor
- [ ] /testforblock
- [ ] /testforblocks
- [x] /time
- [x] /title
- [x] /toggledownfall
- [x] /tp
- [x] /trigger
- [x] /weather
- [x] /whitelist
- [ ] /worldborder
- [x] /xp
##

**Comment by mastercoms** [comment]
Here is a list of Glowkit commands: https://github.com/GlowstoneMC/Glowkit/tree/master/src/main/java/org/bukkit/command/defaults

**Comment by deathcap** [comment]
There's also two in the implementation, /color and /tellraw:

https://github.com/deathcap/GlowstonePlusPlus/tree/master/src/main/java/net/glowstone/command

**Comment by mastercoms** [comment]
Oh yes, I missed those, sorry.

**Comment by RandomAltThing** [comment]
Do we put 1.8 commands in glowstone or glowkit? And I'm not entirely sure what /debug does.

**Comment by RandomAltThing** [comment]
You could check who has debug enabled (and set it enabled) with a some ArrayList then idek what the command does so I can't tell you the rest

**Comment by mastercoms** [comment]
AFAIK commands shouldn't be in Glowstone.

**Comment by RandomAltThing** [comment]
Tell that to who added /colour and /title.

**Comment by mastercoms** [comment]
I have figured out the difference. You put commands that extend VanillaCommand in Glowkit and commands that extend BukkitCommand in Glowstone.

**Comment by RandomAltThing** [comment]
Well how do we know if they extends BukkitCommand? Bukkit isint updated

**Comment by Johni0702** [comment]
Every command that isn't on a vanilla server is a BukkitCommand.

**Comment by RandomAltThing** [comment]
But /tellraw is a vanilla command

**Comment by RandomAltThing** [comment]
And /title is a vanilla 1.8 command

**Comment by Johni0702** [comment]
/tellraw is probably in Glowstone because at the time it was added there wasn't any way of implementing it in Glowkit. I'm not sure about /title, might be the same reason.

**Comment by RandomAltThing** [comment]
Are they remain here? It seems weird that just 3 commands have the glowstone permission, why not make it bukkit to avoid confusion?

**Comment by mastercoms** [comment]
Yeah, I guess we should port them at some point.

**Comment by RandomAltThing** [comment]
/title is basically ready to go. It has no glowstone imports and you would just have to remove some bukkit ones (Files that will be in the same directory)

**Comment by mastercoms** [comment]
Yeah, it seems like https://github.com/Bukkit/Bukkit/pull/1111 seems to be the way to go for tellraw.

**Comment by ST-DDT** [comment]
There is a better/newer implementation in SpongeAPI, that you can use here as well.
https://github.com/SpongePowered/SpongeAPI/tree/master/src/main/java/org/spongepowered/api/text

**Comment by mastercoms** [comment]
Alright, thanks!

**Comment by mastercoms** [comment]
md5's BaseComponent seems like the thing we should be using for supporting all this JSON stuff.

**Comment by GreenBeard** [comment]
@deathcap you should uncheck /playsound it has a major update in 1.9

**Comment by gdude2002** [comment]
@GreenBeard This is a ticket about 1.8, though.

Speaking of which, has there been any more movement on this?

**Comment by robotman3000** [comment]
What version of minecraft should the behavior for the remaining commands match?

**Comment by mastercoms** [comment]
Glowstone targets the latest Minecraft version, so 1.12

**Comment by mastercoms** [comment]
Though, this issue is better: #499

**Comment by robotman3000** [comment]
Cool, thanks.

**Comment by robotman3000** [comment]
Is there a specific reason why this issue is still open?

**Comment by gdude2002** [comment]
I was just about to close it in favour of #499 tbh
