### ISSUE TITLE
Flow Noise

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#134]
Could we use flow noise to replace our internal noise? https://github.com/flow/noise

We already use flow networking.

**Comment by jimmikaelkael** [comment]
@mastercoms Theoretically it should be possible to use it as long as we use Fractional Brownian motion.
The reason I kept it internally is to avoid generation changes if something is changed in an external noise library.

Another bad thing to could come back from using noise libraries (if we use their own fBm method provided that they have one, but here I was thinking about bukkit noise implementation) is the farlands symptoms.
You can look at the PerlinOctaveGenerator class where I left a comment at line 47 concerning farlands.

**Comment by mastercoms** [comment]
I guess we can make a new branch using it and check to see if it has any problems. Though, I am not sure it has any benefit, so we will also have to check that too.

**Comment by mastercoms** [comment]
I tested it, and the noise isn't suitable for Minecraft, really. There were no farlands though.
