### ISSUE TITLE
Crafting Bug

### ISSUE THREAD

**Issue by BalloonChamp** [GlowstoneMC/Glowstone#137]
When I went into the inventory 2 by 2 crafting grid to make some planks, I placed the wood and it stayed for a fraction of a second, then disappeared. I exited the inventory and the logs flew out of me and I picked them up. This bug also happens in the regular crafting table.

**Comment by BalloonChamp** [comment]
this appears in console when I put wood into the inventory 2 by 2 crafting grid

15:17:02 [INFO] BalloonChamp: [rejected] WindowClickMessage(id=0, slot=3, button
=0, transaction=25, mode=0, item=null)

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/0be6bc0a5ec62dbf8aa967d831c7a1c47e6536fc
