### ISSUE TITLE
Spawn egg bug/ block break bug.

### ISSUE THREAD

**Issue by BalloonChamp** [GlowstoneMC/Glowstone#139]
Hi again,
So 2 simple bugs. 
1. When I try to spawn an animal from an egg, it spawns a pig with no AI
1. Every time I break a block, it lags bad. And this is not the fact that the server is lagging, because I put 4 gigs of ram on it.

**Comment by twizmwazin** [comment]
The first issue is partially fixed in my PR. AI has not been implemented in any branch yet.

**Comment by BalloonChamp** [comment]
Ok

**Comment by BalloonChamp** [comment]
Question, On my branch of GlowstonePlusPlus, I want to change the dependency to My version of Glowkit, how would i do that?

**Comment by mastercoms** [comment]
What is your tps when you break a block? Are there any console errors?

Just do mvn install in the Glowkit folder, and you should be good.

**Comment by mastercoms** [comment]
Closing as spawn egg bug was fixed, and there is no data or reproducibility for the lagging.
