### ISSUE TITLE
Update to use flow-network release once available (instead of submodule)

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#144]
Currently Glowstone++ is using a snapshot version of com.flowpowered flow-networking. Once a release is published (waiting on https://github.com/flow/network/issues/11), we should switch to the release version.

This will have several advantages (ensuring stability, avoiding the unnecessary daily update checks, easier installs, etc.), more details: http://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it

**Comment by mastercoms** [comment]
We need to use the fake snapshot version for netty 5.
