### ISSUE TITLE
Glowstone++ no longer <3s the CPU and RAM

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#145]
CPU and RAM usage seems to have gone up a lot in the later builds. I've seen CPU usage go up to around 50% on my i7-4510U. The JVM allocates 1.5G of RAM, although Glowstone++ seems to be only using 600MB. Before, CPU usage was around 8%, and JVM allocated 500MB, with Glowstone++ using around 200MB. I think this has to do with my new liquid flow logic.

**Comment by TheRaspPie** [comment]
I encountered this too and wondered if there may be a bug.

**Comment by mastercoms** [comment]
I removed the liquid flow code, and the resource usage went down. I also noticed that BlockLiquid.updateBlock is called a lot, so I think I may remove the random tick functionality from liquid blocks.

**Comment by TheRaspPie** [comment]
Okay, thanks!
