### ISSUE TITLE
mineflayer client hangs Glowstone++ server

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#146]
Using the latest Glowstone++ (65111e) I can connect with the official client, but https://github.com/PrismarineJS/mineflayer (also latest dev version, c3f67f9) hangs and seems to DoS the server, but it does not crash:

```
# using simple mineflayer example client
mineflayer $ NODE_DEBUG=minecraft-protocol node examples/echo.js  localhost 25565
MC-PROTO: 65282 Old-styling packet
MC-PROTO: 65282 writing packetId handshaking.set_protocol (0x0)
MC-PROTO: 65282 { protocolVersion: 47,
  serverHost: 'localhost',
  serverPort: 25565,
  nextState: 2 }
MC-PROTO: 65282 Old-styling packet
MC-PROTO: 65282 writing packetId login.login_start (0x0)
MC-PROTO: 65282 { username: 'echo' }
# hangs here until it eventually times out after a few seconds
mineflayer $ 
```

The server kicks the client for timing out:

```
+ java -mx2G -jar target/glowstone++-1.8.9-SNAPSHOT.jar
23:41:44 [INFO] This server is running Glowstone++ version null (Implementing API version null)
23:41:45 [INFO] Recipes: 295 shaped, 63 shapeless, 24 furnace, 10 dynamic, 14 fuels.
23:41:45 [WARNING] The server is running in offline mode! Only do this if you know what you're doing.
23:41:45 [INFO] Scanning plugins...
23:41:45 [INFO] Preparing spawn for world...
23:41:45 [INFO] dungeon generated: -335,8,-325
23:41:46 [INFO] Preparing spawn for world: 1%
23:41:47 [INFO] Preparing spawn for world: done
23:41:47 [INFO] Preparing spawn for world_nether...
23:41:48 [INFO] Preparing spawn for world_nether: 76%
23:41:48 [INFO] Preparing spawn for world_nether: done
23:41:48 [INFO] Preparing spawn for world_the_end...
23:41:48 [INFO] Preparing spawn for world_the_end: done
23:41:48 [INFO] Binding to address: 0.0.0.0/0.0.0.0:25565...
23:41:49 [INFO] Successfully bound to: /0:0:0:0:0:0:0:0:25565
23:41:49 [INFO] Ready for connections.
23:42:20 [INFO] [/127.0.0.1:60220] kicked: Timed out
```

After the server gets into this state, I can no longer connect even with the official client (it, too, times out), and the server console accepts input but does is not responsive to any commands.

Thread dump (from Ctrl-): https://gist.github.com/deathcap/f693a83c749199824926

There were Glowstone++ / mineflayer incompatibilities previously (I last tested with https://github.com/PrismarineJS/mineflayer/issues/253) but IIRC, this used to work - maybe regressed with protocol updates?

**Comment by mastercoms** [comment]
Does this work in the build before Netty 5?

**Comment by deathcap** [comment]
Yes same results if I rebuild Glowstone++ with FlowNetworking without https://github.com/GlowstonePlusPlus/network/commit/efae101743c12e6e0beb177fdd325fa6506204ef. Will test further to narrow this down

**Comment by deathcap** [comment]
No longer reproduces on build 511, downloaded from CircleCI or built locally - seems this was fixed by https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/20435e9799195a5ed83677082ef36dddb357955f
