### ISSUE TITLE
After crafting an item the items drop out of the crafting table giving me the item and items I used to craft it

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#158]
**Java version**: `build 1.8.0_66-b17`
**OS**: `Mac OSX El Capitan (10.11)`
**Glowstone ver.**: `newest (40df0c7)`

**What I did**:
I used creative mode the get 2 sticks and a diamond then I switched back and put them into a crafting table to make a diamond shovel. After I pulled out the shovel the items disappeared from the other slots (as they should) then I exited out and items that I used to craft the diamond shovel dropped to the ground with the shovel that I crafted still in my inventory.

**Comment by mastercoms** [comment]
I tested it and this only happens on a click, not a shift click. Crafting does not happen when the client clicks, so the items only disappear to the client, but the server thinks it is still there.
