### ISSUE TITLE
JavaDoc build issues [$10 awarded]

### ISSUE THREAD

**Issue by gdude2002** [GlowstoneMC/Glowstone#166]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=30141859)](https://www.bountysource.com/issues/30141859-javadoc-build-issues?utm_source=30141859&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Due to doclint, the Javadocs for all repos [are not building](https://bamboo.gserv.me/download/GSPP-SRV-JOB1/build_logs/GSPP-SRV-JOB1-12.log). What should we do?
- Disable doclint
- (_Decided_) Fix the new doclint issues added in Java 8

Additionally, do we want to build a Javadocs JAR?
##

**Comment by mastercoms** [comment]
I would like to fix the doclint issues.

**Comment by gdude2002** [comment]
Should we also do that for the `flow-networking` repo?

**Comment by mastercoms** [comment]
Yes

**Comment by gdude2002** [comment]
Alright, I might take a look into it when I get back home

**Comment by mastercoms** [comment]
Ok, thanks!

**Comment by gdude2002** [comment]
I have added a [$10 bounty](https://www.bountysource.com/issues/30141859-javadoc-build-issues) for this ticket as I don't have time to handle it myself, but would like to see it completed.

**Comment by gdude2002** [comment]
This has been solved across the board by @kamcio96
