### ISSUE TITLE
Entity destory packet is not send when disconnecting

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#170]
When a player gets disconnected or is kicked, the EntitiesDestoryMessage is not broadcasted to all clients. When interacting with the player the servers notices that there is no entity: `Player Paulomart tried to attack an entity that does not exist`

![2016-01-24_12 34 29](https://cloud.githubusercontent.com/assets/4148404/12535990/f985d70e-c296-11e5-9440-bcf03f96f81e.png)

**Comment by Paulomart** [comment]
Is it possible that no entities are removed? I think it _should_ be done it `pulse()` but could not find anything?

**Comment by mastercoms** [comment]
fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/e326e50342560543fbbd5c42ebd03d9b19e54daa
