### ISSUE TITLE
Water broken?

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#179]
I think there is a bug with water flow in current master: 
![2016-01-25_16 54 33](https://cloud.githubusercontent.com/assets/4148404/12558222/d547d826-c38e-11e5-8b43-c1942b843ed6.png)

As you can see in the picture the water flows all accross the world. I _should_ flow down, as in Spigot:
![2016-01-25_18 11 05](https://cloud.githubusercontent.com/assets/4148404/12558266/036fe7e8-c38f-11e5-9a5d-8b381c179747.png)

Like since 6cd1bbc68fe46e1a8fceea2a8fc82eca01ec0ab4?

Also: Server is lagging as hell!

**Comment by codekilla747** [comment]
@mastercoms has been working on a fix for this I think. I thought he already merged it though

**Comment by mastercoms** [comment]
oh lol, this is why i should test things instead of using the github editor when im not home
