### ISSUE TITLE
Inventory sync issue

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#181]
Because images say more then words. I dobble click on in the inventory,
![gif](http://i.imgur.com/EkdKMbW.gif) http://i.imgur.com/EkdKMbW.gif

Console claims that it was rejected:

```
2016/01/25 22:31:14 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=7, slot=-999, button=0, transaction=4, mode=4, item=null)
2016/01/25 22:31:51 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=3, button=0, transaction=1, mode=0, item=ItemStack{STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=§f}})
2016/01/25 22:31:51 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=3, button=0, transaction=2, mode=6, item=null)
2016/01/25 22:31:53 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=-999, button=2, transaction=5, mode=5, item=null)
2016/01/25 22:31:54 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=66, button=0, transaction=6, mode=0, item=ItemStack{STAINED_GLASS_PANE x 10, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=§f}})
2016/01/25 22:31:54 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=-999, button=2, transaction=17, mode=5, item=null)
2016/01/25 22:31:55 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=85, button=0, transaction=18, mode=0, item=null)
2016/01/25 22:31:56 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=49, button=0, transaction=19, mode=0, item=ItemStack{STAINED_GLASS_PANE x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name=§f}})
2016/01/25 22:31:56 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=49, button=0, transaction=20, mode=6, item=null)
2016/01/25 22:31:57 [INFORMATION] Paulomart: [rejected] WindowClickMessage(id=8, slot=-999, button=2, transaction=25, mode=5, item=null)
```
##

**Comment by Paulomart** [comment]
Hotbar updates instand because of a plugin. Items that you put into you player inventory, are gone when reopening the inventory (self or container)

**Comment by mastercoms** [comment]
is this with a plugin?

**Comment by mastercoms** [comment]
Could I see the plugin's code?

**Comment by Paulomart** [comment]
Sure, I created a Test plugin: https://github.com/Mystalion/GlowTest/tree/inventory-sync

**Comment by mastercoms** [comment]
Not sure if we use events correctly for the click handler, then.

**Comment by Paulomart** [comment]
Handler seems to be fine, the server is not accepting the transaction. Maybe a client side bug that is worked around in craftbukkit?

**Comment by Paulomart** [comment]
When clicken outsite it now gives a exception:

```
2016/02/11 17:57:53 [SCHWERWIEGEND] Error while handling WindowClickMessage(id=4, slot=-999, button=0, transaction=50, mode=0, item=null) (handler: WindowClickHandler)
java.lang.ArrayIndexOutOfBoundsException: -999
	at java.util.Arrays$ArrayList.get(Unknown Source)
	at net.glowstone.inventory.GlowInventory.getItem(GlowInventory.java:320)
	at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:234)
	at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:31)
	at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:26)
	at net.glowstone.libs.com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
	at net.glowstone.libs.com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
	at net.glowstone.net.GlowSession.pulse(GlowSession.java:428)
	at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
	at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:173)
	at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
	at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by Paulomart** [comment]
![glowtest](https://cloud.githubusercontent.com/assets/4148404/12983385/5b5ebdf0-d0e9-11e5-933b-f997bf34a4c5.gif)

Also the items can get in the bottom inventory if you shift click.

**Comment by mastercoms** [comment]
As of this commit: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/930a3c8156ad7e200fee959d5ceb9dc5fc1e2e53, the outside slot should work, but I'm not sure if or how the cursor item would be reset.

Also, the shift click issue seems to be client side only - is there another bukkit did to resolve it?

**Comment by Paulomart** [comment]
Not sure, what CraftBukkit did there, maybe updating the whole inventory would be faster and better?

**Comment by mastercoms** [comment]
maybe we could guess where the item went for the client and then tell it to revert the change?

**Comment by Paulomart** [comment]
Would have to mess with the DragTracker to do that

**Comment by Paulomart** [comment]
Also happing when open a new inventory on click, the item is still there then.

**Comment by mastercoms** [comment]
What do you mean?

**Comment by Paulomart** [comment]
Maybe adapt this change Mystalion/MysticStone@db6895debe9ce25af7feaf714dbea58ca9238ce5

**Comment by Paulomart** [comment]
Cannot provide a test case now, ask @summsi if he has time

**Comment by mastercoms** [comment]
Is there a GIF of the issue that you could show me?

**Comment by summsi** [comment]
![bug 2](https://cloud.githubusercontent.com/assets/10583273/13015784/3dfb886a-d1bb-11e5-8036-02cf7dd96e80.gif)

**Comment by mastercoms** [comment]
Are you sure the inventory is cancelling events for the bottom inventory as well?

**Comment by Paulomart** [comment]
No, because we care only about the top one

**Comment by mastercoms** [comment]
Could I see the code for this plugin?

**Comment by Paulomart** [comment]
Really big lib, will try to extract the bug and put in Mystalion/GlowTest

**Comment by Paulomart** [comment]
https://github.com/Mystalion/GlowTest/blob/inventory-sync/src/main/java/com/mystalion/glowtest/GlowTestPlugin.java

![inventory2](https://cloud.githubusercontent.com/assets/4148404/13029392/4a4b0ca0-d28b-11e5-81c8-51cd6b610dd9.gif)

**Comment by Paulomart** [comment]
The class plane shuld not be there.

**Comment by Paulomart** [comment]
Note: I fixed this in my patch: https://github.com/Mystalion/MysticStone/blob/master/patches/0003-Fix-inventory-sync-issues.patch

**Comment by mastercoms** [comment]
And all window click logic works? If you want, send it as a PR.

**Comment by Paulomart** [comment]
It only calls updateInventory so I guess it should not break anything. Will PR tomorrow
