### ISSUE TITLE
Fall damage not working properly

### ISSUE THREAD

**Issue by LuxusDarkangel** [GlowstoneMC/Glowstone#182]
You can avoid fall damage following these steps:
1.- Go somewhere high (i haven't tried this on very high places, only 5-7 blocks)
2.- Jump to fall and jump again just before reaching the ground
3.- If done properly, you'll avoid fall damage

It's really easy to reproduce once you get the trick. Anyway I can upload a video showing it if needed.
##

**Comment by mastercoms** [comment]
A video would be appreciated.

**Comment by mastercoms** [comment]
@LuxusDarkangel sorry to pester you, but could you please post a video of this behavior? I was not able to replicate it, but I think it's just me doing it wrong.

**Comment by LuxusDarkangel** [comment]
Sorry, github didn't notify me about your other reply. I'll upload the video later today, hope you can fix it :D

**Comment by LuxusDarkangel** [comment]
Ok, i realized that this issue was very easy to reproduce in build 632, it's "fixed" now (i guess it was part of another bug), but keeps happening sometimes because of this:

You should get fall damage if you fall from 4 blocks, but in glowstone this happens when you fall from 5 blocks (or 4.5? because if you get in a 4 blocks high tower, jump and you get far enough you receive fall damage, but if you get near where you jumped, you won't, it's really strange)
So, the bug itself is gone now, but fall damage keeps working wrongly.

**Comment by gdude2002** [comment]
This ticket needs categorization on the [waffle board](https://waffle.io/GlowstoneMC/Glowstone).

Has this ticket seen any movement or has there been any action expected since the previous comment?

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/aa26e04ff6403e5f50724a6a92c265b7e4b5d6e0.
