### ISSUE TITLE
Legacy ping support (fe01 / fe packet)

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#186]
Glowstone++ supports supports the 'modern' status handshake ping (Netty-based protocol), but not the "legacy" (0xfe packet) ping. According to http://wiki.vg/Protocol#Legacy_Server_List_Ping:

> While not technically part of the current protocol, legacy clients may send this packet to initiate Server List Ping, and modern servers should handle it correctly.

All vanilla Minecraft servers 1.4.4+ support this ping, including 1.8.9 and 1.9 snapshots. Client software such as server status pages may still use it (being much simpler than the modern ping), so I think it would be a good idea for Glowstone++ to support it.

References:
- https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/net/protocol/HandshakeProtocol.java - add here or nearby? but note 0xfe does not have a varint length or packet id field, so special-casing it may be the most feasible approach
- https://github.com/deathcap/node-minecraft-ping - tool for sending various ping types for testing; can also use older vanilla client versions, check if Glowstone++ appears in the server list
- https://github.com/PrismarineJS/node-minecraft-protocol/pull/334 - adding support to another server implementation, could be useful for comparison

Attempts to send a 0xfe01 ping currently will timeout, causing this message in the server log:

```
11:03:41 [INFO] [/127.0.0.1:57037] kicked: Timed out
```
##

**Comment by mastercoms** [comment]
:+1:

**Comment by deathcap** [comment]
Another tool to help test legacy pings: https://github.com/WaterfallMC/LegacyPinger

**Comment by GreenBeard** [comment]
Does anyone know where the length of packets is now read? There are two functions in [GlowProtocol.java](https://github.com/GlowstoneMC/GlowstonePlusPlus/blob/f84d3f08644f2fd43d2828468855bedd87ac9060/src/main/java/net/glowstone/net/protocol/GlowProtocol.java) and I don't understand where the length of the packet is read in newReadHeader but I do understand the old readHeader. The reason I want to know is because the old ping packet didn't have the length prepended to it.

**Comment by gdude2002** [comment]
This ticket needs categorization on the [waffle board](https://waffle.io/GlowstoneMC/Glowstone).

Has this ticket seen any movement or has there been any action expected since the previous comment?

**Comment by GreenBeard** [comment]
@gdude2002 I had this finished for a week or so now just forgot to make the pull request. I'll do that now.

**Comment by gdude2002** [comment]
Thanks, I'd appreciate that \o/
