### ISSUE TITLE
Teleport on PlayerMoveEvent causes client desync

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#198]
When teleporting a client on PlayerMoveEvent, the player is teleported for all other players on the server, but not for himself. Cancelling the event dosent help. Only teleporting on the next tick.

Code:

```
    @EventHandler
    public void onPlayerMove(PlayerMoveEvent e) {
        if (e.getTo().getY() < 0) {
            e.getPlayer().teleport(limbo.getSpawn());
        }
    }

```

**Comment by mastercoms** [comment]
What is the type of limbo?

**Comment by Paulomart** [comment]
JavaPlugin, getSpawn() returns a Location

**Comment by mastercoms** [comment]
The best practice is to set the player's location using `setTo()` in the event, but I have now added a workaround for plugins that don't use the recommended way.
