### ISSUE TITLE
Bonemeal on grass no longer works as of #16

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#2]
https://circleci.com/gh/deathcap/GlowstonePlusPlus/16

https://github.com/deathcap/GlowstonePlusPlus/commit/990a916c88760a3d86b673f6a382cdf7dd78e2eb

**Comment by deathcap** [comment]
Fixed in https://circleci.com/gh/deathcap/GlowstonePlusPlus/21

**Comment by XakepSDK** [comment]
oops, sorry.
