### ISSUE TITLE
Invisible blocks?

### ISSUE THREAD

**Issue by Paulomart** [GlowstoneMC/Glowstone#202]
![2016-02-15_19 28 00](https://cloud.githubusercontent.com/assets/4148404/13057122/4afbe044-d41a-11e5-9850-81cabf14f24b.png)
![2016-02-15_19 28 06](https://cloud.githubusercontent.com/assets/4148404/13057123/4b1cf7a2-d41a-11e5-8a21-0079716e3b76.png)

Running lastest Glowstone++, patched with MysticStone, but It should not make a difference. Also runnung behind bungee.
##

**Comment by gdude2002** [comment]
Looks like a chunk error - are you able to reproduce with vanilla Glowstone++?

**Comment by Paulomart** [comment]
Happens only after respawn, maybe related to bungee
![2016-02-15_19 33 55](https://cloud.githubusercontent.com/assets/4148404/13057264/2e84e7ac-d41b-11e5-93e6-43c7881ab840.png)
![2016-02-15_19 33 51](https://cloud.githubusercontent.com/assets/4148404/13057265/30f85816-d41b-11e5-8b56-ce9986d57e30.png)

**Comment by gdude2002** [comment]
Try to eliminate variables; try it without bungee, or without MysticStone. See if not using either of those fixes it.

**Comment by Paulomart** [comment]
Above was without both, just after a respawn

**Comment by gdude2002** [comment]
Alright, paging doctor @mastercoms 

I'm not really sure what to have you check; I'm assuming you've already looked at the logs, so I'll see what he wants us to look at.

**Comment by Paulomart** [comment]
Its so strange, maybe glowstone is sending the chunks weird? To early or something?

**Comment by gdude2002** [comment]
Hard to say without some more info, just not yet sure what to look for.

**Comment by Paulomart** [comment]
Will try to debug the client now..

**Comment by mastercoms** [comment]
I have experienced this bug as well. I've noticed if you break a block in that area, it will show the blocks.

**Comment by Paulomart** [comment]
So that is what if got, dont know that todo with it thou :D https://gist.github.com/Paulomart/f8aa774c129a1b51b365

**Comment by gdude2002** [comment]
That doesn't look too relevant, honestly.. And there's nothing in your server logs?

**Comment by Paulomart** [comment]
Just getting #199 sometimes, but in the moment I respawn or something

**Comment by gdude2002** [comment]
It's probably related to that, then? Seems likely anyway.

**Comment by Paulomart** [comment]
Sometimes chunks get invisible even if they loaded before. (Sorry gif is too big)

**Comment by gdude2002** [comment]
Well, maybe rolling through #199 might net us some answers for this one as well - never know.

**Comment by Paulomart** [comment]
I can reproduce it 99% on my server, if someone wants to take a look, ping me at gitter

**Comment by mastercoms** [comment]
I might have fixed this inadvertently. Could you confirm?

**Comment by mastercoms** [comment]
Closing this as I haven't been seeing this bug recently when I had been before. (and bug reporter seems to be inactive :frowning:)
