### ISSUE TITLE
Thunder is crazy

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#206]
Has anyone noticed how much frequently the lightning bolt strikes ?

**Comment by mastercoms** [comment]
Wow, that's a lot of thunder. Our server must be angry!

**Comment by jimmikaelkael** [comment]
According to gamepedia:
> For each loaded chunk, every tick there is a 1⁄100,000 chance of an attempted lightning strike while it is thunderstorming.

We are at 1/25,000 chance.
