### ISSUE TITLE
Nether hangs

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#209]
It wasn't happening until recently, but now as soon as I teleport to the nether the server hangs...
I get kicked after a while for 'time out' reason and the server is frozen.

I've noticed too that I'm often kicked for hacking reason at first connection attempt. 

Sometimes I enter infinite loops where I start a server with fresh worlds, I get spawned in the air then fall and die. I'm sent back to another location then I'm kicked for hacking reason, I reconnect and the loop start over again.

Server log:
http://pastebin.com/ys8Gu2sD

Note (tests regarding nether freeze bug):
Not happening with 05caa512b992e62314b46a66f2d9c87e0d697d89
Hapening with e0646d22080f8a0293a80a8efc67ce762a612b0f
Hapening with c42b204e4c4e17fde833837acc5a5d7a1ee0c7e5 (for reference as above faulty commit name appear in commit message)

**Comment by mastercoms** [comment]
Maybe the lava is crashing the server?

**Comment by jimmikaelkael** [comment]
Might be...

**Comment by jimmikaelkael** [comment]
Erm, I can't tell you why, but just changing back the tickMap type back to HashMap in GlowWorld solves the problem.

**Comment by jimmikaelkael** [comment]
This is caused by BlockFire, I'm filing a PR.
