### ISSUE TITLE
Liquid physics are not perfectly vanilla-like

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#21]
https://github.com/deathcap/GlowstonePlusPlus/pull/20#issuecomment-92104993

**Comment by mastercoms** [comment]
For flowing down:
water checks if there are any air blocks on the same Y within a 3 block radius of the block it was placed on. If so, it gets the cardinal direction of the nearest? air block and then only flows in that direction
For correct block attachment physics, some things have to be changed in the afterPlace function.

**Comment by jimmikaelkael** [comment]
There's also the fact that lava is flowing faster in the Nether.
@mastercoms Did the physics PR handled this ?

**Comment by mastercoms** [comment]
No, these are some problems that have yet to be fixed.

And I did not know that lava flows faster in the Nether. I will fix that.

**Comment by jimmikaelkael** [comment]
It's wrote here: http://minecraft.gamepedia.com/The_Nether?cookieSetup=true
In the Environment paragragh.
No data on speed, tought.

**Comment by mastercoms** [comment]
It also flows further.

**Comment by jimmikaelkael** [comment]
It seems to me that it flows more than vanilla. Is it the consequence of flowing in all directions ?

**Comment by mastercoms** [comment]
Yes, it is because flowing blocks spread more than they would in vanilla.

And I'll do that too.

**Comment by mastercoms** [comment]
http://minecraft.gamepedia.com/Liquids#How_liquids_work

**Comment by SamNosliw** [comment]
The issues with increased flow speed/distance should be easy to solve, currently its just stored in static variables, so you could add two more for NETHER_TICK_RATE_LAVA and STRENGTH_MIN_NETHER_LAVA then check the world type before using one of the variables.


    private static final byte STRENGTH_MIN_WATER = 7; // Flow distance for water
    private static final byte STRENGTH_MIN_LAVA = 4; // Flow distance for lava
    private static final int TICK_RATE_WATER = 5; // How often water updates
    private static final int TICK_RATE_LAVA = 20; // How often lava updates

**Comment by mastercoms** [comment]
Oh, hello there! I would first like to thank you for your work so far on implementing water physics.

I found two more pages that may be of use:
http://minecraft.gamepedia.com/Lava#Usage
http://minecraft.gamepedia.com/Water#Behavior

I would like to respond to [your comment](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/pull/20#issuecomment-102806646) in the other thread here, since that one is closed.

Lava doesn't disappear slower than it spreads, it is just that some blocks randomly stay longer. The spread speeds look fine though.
