### ISSUE TITLE
A few suggestions for the project

### ISSUE THREAD

**Issue by twizmwazin** [GlowstoneMC/Glowstone#221]
Hi, I wasn't terribly sure where this would best fit so I figured I'd just make an issue. I haven't really contributed much to the project (although I'd like to), but I have a few suggestions/complaints about the project.
- First, I feel that setup is too complicated. I'd really like a clone-and-go setup. This in my mind would mean splitting off the two submodules and using them as maven dependencies. I really think the current setup is annoying and clunky.
- Second, I feel that Glowkit is rather bloated. It seems to have an everything-and-the-kitchen-sink approach right now, with every possible patch included. For lack of a better word I think it is bloated. I feel that the API should be kept as close to upstream as possible, only having small patches that are absolutely necessary to retain functionality. Using the unmodified Bukkit API would be ideal. I feel efforts should go towards implementing the Bukkit APIs before anything else.
- I'm not really sure about how to go about fixing this, but I also feel that the project is way to closely tied with Bukkit. This could be somewhat detrimental in the long run, making it difficult to split the project from Bukkit.
- A bit petty, but the repo could also be cleaned up a little bit. There are some files in the root that I believe are totally unused.

These are just my suggestions and concerns, I'm curious to see what others agree or disagree on.

Another thing that just popped in to my mind would be a suggestion to move towards a scheduled, stable release model. Currently it is rolling, however a more structured cycle would arguably help the project come together and be closer to releasing a production-ready product.

**Comment by mastercoms** [comment]
1. I mean, they are currently maven dependencies, but we don't have repo.glowstone.net set up to provide them.

1. Yes, Glowkit is bloated so much that there are duplicate methods.

1. kamcio and I are working on abstracting away from Bukkit.

1. I'll look into deleting some unused files

1. I was thinking about starting to version Glowstone++ since we've gotten a lot of bugs fixed and features added so that rolling release is not needed as much.

**Comment by gdude2002** [comment]
@mastercoms Whose maven repo were we going to use again?

**Comment by mastercoms** [comment]
Greatman's

**Comment by Nicewuerfel** [comment]
Sorry if there is some kind of obvious answer to this question, but couldn't you use the Central Repository?

**Comment by gdude2002** [comment]
No, only releases are allowed there, but we need to upload development artifacts.

**Comment by Nicewuerfel** [comment]
Granted, you still need to specify a snapshot repo in the pom.xml, but you can deploy snapshots to oss.sonatype.org. I never understood why so many people feel the need to host their own repos...

**Comment by mastercoms** [comment]
Glowkit bloat is fixed. Unnecessary or redundant API features were removed or moved to the server logic.

**Comment by mastercoms** [comment]
What files do you think should be deleted?

**Comment by mastercoms** [comment]
Closing as these suggestions have been considered. For further discussion, I would recommend a forum post.
