### ISSUE TITLE
ItemSpawn entity types are no longer stored as durability.

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#228]
Since 1.9, ItemSpawn (spawn eggs) have their entity type stored as the `EntityTag:id` tag, instead of the durability value.

From the Minecraft wiki: "Spawn eggs can no longer be addressed by numeric data id, like: `give @p spawn_egg 1 50`. The spawnable item from a spawn egg is now addressed by a datatag: `give @p spawn_egg 1 {EntityTag:{id:"Creeper"} }`"

This causes the ItemSpawn functionality to no longer work with durability, and causes the following NPE:

```
java.lang.NullPointerException
        at net.glowstone.block.itemtype.ItemSpawn.rightClickBlock(ItemSpawn.java:28)
```

**Comment by Paulomart** [comment]
This is also true for potions.https://github.com/MylesIsCool/ViaVersion/blob/master/src/main/java/us/myles/ViaVersion/slot/ItemSlotRewriter.java#L63

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/93ec95c1f330780b3fc41e94e34f845f4c670c1d
