### ISSUE TITLE
Possibly invalid(unused) method: leftClickBlock

### ISSUE THREAD

**Issue by ishitatsuyuki** [GlowstoneMC/Glowstone#241]
A line in [`BlockType.java`](https://github.com/GlowstoneMC/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/block/blocktype/BlockType.java) looks never used:

```
public void leftClickBlock(GlowPlayer player, GlowBlock block, ItemStack holding){//nothing}
```

This is only called when player dig a block and the "complete dig" packet is rejected by some reason. This should be unrelated. As a reference, it is handled in [`DiggingHandler.java`](https://github.com/GlowstoneMC/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/net/handler/play/player/DiggingHandler.java).

If the player left click the block, it's either handled by "break" or "interact". There should be no "left click".

These were added by a commit (https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/ed94ee1f35382fa325096f5000703c421012549e), which is more than 1 year old and before proper redstone support was implemented.

I'm not sure with this (didn't try to remove and see the behavior), but I hope you guys to inspect the code.

**Comment by aramperes** [comment]
Could this be related to item frame and noteblock interaction?

**Comment by ishitatsuyuki** [comment]
Item frame is an entity.

**Comment by mastercoms** [comment]
Would be useful for plugins wanting to make custom features for blocks.

**Comment by ishitatsuyuki** [comment]
@mastercoms - wait: I have mentioned the code is invalid and possibly never executed. Had you reviewed the code?

**Comment by ishitatsuyuki** [comment]
At least this is an invalid API - rightClickBlock for items, and left for block!?

**Comment by ishitatsuyuki** [comment]
Hey @mastercoms . Don't close issue without a proper reason. Please reopen this.

**Comment by kamcio96** [comment]
I will review code. mastercoms dosen't have time now ;)

**Comment by mastercoms** [comment]
@ishitatsuyuki Sorry, lost track of this issue.

**Comment by mastercoms** [comment]
definitely still called. interact is for right clicks.
