### ISSUE TITLE
Placing blocks over blocks

### ISSUE THREAD

**Issue by GreenBeard** [GlowstoneMC/Glowstone#245]
1. When any block is placed over a `LONG_GRASS` or `DEAD_GRASS` block it doesn't update properly on the client end, only the block data updates not the block id.
2. When attempting to place a block over a `DOUBLE_PLANT` it doesn't, instead it places it adjacent.

**Comment by aramperes** [comment]
1. ~~I don't have any problem with `DEAD_BUSH`~~, but `LONG_GRASS` does have a strange behavior. **Can confirm for `DEAD_BUSH` too.**
2. I was not able to reproduce it, it correctly placed it on top for me.

**Comment by mastercoms** [comment]
Could you see if the bug still happens? I believe this was fixed. Closing unless shown to still happen.
