### ISSUE TITLE
Can't Place Sponge or Wet Sponge

### ISSUE THREAD

**Issue by GreenBeard** [GlowstoneMC/Glowstone#247]
When attempting to place Sponge it gives the following message:
[WARNING] Wrong MaterialData for SPONGE (BlockSponge): expected Sponge, got SPONGE(0)
When attempting to place Wet Sponge:
[WARNING] Wrong MaterialData for SPONGE (BlockSponge): expected Sponge, got SPONGE(1)

**Comment by aramperes** [comment]
Issue is rather related to Glowkit, see [PR](https://github.com/GlowstonePlusPlus/Glowkit/issues/16).

**Comment by GreenBeard** [comment]
K next time I'll put it there. (Should I close the issue if you have a pull request?)

**Comment by mastercoms** [comment]
No, issues stay open to discuss the issue, while PR discussions are there to discuss the code for that individual fix to the issue. This becomes helpful if there are multiple PRs with different ways to fix  a single issue.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstonePlusPlus/Glowkit/commit/63fbb29c40ebc7107036243b3825c25b0b2b1657.
