### ISSUE TITLE
Cannot download libraries from Maven repository on startup.

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#248]
The following libraries cannot be downloaded when the server starts, due to an HTTP 403 error:
- sqlite-jdbc-3.7.2.jar
- slf4j-jdk14-1.7.15.jar
- mysql-connector-java-5.1.38.jar

This is the [stacktrace](https://gist.github.com/momothereal/fe5f346d689eda8cc065) thrown by the server.

**Comment by gdude2002** [comment]
I think this is down to @greatman
