### ISSUE TITLE
Block Type Cache

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#250]
Currently the block type cache behaves rather strangely. Sometimes it does cache the type while it doesn't at other times (it isn't cleared either), when the type is set. Specifically, [this](https://github.com/GlowstoneMC/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/block/GlowBlock.java#L209) line is the troublemaker.

There are a few ways this could be fixed. First of all, that line could be removed and something like it could be added to `GlowBlock#setTypeIdAndData(int, byte, boolean)` to cache the type each time it is set. Secondly, the line could be removed and the cached type could be nullified in `GlowBlock#setTypeIdAndData(int, byte, boolean)`. And finally, the cache could be removed all together; the benefit of which is that setting the block type through another block instance doesn't create desynchronisation between the two.

I'm merely mentioning this as I'm not sure why the type is cached and what the preferable course of action is. Git blame turns up with you, @mastercoms.

**Comment by mastercoms** [comment]
Block type is cached because water physics uses getType, and getType was using a lot of CPU time. I accidentally missed those other setType methods.

**Comment by kamcio96** [comment]
water physic (or all physic) shouldn't call GlowBlock, or use other custom structure

I suggest use GlowBlock only for api

**Comment by mastercoms** [comment]
How else would water work?

**Comment by kamcio96** [comment]
it should faster get data from blocks array
