### ISSUE TITLE
Liquid sets double plants to a single plant

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#26]
When liquid flows, it sets the adjacent block if applicable. However, there is not a handler for double plants for this physics action, and the double plant sets itself to a single plant, but over the water because the breaking was performed on the bottom block in the double plant block group.

Double plants should be set to air completely on a physics interaction by a liquid.

![single plant above liquid](http://i.imgur.com/l4PrUwH.png)

**Comment by jimmikaelkael** [comment]
Wasn't this related to the afterPlace override in BlockDoublePlant ?

**Comment by mastercoms** [comment]
No, I tried it with and without the override.

**Comment by mastercoms** [comment]
Probably found the problem in the set type method. Fixing.
