### ISSUE TITLE
About the files downloads

### ISSUE THREAD

**Issue by Small-Ku** [GlowstoneMC/Glowstone#264]
I am hongkonger,let me sorry for the bad English first.:P
By the way,is there any lastest recommened or stable versions download in the website of Glowstone++ with each supporting Minecraft versions?

**Comment by mastercoms** [comment]
For which version do you want a download? 1.9.x or 1.8.x?

These are the latest versions for 1.9 and 1.8:

1.9: https://bamboo.gserv.me/browse/GSPP-SRV/latestSuccessful/artifact/shared/Server-JAR/glowstone%2B%2B-1.9.2-SNAPSHOT.jar

1.8: https://github.com/GlowstoneMC/GlowstonePlusPlus/releases/download/v1.8.9/glowstone.-1.8.9-SNAPSHOT.jar
