### ISSUE TITLE
Elytra wings don't work yet in 1.9.x

### ISSUE THREAD

**Issue by MisterCavespider** [GlowstoneMC/Glowstone#266]
Dear awesome developers of this awesome thing called Glowstone++,

I just started using Glowstone after years of Bukkit.
Naturally, I downloaded the the latest version, which was a 1.9.x SNAPSHOT.
I was horsing around in my new server, when I noticed that the Elytra wings don't work.
The console says:

> Player GlowPlayer(name=cavespider12) sent unknown PlayerAction: 8

Elytra wings probably aren't your biggest issue at the moment, but it is something you can add to your to-do list.

In addition, I also think an exception would fit better over here than just a print.

**Comment by mastercoms** [comment]
shut the fuck up you cancerous fuck you piece of shit shut up already i hate you

**Comment by kamcio96** [comment]
wow, mastercoms why?

**Comment by mastercoms** [comment]
Exceptions are scary, so I don't think it would be the best way to log this info. The print gives us sufficient information about the missing protocol handler.

@kamcio96 I am in a public place right now and I had left my computer unattended on this page and some "comedian" came and wrote that.

**Comment by aramperes** [comment]
Yes, it is currently listed in our [To-Do wiki page](https://github.com/GlowstoneMC/GlowstonePlusPlus/wiki/To-Do-List).

**Comment by MisterCavespider** [comment]
Great, I'll be waiting in my room for an update.
_waiting intensifies_

**Comment by aramperes** [comment]
@MisterCavespider This will likely take a while, elytra is not really a priority and its physics are decently complex.

**Comment by mastercoms** [comment]
I would think the movement would be handled clientside. I'm not sure though.

**Comment by momothereal** [comment]
@mastercoms It seems that physics are clientside indeed. However, I think the elytra taking damage while flying should be handled serverside, although I can't find the code for it in MCP. There is also no "Stop flying" action afaik?

**Comment by aramperes** [comment]
@MisterCavespider I may have over-thought how much time it would actually take! ¯\_(ツ)_/¯ See #268

**Comment by MisterCavespider** [comment]
@mastercoms,
Why did you say

>shut the fuck up you cancerous fuck you piece of shit shut up already i hate you

6 days ago and why did you delete it?

**Comment by mastercoms** [comment]
@MisterCavespider You deleted your comment, but see the second section of my comment here: https://github.com/GlowstoneMC/GlowstonePlusPlus/issues/266#issuecomment-210493401

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/7d99696129f057d2f3ec7171e5f476d8d1fb67c2
