### ISSUE TITLE
Give command tab completes raw (enum) material name

### ISSUE THREAD

**Issue by MisterCavespider** [GlowstoneMC/Glowstone#267]
You know, I liked the 'old' bukkit and spigot `/give` command:
The id you had to enter looked like an actual name: `minecraft:glowstone`
Now you have to type it in like an enumerator: `GLOWSTONE`

Because reasons, can you please tell me how I can change this, as Glowstone++ is open-source and I can change the code?
Or better: Is it possible to make a plugin that can replace the original altered Glowstone command so I don't have to horse around in the source?

And by the way, where else could I put this question? I don't want anyone to be concerned this is an issue. It only bothers my friend a little bit, who isn't used to using _TAB_.

**Comment by gdude2002** [comment]
It looks like this would be down to how [materials are registered in Glowkit](https://github.com/GlowstonePlusPlus/Glowkit/blob/30feb17215b35c70507187982c6c62d7f0f20462/src/main/java/org/bukkit/Material.java#L660), but I'm really not sure.

**Comment by mastercoms** [comment]
We have forums: https://forums.glowstone.net/. But I would consider this a bug.

**Comment by mastercoms** [comment]
Partially fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/540ab67c04f9a3b3440375c04d3df78b4c904956.

Also, you can type in glowstone. It just tab completes to GLOWSTONE.

**Comment by aramperes** [comment]
Fixed in ff6912d9cf01ba1fdd147580c88744f7dfb1d48f
