### ISSUE TITLE
Trees not generating on dynmap that on generated by worldborder

### ISSUE THREAD

**Issue by Small-Ku** [GlowstoneMC/Glowstone#269]
World generated by WorldBorder and Map generated by Dynmap
![103](https://cloud.githubusercontent.com/assets/16464896/14981612/df93f96e-1162-11e6-83e1-80254d7245db.png)

**Comment by gdude2002** [comment]
Aren't these trees?

![](https://dl.dropboxusercontent.com/u/1547120/ShareX/2016/May/vivaldi_2016-05-03_12-20-28.png)

It should be generating them, so please go there and provide a screenshot.

**Comment by Small-Ku** [comment]
The Trees are there but dynmap haven't show it on the map =3=

**Comment by gdude2002** [comment]
That sounds like a problem with dynmap, not Glowstone++. Raise a ticket with them.
