### ISSUE TITLE
Adding new portable format?

### ISSUE THREAD

**Issue by tamaskis99** [GlowstoneMC/Glowstone#271]
You can upgrade fully compatible PC-PE? Adding PE support to serverfile? 0.14.2 version addon update is best upgrade in serverfile is thankful, and its me reports any bug, etc from this.

**Comment by mastercoms** [comment]
We are focused on being a PC server. You can check out [Dragonet](https://github.com/DragonetMC/DragonProxy) to find a way to bridge PE clients to Glowstone++.

**Comment by tamaskis99** [comment]
Thank you help!

**Comment by mastercoms** [comment]
Any time!
