### ISSUE TITLE
Moving Arrow with effects to other slots

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#280]
Needs no explanation:
![c5e6773b10c687693ffc631a8f865f1b](https://cloud.githubusercontent.com/assets/17110757/15670971/7e3392c0-2728-11e6-82a4-f950f14155e9.gif)

**Comment by ghost** [comment]
Same with potions

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/fa5f8a0966c6ab2322187eb81b949fce2abdc296
