### ISSUE TITLE
You can place blocks at the same location as other entities

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#282]
Self-explanatory; players can place blocks at the same location as an entity, including yourself. A fix for this issue would have to take into account the size/box of the entity.

**Comment by mastercoms** [comment]
Partially fixed in https://github.com/GlowstoneMC/Glowstone/commit/5104c727e93bc6a40df690e655581736ce139783. Still needs to account for bounding box.

**Comment by aramperes** [comment]
Done in #373
