### ISSUE TITLE
ChunkManager getChunk uses invalid check

### ISSUE THREAD

**Issue by GreenBeard** [GlowstoneMC/Glowstone#283]
The line of code
`if (chunks.containsKey(key)) {`
will always return false because it creates a new instance and containsKey uses Equals which checks if they are the same instance (unless overridden) so it will always return false.

If you wish to verify this run http://pastebin.com/aFRJAUZt and it will always fail.

**Comment by GreenBeard** [comment]
I'll work on fixing this

**Comment by mastercoms** [comment]
The issue should still be open until it is fixed

**Comment by GreenBeard** [comment]
I think that it works if you use `chunks.put(new Key(2, 2), new GlowChunk(null, 0, 0));` instead of `chunks.put(new Key(2, 2), null);` because it wouldn't allow a null variable to be added to an array therefore the containsKey does work but I am still trying to figure out why the memory always increases steadily as soon as any chunks are generated (as in even after the chunks have been generated).

**Comment by GreenBeard** [comment]
Actual issue turns out to be #284
