### ISSUE TITLE
Command selectors (aka Target Selectors).

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#290]
Command/Target selectors are not implemented in Glowstone. For example, the target selector `@a` will represent all players, while `@a[m=1]` will represent all players in creative.

More info here: http://minecraft.gamepedia.com/Commands#Target_selectors

**Comment by aramperes** [comment]
Could an API be useful for this? Selectors + their arguments could me parsed/mapped and then used by the command.

**Comment by mastercoms** [comment]
So like getNearestPlayer(Location loc)? Yeah, I think that would be a nice thing to expose instead of just hiding it in a command.

**Comment by aramperes** [comment]
Yeah, but also something to parse the arguments, so that say `@a[m=1,r=10]` could be parsed into a map:

``` json

{
    "target": "all",
    "arguments": {
        "mode": "creative",
        "radius": 10
    }
}

```

And the command can use it:

``` java

CommandTarget target = new CommandTarget("@a[m=1,r=10]");
GameMode mode = target.getGameMode();
int radius = target.getRadius();
```

**Comment by aramperes** [comment]
-> https://github.com/GlowstoneMC/Glowkit/pull/4

**Comment by aramperes** [comment]
Done in https://github.com/GlowstoneMC/Glowkit/pull/6
