### ISSUE TITLE
Update to 1.10

### ISSUE THREAD

**Issue by Primorior** [GlowstoneMC/Glowstone#291]
The minecraft-update 1.10 is released, will Glowstone get a update for it?

**Comment by aramperes** [comment]
See https://forums.glowstone.net/topic/2/updating-to-1-10;

Basically, we are more focusing on completing major features from 1.8-1.9. However, we already have an (almost) complete protocol update on my fork: https://github.com/momothereal/GlowstonePlusPlus/tree/1.10-dev

**Comment by mastercoms** [comment]
Also, it is a small update that won't need much coding. The entities can be added, but they won't function, just like all other entities. The blocks don't need any work really to add.

**Comment by aramperes** [comment]
#293
