### ISSUE TITLE
Levitating AFK players & ghost players

### ISSUE THREAD

**Issue by BlackTrojan** [GlowstoneMC/Glowstone#295]
I found bug on your core.

When player is afk, if a player to break blocks it will hang in the air.

Next: if a player quit the server, the player with the nickname model lt remains on the server.

![screenshot_22](https://cloud.githubusercontent.com/assets/10076100/16015588/d8f33882-31af-11e6-8f42-7fc62d0a8b1c.png)
![screenshot_23](https://cloud.githubusercontent.com/assets/10076100/16015575/c13de98a-31af-11e6-9c16-27bfbdb0a5a2.png)

**Sorry for my english, im from Russia :)**

**Comment by gdude2002** [comment]
What build of Glowstone++ are you using?

**Comment by BlackTrojan** [comment]
I downloaded Glowstone++ from https://bamboo.gserv.me/browse/GSPP-SRV-148/artifact/shared/Server-JAR/glowstone%2B%2B-1.9.4-SNAPSHOT.jar

**Comment by mastercoms** [comment]
Hm that is strange. I remember that we fixed both of these bugs before. Maybe a protocol update messed them up.

**Comment by BlackTrojan** [comment]
Bug fixed?

**Comment by mastercoms** [comment]
Not yet, sorry. I'll update you when it's fixed.

**Comment by BlackTrojan** [comment]
Okey. I close this issue.

**Comment by Paulomart** [comment]
The bug is not fixed so

**Comment by gdude2002** [comment]
Yeah, please don't close issues (unless they're fixed and we forgot to). We need them to track what needs doing.

**Comment by BlackTrojan** [comment]
Okey, i I will not close issue, forward this bug fix.

**Comment by aramperes** [comment]
Appears to be fixed in 98e7d3b31ba0be9e72a9d51aeb0a8803b9398bc0
