### ISSUE TITLE
Armor issues.

### ISSUE THREAD

**Issue by vincentchu37** [GlowstoneMC/Glowstone#298]
Armor, goes into wrong slots and duplicates. MineCraft Version 1.9.4

http://puu.sh/pv5gh/c0221dee11.jpg

Error Message:
http://puu.sh/pv59k/104f68ea4c.png

**Comment by aramperes** [comment]
Is this with a world that was ported from Vanilla/Spigot to Glowstone?

**Comment by vincentchu37** [comment]
Yea it was.

**Comment by aramperes** [comment]
Should be fixed in #293.

**Comment by gdude2002** [comment]
Note that this will only be fixed for 1.10, not 1.9.4

**Comment by vincentchu37** [comment]
That's fine, I just wanted to let y'all know. Thanks

**Comment by aramperes** [comment]
Fixed in #293
