### ISSUE TITLE
CircleCI build artifacts not available without logging in?

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#3]
Configured https://circleci.com/gh/deathcap/GlowstonePlusPlus to copy the server jar out of the target directory after each build as described on http://blog.circleci.com/build-artifacts/, making it available for download, but I'm not seeing the "artifacts" tab without logging in. May have to switch somewhere else for hosting builds.

**Comment by deathcap** [comment]
Trying another free CI service:

https://drone.io/github.com/deathcap/GlowstonePlusPlus/files

**Comment by deathcap** [comment]
https://circleci.com/gh/circleci/artifact-test is accessible to me logging in with GitHub, so it may be that downloads are only available to any logged-in user. 

For non-GitHub users who want to try this project without building from source, https://drone.io/github.com/deathcap/GlowstonePlusPlus/files should have the latest build. 

Also trying out https://codeship.com/projects/72720

**Comment by deathcap** [comment]
Confirmed the artifacts on https://circleci.com/gh/deathcap/GlowstonePlusPlus are downloadable after logging in as a new user via GitHub, so I think CircleCI should be sufficient for hosting these builds for now, since anyone who wants to report issues already has to have a GitHub account.

To update the readme stating this fact, and also adding a link to drone.io as a convenient mirror for users to download without an account (but still prefer CircleCI since it hosts all builds that were ever built, useful for regression testing).

**Comment by rutsky** [comment]
Just for the record: we use CircleCI at [Buildbot](http://buildbot.net/) to build and "publish" documentation for Pull Request, and in our configuration artifacts are available *by direct link* for anyone.
Only "Artifacts" tab in the web UI is seen only to logged-in users.

For example, try this in private browsing mode: https://circle-artifacts.com/gh/rutsky/buildbot/19/artifacts/0/home/ubuntu/buildbot/master/docs/_build/html/index.html
And yes, not "Artifacts" tab in the build web UI in private browsing mode: https://circleci.com/gh/rutsky/buildbot/19#artifacts

Here is [how we collect artifacts in circle.yml](https://github.com/buildbot/buildbot/blob/51891ddd62588c3a01bf22513716bcbcbac63d0f/circle.yml#L13):

```
general:
  artifacts:
    - "master/docs/_build/html/"
```

**Comment by gdude2002** [comment]
@rutsky We're using [bamboo](https://bamboo.gserv.me/browse/GSPP-SRV) for the public builds these days anyways; you can see a table [on the site](http://glowstone.net) powered by that.
