### ISSUE TITLE
Permissions in permissions.yml don't work

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone#306]
The following error occurs:

```
13:46:21 [SEVERE] Permission node 'player' in permissions config is invalid
java.lang.ClassCastException: org.bukkit.configuration.MemorySection cannot be cast to java.util.Map
        at org.bukkit.permissions.Permission.loadPermissions(Permission.java:233)
        at net.glowstone.GlowServer.enablePlugins(GlowServer.java:847)
        at net.glowstone.GlowServer.start(GlowServer.java:529)
        at net.glowstone.GlowServer.run(GlowServer.java:454)
        at net.glowstone.GlowServer.main(GlowServer.java:311)
```

with the following `permissions.yml` file:

``` yaml
# This is the permissions configuration file for Bukkit.
# For documentation on how to make use of this file, check out the Bukkit Wiki at
# http://wiki.bukkit.org/Permissions.yml
#
# This file IS NOT a replacement for a permission management plugin. Please read the
# wiki for more information. If in doubt, do not use this file.
#
# For help, join us on IRC: #glowstone @ esper.net
player.basics:
    default: true
    children:
        skywars.kit: true
        skywars.kitgui: true
```

**Comment by gdude2002** [comment]
Hmm, interesting. To clarify, this is for the Bukkit-included basic permissions system, right?

We've seen a bunch of permissions plugins used and tested on Glowstone, but never the bundled bperms. It'll be worth our time to look into this more.

**Comment by gdude2002** [comment]
Alright, the issue appears to be related to the following lines in `GlowServer.java`

``` java
// load permissions.yml
ConfigurationSection permConfig = config.getConfigFile(Key.PERMISSIONS_FILE);
List<Permission> perms = Permission.loadPermissions(permConfig.getValues(false), "Permission node '%s' in permissions config is invalid", PermissionDefault.OP);
```

Looks like the Bukkit API expects a Map to be passed in here, not a ConfigurationSection. Should be an easy fix.

**Comment by gdude2002** [comment]
Yup, [can confirm](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/permissions/Permission.java#228). This is probably a one-line fix, but I'll let one of the regular contributors push a PR or fix in case there's a better way to do it than I'm thinking.

**Comment by daboross** [comment]
Ok, thank you for looking into this! I guess the bundled permissions aren't used much in production, but they're super useful for testing plugins in development without having any additional plugins.
