### ISSUE TITLE
Client can't connect to server

### ISSUE THREAD

**Issue by Rocologo** [GlowstoneMC/Glowstone#309]
Hi again,

So now my plugin seems to run when I start the Glowstone Server, but my standard Minecraft client can't connect to the server???

This is the error I get in the client log. There is nothing to see in the server log.:

> Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
> [16:33:34] [Client thread/INFO]: Setting user: Gabriel333
> [16:33:36] [Client thread/INFO]: LWJGL Version: 2.9.4
> [16:33:39] [Client thread/INFO]: Reloading ResourceManager: Default, Matmos.Default.zip, MSI_conversion.zip
> [16:33:40] [Client thread/WARN]: File minecraft:sounds/matmos_interactions/jumpina.ogg does not exist, cannot add it to event minecraft:matmos_interactions.jumpina
> [16:33:40] [Client thread/WARN]: File minecraft:sounds/matmos_msi/cave/woodb.ogg does not exist, cannot add it to event minecraft:matmos_msi.cave.woodb
> [16:33:40] [Client thread/WARN]: File minecraft:sounds/matmos_msi/cave/woodc.ogg does not exist, cannot add it to event minecraft:matmos_msi.cave.woodc
> [16:33:40] [Sound Library Loader/INFO]: Starting up SoundSystem...
> [16:33:40] [Thread-5/INFO]: Initializing LWJGL OpenAL
> [16:33:40] [Thread-5/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
> [16:33:40] [Thread-5/INFO]: OpenAL initialized.
> [16:33:40] [Sound Library Loader/INFO]: Sound engine started
> [16:33:42] [Client thread/INFO]: Created: 1024x512 textures-atlas
> [16:33:49] [Client thread/INFO]: Connecting to localhost, 25565
> [16:33:49] [Server Connector #1/ERROR]: Couldn't connect to server
> java.io.IOException: Unable to connect to remote host: Connection refused
>   at io.netty.channel.epoll.Native.finishConnect(Native Method) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
>   at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doFinishConnect(EpollSocketChannel.java:659) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
>   at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.finishConnect(EpollSocketChannel.java:592) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
>   at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:621) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
>   at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
>   at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
>   at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
>   at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_91]

This is the info from the launcher:
http://pastebin.com/KpeL7gQ2

**Comment by mastercoms** [comment]
what's on the server console log?

also i can't help but notice your kernel is sort of old

**Comment by Rocologo** [comment]
Nothing, I can't even see the client tries to logon.

> 13:44:52 [INFO] This server is running Glowstone++ version 1.9.4-SNAPSHOT-"ff881e6"-MC1.9.4 (Implementing API version 1.9.4-R0.1-SNAPSHOT)
> 13:44:53 [INFO] Recipes: 295 shaped, 63 shapeless, 26 furnace, 10 dynamic, 28 fuels.
> 13:44:53 [INFO] Scanning plugins...
> 13:44:53 [INFO] PluginTypeDetector: found 6 Bukkit, 1 Sponge, 0 Forge, 0 Canary, 0 unknown plugins (total 6)
> 13:44:53 [INFO] Set PluginClassLoader as parallel capable
> 13:44:53 [WARNING] SpongeAPI plugins found, but no Sponge bridge present! They will be ignored.
> 13:44:53 [WARNING] Ignored SpongeAPI plugin: plugins/MobHunting-3.2.5-SNAPSHOT-B56.jar
> 13:44:53 [WARNING] Suggestion: install https://github.com/deathcap/Bukkit2Sponge to load these plugins
> 13:44:53 [INFO] [Vault] Enabling Vault v1.5.6-b49
> 13:44:53 [INFO] [Vault] [Economy] Essentials Economy found: Waiting
> 13:44:53 [INFO] [Vault] [Permission] PermissionsEx found: Waiting
> 13:44:53 [INFO] [Vault] [Permission] SuperPermissions loaded as backup permission system.
> 13:44:53 [INFO] [Vault] [Chat] PermissionsEx found: Waiting
> 13:44:53 [INFO] [Vault] Enabled Version 1.5.6-b49
> 13:44:53 [INFO] Preparing spawn for world...
> 13:44:55 [INFO] Preparing spawn for world: 21%
> 13:44:55 [INFO] Preparing spawn for world: done
> 13:44:55 [INFO] Preparing spawn for world_nether...
> 13:44:56 [INFO] Preparing spawn for world_nether: done
> 13:44:56 [INFO] Preparing spawn for world_the_end...
> 13:44:57 [INFO] Preparing spawn for world_the_end: done
> 13:44:57 [INFO] [PermissionsEx] Enabling PermissionsEx v1.23.4
> 13:44:57 [INFO] [PermissionsEx] Initializing file backend
> 13:44:57 [INFO] [PermissionsEx] Permissions file successfully reloaded
> 13:44:57 [INFO] [Vault][Permission] PermissionsEx hooked.
> 13:44:57 [INFO] [Vault][Chat] PermissionsEx_Chat hooked.
> 13:44:57 [INFO] [Essentials] Enabling Essentials v2.0.1-b334
> 13:44:58 [INFO] Using locale en_US
> 13:44:58 [INFO] [Essentials] Using legacy item data provider as mob spawner provider.
> 13:44:58 [INFO] [Essentials] Using legacy item data provider as spawn egg provider.
> 13:44:58 [INFO] [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
> 13:44:58 [INFO] Using locale en_US
> 13:44:58 [INFO] [Essentials] Starting Metrics. Opt-out using the global PluginMetrics config.
> 13:44:58 [INFO] [Vault][Economy] Essentials Economy hooked.
> 13:44:58 [INFO] [MobHunting] Enabling MobHunting v3.2.5-SNAPSHOT
> 13:44:59 [INFO] [MobHunting] [Debug] Loading WorldGroups
> 13:44:59 [INFO] [MobHunting] [Debug] Updating database triggers.
> 13:44:59 [INFO] [MobHunting] Enabling compatibility with Essentials (2.0.1-b334)
> 13:44:59 [INFO] [EssentialsSpawn] Enabling EssentialsSpawn v2.0.1-b334
> 13:44:59 [INFO] [GameModeControl] Enabling GameModeControl vBeta 1.2.0
> 13:44:59 [INFO] [GameModeControl] Forcing game mode 0 on player join.
> 13:44:59 [INFO] [GameModeControl] Plugin enabled!
> 13:44:59 [INFO] [GameModeControl] Note: this is a [BETA]
> 13:44:59 [INFO] [GameModeControl] If you need help with the commands
> 13:44:59 [INFO] [GameModeControl] use /gmh.
> 13:45:00 [INFO] Binding to address: localhost/127.0.0.1:25561...
> 13:45:00 [INFO] Successfully bound to: /127.0.0.1:25561
> 13:45:00 [INFO] Ready for connections.
> 14:44:59 [INFO] [MobHunting] Checking for new updates...
> 14:45:00 [INFO] [MobHunting] [Debug] You are using a development version (3.2.5-SNAPSHOT)
> 14:45:00 [INFO] [MobHunting] No update found.

**Comment by Rocologo** [comment]
What do you mean with my kernel is old?

**Comment by aramperes** [comment]
Edit: Found your problem.

Your server is starting on port `25561`, while you are connecting to port `25565`.

> 13:45:00 [INFO] Successfully bound to: /127.0.0.1:25561
> [16:33:49] [Client thread/INFO]: Connecting to localhost, 25565

**Comment by Rocologo** [comment]
The server is 1 out of 15 different servers I start on my labtop (Linux Mint 17.3) each time want to test my plugin against any server (Spigot, Craftbukkit, PaperClip, Glowstone, Cauldron)

And I simply forgot that I had to change the port when I was testing against Glowstone 1.8.9. This is not needed any more and this is of cause the reason for my problem. :-(

Sorry.
