### ISSUE TITLE
Error making sticks

### ISSUE THREAD

**Issue by Rocologo** [GlowstoneMC/Glowstone#310]
So now I'm up and running with the Glowstone server and my plugin (not tested yet) while trrying to play a little I found some bugs.

When I tried to make sticks (to make torches) I was only able to make 4 at a time, and then I had to close and open the workbench again.

In the console I got this message, each time I tried to make more than 4 sticks.:

> 18:55:54 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=29, mode=0, item=ItemStack{STICK x 4})
> 18:55:58 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=31, mode=0, item=ItemStack{STICK x 4})
> 18:55:59 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=32, mode=0, item=ItemStack{STICK x 4})
> 18:55:59 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=33, mode=0, item=ItemStack{STICK x 4})
> 18:56:21 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=35, mode=0, item=ItemStack{STICK x 4})
> 18:56:22 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=36, mode=0, item=ItemStack{STICK x 4})
> 18:56:22 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=37, mode=0, item=ItemStack{STICK x 4})
> 18:56:22 [INFO] Gabriel333: [rejected] WindowClickMessage(id=1, slot=0, button=0, transaction=38, mode=0, item=ItemStack{STICK x 4})

**Comment by gdude2002** [comment]
I've seen this before, but I thought it was fixed previously. You're on the latest build of Glowstone, right?

**Comment by mastercoms** [comment]
Works with shift clicking, but the bug occurs with manual clicking. So shift click is a workaround until I fix it.
