### ISSUE TITLE
Dungon generated

### ISSUE THREAD

**Issue by Rocologo** [GlowstoneMC/Glowstone#312]
Just walking around I got this error in the console:

> 19:12:56 [INFO] dungeon generated: -61,44,-222
> 19:13:32 [SEVERE] Error while loading chunk (3,-16)
> java.io.IOException: Invalid length: 93061752 > 4096
>   at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:196)
>   at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:63)
>   at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:152)
>   at net.glowstone.GlowChunk.load(GlowChunk.java:188)
>   at net.glowstone.GlowChunk.load(GlowChunk.java:181)
>   at net.glowstone.GlowChunk.getSection(GlowChunk.java:282)
>   at net.glowstone.GlowChunk.getType(GlowChunk.java:322)
>   at net.glowstone.block.GlowBlock.getTypeIdNoCache(GlowBlock.java:201)
>   at net.glowstone.block.GlowBlock.getType(GlowBlock.java:182)
>   at net.glowstone.block.blocktype.BlockWater.hasNearSolidBlock(BlockWater.java:46)
>   at net.glowstone.block.blocktype.BlockWater.updateBlock(BlockWater.java:30)
>   at net.glowstone.GlowWorld.updateBlocksInSection(GlowWorld.java:436)
>   at net.glowstone.GlowWorld.updateBlocksInActiveChunks(GlowWorld.java:418)
>   at net.glowstone.GlowWorld.pulse(GlowWorld.java:370)
>   at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
>

**Comment by Rocologo** [comment]
And again in another area:

> 19:15:48 [INFO] dungeon generated: 254,49,-96
> 19:18:32 [SEVERE] Error while loading chunk (-3,-11)
> java.io.IOException: Invalid length: 190338903 > 4096
>   at net.glowstone.io.anvil.RegionFile.getChunkDataInputStream(RegionFile.java:196)
>   at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:63)
>   at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:152)
>   at net.glowstone.GlowChunk.load(GlowChunk.java:188)
>   at net.glowstone.GlowChunk.load(GlowChunk.java:181)
>   at net.glowstone.GlowChunk.getSection(GlowChunk.java:282)
>   at net.glowstone.GlowChunk.getType(GlowChunk.java:322)
>   at net.glowstone.block.GlowBlock.getTypeIdNoCache(GlowBlock.java:201)
>   at net.glowstone.block.GlowBlock.getTypeId(GlowBlock.java:196)
>   at net.glowstone.GlowWorld.lambda$pulseTickMap$20(GlowWorld.java:1792)
>   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
>   at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
>   at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3606)
>   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
>   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
>   at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
>   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
>   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>   at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>   at net.glowstone.GlowWorld.pulseTickMap(GlowWorld.java:1790)
>   at net.glowstone.GlowWorld.pulse(GlowWorld.java:356)
>   at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:139)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)

**Comment by gdude2002** [comment]
Possibly a duplicate of #256

**Comment by aramperes** [comment]
Not necessarily a duplicate; it does seem like the same bug, but this is not caused by water updates.

**Comment by Rocologo** [comment]
Water could be involved. I walked along the coast and noticed some errors in the water. Some water  blockes was one block lower than the rest of the sea.

**Comment by aramperes** [comment]
My mistake, did not read your stacktrace carefully (was on mobile). It is indeed the same stacktrace (caused by BlockWater), therefore this is a duplicate. Dungeon generation is not related (there is a 2-3 minutes interval from these two log lines).

**Comment by gdude2002** [comment]
Closed as a duplicate of #256. Feel free to give any extra info there.
