### ISSUE TITLE
IndexOutOfBoundsException sometimes when shutting down, and OP not persisting

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone#314]
This error happened once when shutting down, and I haven't experienced it since. There doesn't seem to be any result of the error, it just is shown in the console. I was the only player online, and the server was in offline mode.

```
23:03:13 [INFO] daboross kicked: Server shutting down.
23:03:13 [WARNING] Exception in thread "Thread-4" 
23:03:13 [WARNING] java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
23:03:13 [WARNING]      at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:313)
23:03:13 [WARNING]      at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:295)
23:03:13 [WARNING]      at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65)
23:03:13 [WARNING]      at net.glowstone.GlowServer.getPlayerDataService(GlowServer.java:975)
23:03:13 [WARNING]      at net.glowstone.entity.GlowPlayer$2.run(GlowPlayer.java:1833)
```

If it matters, there was also this earlier:

```
>op daboross
23:01:35 [WARNING] Failed to look up profile
23:01:35 [WARNING] Failed to look up profile
23:01:35 [INFO] CONSOLE: Opped daboross
```

I became OP, but only until the server restarted.

On the following restart, this error occurred:

```
23:04:16 [SEVERE] Error reading from: config/ops.json
java.lang.NullPointerException
        at net.glowstone.util.bans.JsonListFile.load(JsonListFile.java:54)
        at net.glowstone.GlowServer.start(GlowServer.java:487)
        at net.glowstone.GlowServer.run(GlowServer.java:454)
        at net.glowstone.GlowServer.main(GlowServer.java:311)

```

ops.json:

```
[{"name":null,"uuid":"24c15528-0bce-3f0f-8342-7adea12a030e"}]
```

Version: 1.9.4-SNAPSHOT-"ff881e6"-MC1.9.4

**Comment by aramperes** [comment]
That's probably because you are on an offline/cracked server.

Edit; Whoops, didn't read the part where you mentioned it ;) - Yes it is a known issue, not sure if it's worth fixing since it's not a crash and we don't support the use of cracked servers.

**Comment by daboross** [comment]
Yes, that seems likely.

By the way, thank you for the quick responses on support tickets! I've just been testing plugins with Glowstone recently, to ensure that I stay as compatible as possible.

**Comment by mastercoms** [comment]
Please note that we don't support using offline servers in help threads (besides bugs like this), but we definitely support as a feature, so this should be fixed.

**Comment by mastercoms** [comment]
Op not persisting was fixed in https://github.com/GlowstoneMC/Glowstone/commit/be5194e71d5d53a3589944ff600d7fd8cc726cdf.

**Comment by mastercoms** [comment]
Other issue fixed https://github.com/GlowstoneMC/Glowstone/commit/2c19d3b1300a0484a77ea0d439043d9e368645ab. It was because player data was not saved before worlds were unloaded, due to thread timing issues. Now that async has been disabled for shutdown, there will be no issues with this.
