### ISSUE TITLE
After death, PlayerDeathEvent isn't called, and player can't interact with other players

### ISSUE THREAD

**Issue by daboross** [GlowstoneMC/Glowstone#318]
When a player dies, Glowstone doesn't seem to recognize, and doesn't seem to "finish" the death action.

The PlayerDeathEvent isn't launched, and if the player who died tries to attack another player after respawning, the following message is displayed:

```
00:15:18 [INFO] Player daboross tried to interact with an entity while dead
```

The player who died in the world is also invisible to all other players on the server (as far as I can tell). However, the minecraft client does show the respawn as successful, and the player is able to break blocks, place blocks, and move around - just not interact with other players.

Glowstone server version: 1.9.4-SNAPSHOT-"ff881e6"-MC1.9.4

**Comment by aramperes** [comment]
Appears to be fixed in #333
