### ISSUE TITLE
Durability and Breaking Overhaul

### ISSUE THREAD

**Issue by tsengia** [GlowstoneMC/Glowstone#319]
After looking into issue #311, it seems that the DiggingHandler class uses some spotty code, and the ItemTable is far from complete (the only tools it has registered are hoes)! 
I propose creating a class for each tool type, as Flint & Steel has its own class, and so do Hoes (ItemHoe).

**Comment by mastercoms** [comment]
You don't need classes for any other tool type. The other tools have no special abilities. They act as a hand, but with different damage numbers that are handled by the client. Hoe has a special function on right click to till the ground. Same with flint and steel. You right click to place fire.

**Comment by tsengia** [comment]
Ok, then we don't need to make separate classes, however the ItemTable does not contain pickaxes, shovels, or swords. I think that is needed to complete it, and to help avoid bugs in the future from not having all of the items in the ItemTable.

**Comment by mastercoms** [comment]
ItemTable is only there to associate classes that provide extra functionality to their relevant item type.
