### ISSUE TITLE
Review Pore's patches to Bukkit API

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#32]
The Pore project (an implementation of Spigot's 1.8.3 update to the Bukkit API) has a handful of its own patches to the API, some might make sense to pull into Glowstone++'s:

https://github.com/LapisBlue/Pore/tree/master/patches
- [x] 0001-Disable-Spigot-version-check.patch
- [ ] 0002-Remove-final-from-event-getters.patch
- [ ] 0003-Add-HandlerList-adapters.patch
- [ ] 0004-Make-events-properly-initialisable.patch
- [ ] 0005-Add-method-to-get-EntityType-from-Class.patch
- [ ] 0006-Disable-reload-command.patch
- [ ] 0007-Remove-plugin-prefixes-and-use-normal-logger-instead.patch
- [ ] 0008-Add-validity-check-supermethod-to-top-Event-class.patch
##

**Comment by mastercoms** [comment]
First one is useless for a server implementation, we need a version command.
I think the second one was only done so they could extend it for Pore's use.
Third one seems good.
4th one seems only applicable to Pore.
5th is useful.

In my opinion, we should use only 3 and 5.

**Comment by deathcap** [comment]
I took the first patch (committed in https://github.com/deathcap/Glowkit/commit/18d92a429a99d64e814858d59e444361fbeb20e3), it only disables Spigot's online API version check (queries https://hub.spigotmc.org/stash/rest/api/1.0/projects/SPIGOT/repos/) in `/version`, which with Glowstone++ always fails (but we could re-enable it if we have a similar stash API for this project, at some point)

**Comment by mastercoms** [comment]
Oh, I didn't see that part, sorry.

**Comment by deathcap** [comment]
Pore has since added three additional patches:

* 0006-Disable-reload-command.patch - I believe this was added because of issues with mods when reloading (something with resetting recipes mod recipes?), does not apply to us
* 0007-Remove-plugin-prefixes-and-use-normal-logger-instead.patch - seems like we wouldn't want this one either, plugin prefixes in logging are useful..
* 0008-Add-validity-check-supermethod-to-top-Event-class.patch - unsure, added for Sponge compatibility, might be useful later for SpongeAPI support?

**Comment by gdude2002** [comment]
This ticket needs categorization on the [waffle board](https://waffle.io/GlowstoneMC/Glowstone).

Has this ticket seen any movement or has there been any action expected since the previous comment?

**Comment by mastercoms** [comment]
Closing due to Pore being dead, and the patches don't seem to add much for Bukkit plugins.
