### ISSUE TITLE
Maven compiler option

### ISSUE THREAD

**Issue by hugo4715** [GlowstoneMC/Glowstone#324]
Hello, 

I'm starting to take a look at this project, but i'm wondering if there is a reason not to add 
`<useIncrementalCompilation>false</useIncrementalCompilation>`
in the Maven compiler plugin configuration. This way, maven only compile modified classes, wich is faster than recompiling the entire project.

Bye

**Comment by VaiTon** [comment]
It would be useful for local development but not for continuous integration because it'll compile all classes.

**Comment by gdude2002** [comment]
Bamboo (my CI server) runs in a clean dir each time, so it wouldn't be a problem there.

**Comment by hugo4715** [comment]
I'm trying to see if there is a command line option available, i'll update you if i find results.

**Comment by hugo4715** [comment]
I found that there is a user property available wich is `maven.compiler.useIncrementalCompilation`.
We can set it in the eclipse maven properties, or (not tested) with the cl option `-Dmaven.compiler.useIncrementalCompilation=false`

Maybe i'll add this in the wiki.
