### ISSUE TITLE
 Rogue thread: Thread[Glowstone-scheduler-4,5,main]

### ISSUE THREAD

**Issue by Rocologo** [GlowstoneMC/Glowstone#325]
After updating to Glowstone Build 180, I get the error when stopping the server 

> 14:48:25 [WARNING] Still running after shutdown, finding rogue threads...
> 14:48:25 [WARNING] Rogue thread: Thread[Glowstone-scheduler-4,5,main]
> 14:48:25 [WARNING]     at java.net.SocketInputStream.socketRead0(Native Method)
> 14:48:25 [WARNING]     at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
> 14:48:25 [WARNING]     at java.net.SocketInputStream.read(SocketInputStream.java:170)
> 14:48:25 [WARNING]     at java.net.SocketInputStream.read(SocketInputStream.java:141)
> 14:48:25 [WARNING]     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
> 14:48:25 [WARNING]     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
> 14:48:25 [WARNING]     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
> 14:48:25 [WARNING]     at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
> 14:48:25 [WARNING]     at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
> 14:48:25 [WARNING]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
> 14:48:25 [WARNING]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
> 14:48:25 [WARNING]     at net.glowstone.util.Metrics.postPlugin(Metrics.java:446)
> 14:48:25 [WARNING]     at net.glowstone.util.Metrics.access$400(Metrics.java:45)
> 14:48:25 [WARNING]     at net.glowstone.util.Metrics$1.run(Metrics.java:209)
> 14:48:25 [WARNING]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 14:48:25 [WARNING]     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 14:48:25 [WARNING]     at net.glowstone.scheduler.GlowTask.run(GlowTask.java:169)
> 14:48:25 [WARNING]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 14:48:25 [WARNING]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 14:48:25 [WARNING]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 14:48:25 [WARNING]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 14:48:25 [WARNING]     at java.lang.Thread.run(Thread.java:745)

**Comment by gdude2002** [comment]
Not actually a problem. See this [forum thread](https://forums.glowstone.net/topic/18/vault-essentialsx-economy-error).
