### ISSUE TITLE
Some subclasses of BlockType still instanciate a random object.

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#34]
This is now no longer necessary as BlockType instantiate a protected random object.

**Comment by mastercoms** [comment]
Why was this done in the first place?

**Comment by jimmikaelkael** [comment]
Because a lot of blocks needs a Random instance, simply to avoid redundancy.

**Comment by mastercoms** [comment]
Ah, so their super has this Random instance already, but it was still included from before they added it to BlockType?

**Comment by jimmikaelkael** [comment]
Exactly.
