### ISSUE TITLE
Unknown Entity: MinecraftRideable

### ISSUE THREAD

**Issue by FastFelix771** [GlowstoneMC/Glowstone#345]
When my imported world loads, a warning appears and all minecards are removed.
Everything works, no exceptions, but the minecarts are all gone.

`2016/08/22 08:42:54 [WARNING] Unknown entity in GlowChunk{world=spigotworld,x=81,z=114}: MinecartRideable`

Using Glowstone #220 from CI Server.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/a01b1b1441754bad7f4f0b2d85cd518c1f1eaf63.
