### ISSUE TITLE
Add color code parsing to the MOTD config option

### ISSUE THREAD

**Issue by FastFelix771** [GlowstoneMC/Glowstone#346]
Currently, color codes like &4 doesn't work on this config option.
I didn't tested the unicode values yet, but you should add color code parsing anyways, for its ease of use and readability.

**Comment by MisterCavespider** [comment]
I haven'the tried it myself, but you could take a look at this:
http://www.minecraftforum.net/forums/support/server-support/tutorials-and-faqs/1940468-how-to-add-colour-to-your-server-motd

It tells about a Unicode char.
You could copy paste this char and see if that works.
Even if it works, it's still a nasty work-around

**Comment by FastFelix771** [comment]
It probably works, the Minecraft client parses that - maybe even § instead of & will work.
But all users used to use the Bukkit color codes (&) - its known and nice, why not adapt it? 
Super easy to integrate, one line of code.

**Comment by DeprecatedLuke** [comment]
+1 on adding native '&' support for motd - this would make some motd plugins redundant

**Comment by FastFelix771** [comment]
it makes such plugins useless.
Unless they want a reloadable MOTD or any kind of animations (if thats still possible) or per-player views

**Comment by aramperes** [comment]
This feature has been added in #415.
