### ISSUE TITLE
SignChangeEvent doesn't seem to fire and Sign MaterialData may not be existent on Sign blocks.

### ISSUE THREAD

**Issue by FastFelix771** [GlowstoneMC/Glowstone#356]
I've found out, that Essentials' teleport signs are not working (Used [Warp], works on Spigot).
As it uses only bukkits events and a instanceof Sign check, it cannot be an error of Essentials.

You should check, if SignChangeEvents etc. are firing properly.

**Comment by aramperes** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/4037430ef2c0a4e8d58b1e7b3c26b27482557689

Make sure you have `enabledSigns.warp` un-commented in Essential's config.yml:

``` yml
enabledSigns:
  #- color
  #- balance
  #- buy
  #- sell
  #- trade
  #- free
  #- disposal
  - warp
  #- kit
  #- mail
  #- enchant
  #- gamemode
  #- heal
  #- info
  #- spawnmob
  #- repair
  #- time
  #- weather
```

**Comment by FastFelix771** [comment]
Ehm, i copied Essentials and all configs 1:1 from Paper to Glowstone.
It worked before, but good to know it works for you, maybe my version is out of date.

You have tried to place and use that signs, right?

EDIT: ahh, just realised that the hint was optional xD

**Comment by aramperes** [comment]
@FastFelix771 It didn't work in glowstone because SignChangeEvent wasn't getting fired, that was added in that commit. Try with that commit and check if it works (build [here](https://bamboo.gserv.me/browse/GSPP-SRV-226))
