### ISSUE TITLE
Player placed leaves should not be decayable

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#36]
Currently, the leaves placed by playes are decayable, this shouldn't be the case:
http://minecraft.gamepedia.com/Leaves

This currently have no real incidence, but I'm planning leaf decay so this will need to be fixed.

**Comment by mastercoms** [comment]
Fixed in 53ebe9f67642ba4c7394fc54c5fffda905c3fa85. Thanks!
