### ISSUE TITLE
Manual for IDE Setup / References

### ISSUE THREAD

**Issue by valleydev** [GlowstoneMC/Glowstone#360]
I can't get eclipse neon running as many references are missing and not part of the repository.
I would really like to contribute (cows, chickens and animals), so a manual helping me to set up the debug environment would be helpful for me to get involved.

Any help will be highly appreciated.

**Comment by gdude2002** [comment]
Setting up Eclipse for Glowstone should be as simple as setting up any Maven project with it.

I don't personally use Eclipse, but I know there are a few developers here that do - have you worked with a Maven project before?

**Comment by valleydev** [comment]
Thanks for your fast response.
I am used to work with .net Framework and visual studio (no experience with maven). Is there a better alternative to eclipse?

**Comment by gdude2002** [comment]
I personally use Intellij IDEA, but it really comes down to what you're used to. 

I've mentioned the channel on Discord, so someone more knowledgeable with Eclipse should be along at some point, if you still want to go down that route.

**Comment by valleydev** [comment]
Thanks for your recommendation: As i am new to eclipse anyway, i will take a look at Intellij IDEA.

**Comment by mastercoms** [comment]
https://github.com/GlowstoneMC/Glowstone/wiki/Setting-Up-Tips

Make sure you get a Lombok plugin. That's probably why there are missing references. Also, make sure that your IDE is downloading the required dependencies specified in the Maven 3 pom.xml.

**Comment by valleydev** [comment]
Finally got it working. I like the IDE. 

Currently debugging and trying to fix some errors like
[WARNUNG] USR moved too quickly!
on inital join causing players death...

**Comment by mastercoms** [comment]
It has something to do with the spawn point that the server finds being not safe so the client is moved to a safe spot, which makes it move too quickly.

If there is not already an issue created for this bug, please create one.

Closing this as the issue with your IDE was fixed.
