### ISSUE TITLE
Sending message through CommandSender.sendMessage(String) doesn't parse colours.

### ISSUE THREAD

**Issue by MisterCavespider** [GlowstoneMC/Glowstone#361]
Exactly as the title states.

sender.sendMessage("&6TEXT"); wont parse the colour.

**Comment by picknchew** [comment]
The ampersand, `&` is not the color character for Minecraft. It is actually the section sign, `§`.

**Comment by mastercoms** [comment]
You have to do `sender.sendMessage(ChatColor.GOLD + "TEXT")`. & and section signs will not work as they are not parsed by Bukkit by default. EssentialsChat will add this functionality.

**Comment by aramperes** [comment]
Alternatively to what @mastercoms said, you can use `ChatColor.translateAlternateColorCodes('&', "&6TEXT");` ([javadoc](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html#translateAlternateColorCodes%28char,%20java.lang.String%29))

**Comment by gdude2002** [comment]
Yup, out of experience with Bukkit, I can agree with everyone else here. sendMessage does not parse the colour, and that is expected behavior. There are plugins which change that, but you shouldn't rely on their presence.
