### ISSUE TITLE
Signs

### ISSUE THREAD

**Issue by picknchew** [GlowstoneMC/Glowstone#370]
Signs do not break after the supporting block is broken. This makes floating signs possible. ![qvbga7n 1](https://cloud.githubusercontent.com/assets/3619860/18256295/6a8b0924-7381-11e6-9807-c23c499bc886.png)

Placing blocks vertically without shift right clicking on the sign also works. In vanilla, right clicking the sign counts as an interact not a block place (maybe just call it a feature?).

Torches can be placed on signs.

Signs also appear to count as full blocks allowing redstone signals to go through them 
![hpp9l2e 1](https://cloud.githubusercontent.com/assets/3619860/18256334/e3832e74-7381-11e6-8a38-96af970fe67d.png)

**Comment by adlradlr** [comment]
Glowstone build #361 

Also possible to stack pressure plates and remove the blocks beneath them without breaking the pressure plates. (Pressure plates don't click/produce output) 

![2017-02-27_17 07 16](https://cloud.githubusercontent.com/assets/26056727/23371197/33ca3f00-fd0f-11e6-96e1-5d9cc379046c.png)
