### ISSUE TITLE
Replaceable Blocks

### ISSUE THREAD

**Issue by picknchew** [GlowstoneMC/Glowstone#371]
Sometimes the server does not register the placement of blocks on a replaceable block, tall grass for example. Placing a block on it changes the block to what is supposed to be there then immediately reverts as it is never recognized by the server.

**Comment by aramperes** [comment]
Can you give examples of blocks to which this can occur? I tried with Grass and Fern and it works as expected.

**Comment by picknchew** [comment]
Tall grass, specifically with rails.

**Comment by aramperes** [comment]
Should be fixed by https://github.com/GlowstoneMC/Glowstone/commit/972d75ba81642915f315149d539e1acac00569ab, please let me know.
