### ISSUE TITLE
Mobs dont move

### ISSUE THREAD

**Issue by Rocologo** [GlowstoneMC/Glowstone#375]
I have tried to test my Plugin MobHunting against GlowStone 1.10.2 Build 249 but it does not work.

When I spawn mobs with essentials "/spawnmob spider" the mobs don't move and when I kill the mob nothing happens. No vanilla drops and No MobHunting drops and it looks like if "onEntityDeath" is never called???

**Comment by aramperes** [comment]
Please refer to this thread: #362 

This is not a bug, because mob AI and drops have not been implemented yet. It should be regarded as a missing feature, and has been reported in that thread.

**Comment by Rocologo** [comment]
Ahhh... I thought you had that in place... and then it does not make sense to test my plugin :-) Except I can see that there are no errors so far. I close this issue....
