### ISSUE TITLE
Multiple versions - "ProtocolSupport"

### ISSUE THREAD

**Issue by augustresende** [GlowstoneMC/Glowstone#380]
Is not hard add multiple versions with protocol hack. Pls add this!

**Comment by LuminousLoreBloom** [comment]
Why don't you do it yourself if it's not 'hard'?

**Comment by ethsmith** [comment]
@GabrielAugustoTI If it is not so hard, you learn Java and code the update yourself. Since it is so easy you should have no trouble coding it in a reasonable amount of time.
Glowstone is built on top of Spigot. I assume ViaVersion works to an extent but this is not even complete yet,

**Comment by ethsmith** [comment]
@GabrielAugustoTI Learn to have some respect for the open source community.

**Comment by ethsmith** [comment]
@GabrielAugustoTI If it were up to me you would be banned from this repo and the forums.

**Comment by gdude2002** [comment]
Guys? Why are you being so toxic? This attitude doesn't belong in an open-source project.

What are the merits of multiple protocol support? Dragonet exists just to bridge the _current_ versions of desktop MC and MCPE, and they have an _entire project_ dedicated to just that.

**Comment by phase** [comment]
> Glowstone is built on top of Spigot.

At least learn what project you're commenting on before you criticize people. Glowstone is _not_ built on top of Spigot.

I do think multiple versions is a cool idea, and if it isn't supported by the main server then it should be available through some plugin means.

**Comment by mastercoms** [comment]
Multiple protocol support can be buggy, but we've done it before, though on the same release branch (1.9). Adding support across releases will be harder, but definitely not impossible.

And guys, don't criticize this member of our community so much. This feature request is clearly valid, and we should always appreciate new people coming into Glowstone and helping with ideas or code. All of us are contributors, even if some of us don't push code. Glowstone is after all a project beyond just the code and we need all sorts of people to do all sorts of things.

No one should be required to know Java to design our logo or report a bug request, so please never show this kind of disrespect to another human who just happens to not be entirely accurate on a subject, to no fault of his own.

**Comment by BSFishy** [comment]
This could easily be done with Bungeecord, and a plugin. Take Hypixel for example. They obviously do not use a "vanilla", if you will, server or bungeecord, but they still allow Minecraft version 1.8, 1.9, 1.10, and 1.11. I believe this is done by not allowing players to do anything with items and blocks that were implemented after 1.8, meaning that everyone would have the same features. I'm sure if you requested it, someone would make a plugin that made this functionality possible.

**Comment by gdude2002** [comment]
This has been brought up with the ProtocolSupport guys at https://github.com/ProtocolSupport/ProtocolSupport/issues/354.

**Comment by aramperes** [comment]
It has been [confirmed ](https://github.com/ProtocolSupport/ProtocolSupport/issues/354#issuecomment-278909577) by ProtocolSupport's developer that Glowstone is now fully supported.
