### ISSUE TITLE
Chat Error

### ISSUE THREAD

**Issue by Aslaak** [GlowstoneMC/Glowstone#382]
Hello,
I got an issue when a player talk just in the "lag" of the connection:
http://pastebin.com/nZYtyry9

Hope you will fix it :)
Thanks !

**Comment by aramperes** [comment]
I'm not sure what you mean by the 'lag' of the connection. Do you mean when the player is loading the chunks when joining?

**Comment by mastercoms** [comment]
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/entity/GlowPlayer.java#L1029

**Comment by mastercoms** [comment]
`getScoreboard()` seems to not exist?

**Comment by aramperes** [comment]
@mastercoms `scoreboard` field is set when the player joins (`join` method), so I would assume the chat message was sent before the PlayerLoginEvent. Pretty sure that would rely on having a bot sending the message when joining the server.

**Comment by mastercoms** [comment]
We can just add a null check, no harm in doing so. Also, as the OP was saying, on laggy connections, maybe joining will take a long time.

**Comment by aramperes** [comment]
Wouldn't it be better to deny the IncomingMessage handler if the player has not been assigned a profile yet?

**Comment by mastercoms** [comment]
Hm, yeah that would be a better solution, but do we really need to check the scoreboard display name?

I would rather someone be able to send a message at that time rather than to just ignore it, unless that is vanilla behavior.

**Comment by aramperes** [comment]
Fixed in #384.
