### ISSUE TITLE
Test server(s) for Glowstone++ server

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#39]
Would be cool to have a test server (or more than one) for helping develop and test Glowstone++. Some discussion about this in https://github.com/deathcap/GlowstonePlusPlus/issues/8 with @TekkitCommando  and @mastercoms. My thoughts, more servers the better, but some ideas:
- Bleeding-edge server automatically updated with the latest builds from CI (could add a post-build action to circle.yml to copy the build to the server. then somehow have it shutdown and restart with the new build). This could help catch new bugs from the latest commits. Players who want to help out with the project could join this server and mess around, exercise features, report bugs, but it wouldn't be suitable for longer-term play. No guarantee of no data loss, anything goes. Frequent world resets possible (each build? maybe overkill)
- A more stable server, manually managed and maintained, for longer-term gameplay testing. This could be considered a "real" server in that players would be able to expect the world to stay intact, not resetting unless necessary, so they would be free to build and explore. Although survival mode is lacking, may want to wait until it is fleshed out further before deploying this kind of server. But once its viable it could be advertised to the larger community, with the caveat that it is built on experimental server software, to gain interest in real-world testing of Glowstone++. Obviously such a server would require more administrative overhead, maintenance, moderators, etc., from volunteers (not it). The bleeding-edge server (smoke test? canary?) on the other hand would, if fully automated, have less overhead and still provide many useful development/testing benefits.

**Comment by jimmikaelkael** [comment]
I agree with both suggestions.

**Comment by TekkitCommando** [comment]
I can hook you up ;)

**Comment by TekkitCommando** [comment]
Just consider me a sponsor of Glowstone++ lol I will setup two servers for you :) If you have a Skype and you are willing to add me as a contact, send me your skype id to ethan_smith1997@icloud.com or just put it in the comments or if you don't prefer to give it out I understand

**Comment by TekkitCommando** [comment]
We can setup our Jar Directory to build Glowstone++ automatically

**Comment by TekkitCommando** [comment]
If you get to the point to where you want a website for this i think I can provide web hosting as well

**Comment by mastercoms** [comment]
Thank you for your generosity! We appreciate your support to the Glowstone++ project!

CircleCI uses SSH to deploy artifacts to servers. Do your servers support SSH?

**Comment by TekkitCommando** [comment]
Yes they do

**Comment by TekkitCommando** [comment]
Basically if you need something i won't mind looking into it

**Comment by TekkitCommando** [comment]
I would prefer having a means of contact other then github commenting tho if possible lol

**Comment by mastercoms** [comment]
Maybe Slack?

**Comment by TekkitCommando** [comment]
I will look that up

**Comment by TekkitCommando** [comment]
Ok looked at it, we can use that if you like

**Comment by TekkitCommando** [comment]
So any ideas of when you wanna do the servers?? :P

**Comment by mastercoms** [comment]
We have a server already, so closing this.
