### ISSUE TITLE
Frozen entity...

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#390]
![2016-12-06_14 45 15](https://cloud.githubusercontent.com/assets/9270074/20934618/ee5d714a-bbc2-11e6-9683-daa7f5fd3a65.png)
![2016-12-06_14 45 17](https://cloud.githubusercontent.com/assets/9270074/20934617/ee5d0642-bbc2-11e6-8d13-65976df0d7c4.png)
![2016-12-06_14 45 19](https://cloud.githubusercontent.com/assets/9270074/20934621/ee5f0c3a-bbc2-11e6-878b-1d2b1255d5af.png)
![2016-12-06_14 45 37](https://cloud.githubusercontent.com/assets/9270074/20934619/ee5dc690-bbc2-11e6-95b6-dcb2204335f0.png)
![2016-12-06_14 45 46](https://cloud.githubusercontent.com/assets/9270074/20934620/ee5e8d0a-bbc2-11e6-8a50-a30496a3aa8e.png)
![2016-12-06_14 45 52](https://cloud.githubusercontent.com/assets/9270074/20934622/ee6551bc-bbc2-11e6-97b6-08219c69caab.png)
![2016-12-06_14 45 53](https://cloud.githubusercontent.com/assets/9270074/20934623/ee7552b0-bbc2-11e6-9025-ebd0926f6a6e.png)
![2016-12-06_14 45 58](https://cloud.githubusercontent.com/assets/9270074/20934625/ee77944e-bbc2-11e6-904f-8cbd2457d2b8.png)
![2016-12-06_14 46 02](https://cloud.githubusercontent.com/assets/9270074/20934624/ee772c20-bbc2-11e6-8a96-047835c8152c.png)
![2016-12-06_14 46 07](https://cloud.githubusercontent.com/assets/9270074/20934626/ee77f786-bbc2-11e6-92ec-f93fb0a78d51.png)
![2016-12-06_14 46 11](https://cloud.githubusercontent.com/assets/9270074/20934627/ee7ab94e-bbc2-11e6-8ea2-2ba2d80b369f.png)

At the first use, this happens. Oh my god.

Simply the entity doesn't move at all, she is fixed in one place.

**Comment by ghost** [comment]
![2016-12-06_14 48 44](https://cloud.githubusercontent.com/assets/9270074/20934674/19b46ff6-bbc3-11e6-8b10-4907608f2458.png)

**Comment by ghost** [comment]
As far as i know entities are WIP

**Comment by ghost** [comment]
![2016-12-06_14 50 19](https://cloud.githubusercontent.com/assets/9270074/20934740/566ca332-bbc3-11e6-9279-e81711fa8642.png)

The chunk also does not load.

**Comment by ghost** [comment]
Create separate issue. Saying "not loading" will not help resolve problem.

**Comment by Paulomart** [comment]
Entity AI is currently not implemented. So they dont do anything.

**Comment by ghost** [comment]
@paulomart More, NO mob is moving.

**Comment by Kurimatzu** [comment]
@paulomart More, NO mob is moving.

**Comment by Paulomart** [comment]
Moving is entity AI.

**Comment by aramperes** [comment]
Closing this in favor of the entities Story (#396). Please note that knockback, physics and AI are not implemented and as such should not be considered as _bugs_. Also created an issue, #397, regarding the chunk rendering issue.
