### ISSUE TITLE
Comparators and Observers are not implemented

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#393]
Comparators, ObserverBlock, the direction you places is ignored.

Always in a fixed direction.

**Comment by ghost** [comment]
Also you cannot right-click and a comparator.

**Comment by ghost** [comment]
You can also stack comparator (is it possible)?

![2016-12-06_15 19 37](https://cloud.githubusercontent.com/assets/9270074/20935825/789d18b6-bbc7-11e6-849a-aac77dfa2e86.png)

**Comment by DaMatrix** [comment]
I don't think comparators have truly been implemented yet (correct me if I'm wrong) and therefore don't have (m)any of the features that they need.

**Comment by mastercoms** [comment]
Yeah it is not implemented.

**Comment by aramperes** [comment]
Observers have been implemented in 789d66f11e7e9c78f1f4fd47b6fa8ad5d1969b7b and 082a0191b64e4dc96110c15539609db0beab6b0e.

**Comment by aramperes** [comment]
Comparator placing and interaction have been implemented in dd464360575ca9e8df2404c39d8648493cd06c07.

**Comment by aramperes** [comment]
While comparator logic hasn't been implemented, I think this issue has been resolved.
