### ISSUE TITLE
Armor bar is not shown in HUD

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#394]
![2016-12-06_15 23 36](https://cloud.githubusercontent.com/assets/9270074/20935978/1320a524-bbc8-11e6-9f55-ed7cbc53f641.png)

Where's the HUD of armor that appears on top of the hearts?

It's a bug in the server?

**Comment by aramperes** [comment]
Correct me if I am wrong, but I think the armor bar is updated when sending the `EntityEquipmentMessage`  packet to the player about himself. I don't think that information is currently sent to the player itself.

Nop, it's set using the `generic.armor` attribute.

**Comment by aramperes** [comment]
Implemented in commit 61ed27c34015cc50272484249dc98f8ae7caa22a.
