### ISSUE TITLE
Chunks sometimes not rendering on the client

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#397]
Sometimes, a certain group of chunks will not load for the player until they are forcefully reloaded. I encountered this when traveling long distances or when teleporting to another player in unloaded chunks. This problem can often be fixed by using the `F3+A` keybind to refresh the chunks nearby.

![Screenshot by Kurimatzu](https://cloud.githubusercontent.com/assets/9270074/20934740/566ca332-bbc3-11e6-9279-e81711fa8642.png)

This is likely caused by chunk update packets not getting sent in the right timing/not frequently enough. The exact cause is not known.

**Comment by mastercoms** [comment]
https://github.com/GlowstoneMC/Glowstone/commit/5ca2234d50b60b441e3882c0508247188692a07f
https://github.com/GlowstoneMC/Glowstone/commit/a65ef5d399b967ca3617f7e8fcef463196a9ead2

I've tried to induce this bug after these changes, but I could not. Perhaps it is fixed?

**Comment by ghost** [comment]
I have had the same problem and I lost an entire map because something went catastrophically wrong with any chunk that had been built on already. When we tried to reload the map there was a small island of chunks and nothing would load. Ill have the same problem with the random wild teleport plugin, Ill go far away and end up underground due to no chunks loading fast enough to catch my free fall.

**Comment by mastercoms** [comment]
Would you happen to have a copy of that world? It would be nice to be able to see it.

**Comment by ghost** [comment]
I will check on the server computer later in the week. Its an hour from my current location. I go there once a week to do maintenance and plugins. I may have deleted the entire pile of plugins and server and redid all downloads. I thought a hacker on my server had screwed something up but the one player left on the server typed, LOL Your server is not loading at all. I then flew to him and confirmed he was seeing the same as me.

**Comment by ghost** [comment]
I snapped one screen shot of the event when it happened.
![2017-04-11_03 22 37](https://cloud.githubusercontent.com/assets/27814186/25293955/0be83058-26ab-11e7-9108-053c331e47c4.png)

**Comment by mastercoms** [comment]
Hm, then your issue is not related to this one. I'll open a new bug report.
