### ISSUE TITLE
Spawning NPCs

### ISSUE THREAD

**Issue by DenAbr** [GlowstoneMC/Glowstone#398]
BukkitAPI has unimplemented interface NPC. It would be great ability to spawn NPCs with custom skins and display names.

**Comment by BSFishy** [comment]
I would like to make an attempt to implement this feature. I think it will be fun learning how Glowstone works with sending packets, and what not.

**Comment by BSFishy** [comment]
I need a little bit of help on this one :P I would expect to be able to make this possible by making an entity, but when sent to the player, it is sent as a player. It seems easy, but I cannot find anything! Can someone point me in the correct direction?

**Comment by DenAbr** [comment]
Probably you should make new class extending GlowHumanEntity (as in Citizens) and working on it.

**Comment by BSFishy** [comment]
Right, but after looking at the GlowHumanEntity, I think that it will be trying to send packets to it. I can try.

**Comment by aramperes** [comment]
This requires a bit more work than just exending GlowHumanEntity, since clients don't accept that as a valid entity type (note that there is no `EntityType.HUMAN_ENTITY`), nor any network ID for it. You are going to have to fake a player to the client.

**Comment by BSFishy** [comment]
That's what I was thinking. I am thinking about making a GlowNPC class that extends GlowHumanEntity and all, but I am also thinking I am going to need to make some new net messages. I have not looked a huge amount into the code, and do not know **exactly** how it works, but would that be the general concept?

**Comment by DenAbr** [comment]
Seems like i've managed to do it!
![Notch NPC](http://dl3.joxi.net/drive/2017/01/08/0002/2404/182628/28/c23ce3495f.png)
This requires multiple edits in glowstone code:
1) Custom class, extending GlowHumanEntity with modified createSpawnMessage(adding PlayerListItem packet)
2) Create and bind new custom class in net.glowstone.io.entity package to save and load NPC entity
3) Additional EntityType enum
4) Registration of new class in EntityRegistry
5) New method to spawn our NPC in the GlowWorld class

**Comment by DenAbr** [comment]
There is another way to spawn NPCs through plugin.
https://github.com/DenAbr/GlowNPC

**Comment by aramperes** [comment]
@DenAbr very nice!
Does that plugin require modifications to Glowstone to support it?
I'm suggesting to use that as the official way to spawn NPC's and documenting it.

**Comment by DenAbr** [comment]
This plugin works without any Glowstone modifications.
But. There is some difficulties with saving NPCs created this way on server shut down. And that is why "native" NPCs built-in Glowstone looks better.

**Comment by aramperes** [comment]
@DenAbr what kind of difficulties?
I would prefer to stick with a plugin solution, because it's more uniform with the custom entities system

**Comment by DenAbr** [comment]
Plugin loads after world(can be fixed). 
I understand that plugin solution looks graceful but NPCs as integrated feature is more convenient.

**Comment by BSFishy** [comment]
You can make the plugin start on load, rather the default method, which i believe loads it before the world. Also, did you look at the documentation on [custom entities](https://github.com/GlowstoneMC/Glowstone/wiki/Creating-custom-entities)? If you have everything correct, it should save correctly. I have not looked at your code, but I am assuming that if it is not saving correctly, it does not have a proper `EntityStore`.

EDIT: It seems to be coded properly. Mind sharing the error?

**Comment by DenAbr** [comment]
I've already fixed this.

**Comment by aramperes** [comment]
Closing this as this feature has been implemented.
