### ISSUE TITLE
Mycelium block should spread.

### ISSUE THREAD

**Issue by jimmikaelkael** [GlowstoneMC/Glowstone#40]
The mycel block should receive random block ticking, then fade or spread accounting light level.
BlockFadeEvent and BlockSpreadEvent should be called accordingly.

References:
http://minecraft.gamepedia.com/Mycelium
http://minecraft.gamepedia.com/Tick

Will file a PR soon.

**Comment by TekkitCommando** [comment]
:+1:

**Comment by mastercoms** [comment]
+1

thank you for contributing so much to this project!
