### ISSUE TITLE
1.7-1.11.2 support

### ISSUE THREAD

**Issue by Mepth** [GlowstoneMC/Glowstone#411]
Good day, how do I add the-GlowStone support 1.7-1.11.2 versions protocolsupport not working. Thanks in advance.

**Comment by gdude2002** [comment]
I don't understand, are you looking for a build that supports multiple protocols?

**Comment by Mepth** [comment]
Can you make GlowStone build which support 1.7-1.11.2 version?

**Comment by gdude2002** [comment]
I'll take that to mean what I asked. 

Glowstone does not (nor does it plan to) support multiple major Minecraft protocol versions in the same build. It would take too much work, and encouraging users to use older versions of Minecraft only hurts the community (both the players and the developers). 

If users don't like the new combat changes, change the combat timeout gamerule and have them install a mod that removes their off-hand on the client.

**Comment by thelex0** [comment]
Hi! Сan you make GlowStone for multi protocols 
https://www.spigotmc.org/resources/protocolsupport.7201/

**Comment by gdude2002** [comment]
If you want to use this plugin, you need to talk to the developer of the plugin. We will not be implementing `net.minecraft.server`.

**Comment by thelex0** [comment]
something else
Сan add in GlowStone API for packet sensitivity

**Comment by gdude2002** [comment]
I believe you can currently hook into it, but we don't have explicit support for it right now. 

Related: #380

**Comment by thelex0** [comment]
how to make GlowStone stable at large number of players

**Comment by gdude2002** [comment]
It should be stable. If not, make another issue about performance issues. 

This issue is derailing, so I'm going to lock it. Make another if you have a different problem.

**Comment by gdude2002** [comment]
It has been [confirmed ](https://github.com/ProtocolSupport/ProtocolSupport/issues/354#issuecomment-278909577) by ProtocolSupport's developer that Glowstone is now fully supported. You should be able to use new versions with Glowstone.
