### ISSUE TITLE
Вы даун

### ISSUE THREAD

**Issue by Mepth** [GlowstoneMC/Glowstone#413]
Вы даун

**Comment by gdude2002** [comment]
This roughly translates to "you down".

This isn't an issue. It's two words. Please start behaving or I will be forced to remove you from the repository.

**Comment by BeYkeRYkt** [comment]
These two words are insulting associated with Down's syndrome (For those who are not versed in the modern "Russian insults") on the similarity of "you're stupid." He's just a troll.

**Comment by gdude2002** [comment]
Huh, that's good to know. Thanks.
