### ISSUE TITLE
Custom crafting recipes aren't working

### ISSUE THREAD

**Issue by alula** [GlowstoneMC/Glowstone#414]
Registering craftings using Bukkit.addRecipe() doesn't work, but works fine on Spigot.

Glowstone build: `#301`

**Comment by mastercoms** [comment]
What recipe did you register?

**Comment by aramperes** [comment]
@gabixdev 
Please include a code snippet of your plugin in order for us to debug this issue.

**Comment by picknchew** [comment]
Can reproduce. Using the addRecipe method will register the recipe, however the item that it should craft will not appear in the result slot. Shift clicking the result slot will *sometimes* craft the item. Clicking the result slot makes the server think that the client sent an incorrect packet.

Basically, the client thinks the result slot is air. The server thinks the result slot is the result.

**Comment by alula** [comment]
https://gist.github.com/gabixdev/392df453bf32b8656ee6bb87ab593004

**Comment by kamcio96** [comment]
@gabixdev Did you try without config?

**Comment by alula** [comment]
@kamcio96 same behavior without config, it's client <-> server problem...
