### ISSUE TITLE
Unimplemented BossBar API

### ISSUE THREAD

**Issue by alula** [GlowstoneMC/Glowstone#417]
The Bukkit Bossbar API seems to not be implemented, calling addPlayer causes NullPointerException.

Build: 314 and earlier

```java
BossBar x = Bukkit.createBossBar("Generowanie...", BarColor.YELLOW, BarStyle.SOLID);
x.addPlayer(((Player) cs).getPlayer());
```

**Comment by aramperes** [comment]
Implemented in 97ae41bf29d6f549acd0a089343da5262d3a2335.
