### ISSUE TITLE
Wrong structure generation

### ISSUE THREAD

**Issue by qmnl** [GlowstoneMC/Glowstone#422]
Title: Jungle temple generated wrongly

Glowstone build: 2017.1.1.8-SNAPSHOT-"cd891fc"-MC1.11.2 (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Jungle temples dont have walls:

![Imgur](http://i.imgur.com/GJEPmGW.png)
![Imgur](http://i.imgur.com/gNz0sii.png)

[Imgur](http://imgur.com/a/Q6Pg1)

I tried loading up a normal minecraft world with that seed, but the world looks completly different (because of the complete rewrite)
The chest loot is generated correctly.

Reproduce:

1. Download Glowstone

 > wget https://bamboo.gserv.me/artifact/GSPP-SRV/shared/build-latestSuccessful/Version-Independent-Server-JAR/glowstone.jar

2. Change seed to -7813473870166093064 (in config/glowstone.yml)
3. Teleport to

 > /tp -134 88 -158
 > /tp 293 74 248

**Comment by mastercoms** [comment]
I've investigated this problem, and it's quite strange as to why it occurs. Structure generation doesn't happen due to a lot of boolean mismatches, but the fact that chests spawn even though that code doesn't run is very weird.

**Comment by mastercoms** [comment]
Well, that was annoying but also fun to fix.

**Comment by qmnl** [comment]
Thank you for the quick support!

**Comment by mastercoms** [comment]
No problem, and thanks for bringing this bug to our attention!
