### ISSUE TITLE
Water and Lava Buckets behaviour / No lava damage

### ISSUE THREAD

**Issue by adlradlr** [GlowstoneMC/Glowstone#428]
Glowstone build: #359

After placing a lava bucket onto the ground, it briefly flashes in the position placed, but then disappears, however I now have an empty Bucket entity in my inventory, which can be placed again to place lava, which remains and behaves normally.
- This empty bucket entity after the first use can be thrown and a full lava bucket appears, and when picked up is also full. 
- This empty bucket entity after the first use can be used to pick up a water source, and a water bucket entity appears in my inventory, however lava appears in it's position when placed and the water disappears.

Lava and water are interchangeable here, and the scenario can be produced both ways.

![2017-02-27_11 11 16](https://cloud.githubusercontent.com/assets/26056727/23359650/1c37697e-fcdf-11e6-81a9-fc82b6cb438e.png)
![2017-02-27_11 11 23](https://cloud.githubusercontent.com/assets/26056727/23359658/24b97772-fcdf-11e6-90bd-cdf99c6f4f1c.png)

**Edit**
Lava placed deals no damage
![2017-02-27_11 27 08](https://cloud.githubusercontent.com/assets/26056727/23359769/c6fecb86-fcdf-11e6-9a8f-a4bfd0df3d96.png)

**Comment by mastercoms** [comment]
Figured out that problem here. The water bucket is used twice, once to place the water, and then to pick it back up. There's some duplication in method usage.

You can test this by placing the water, but rapidly looking away from it. This prevents you from picking it up again.
