### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by adlradlr** [GlowstoneMC/Glowstone#430]
Glowstone build 359 

level seed used = '-7955155822622757578'

I got this seed from a website claiming that it spawns you near a desert temple and village, however  Glowstone wasn't generating the same world using the same seed, as well as having vastly varying spawn points every time.

After generating the world a couple of times using Glowstone, I confirmed that it wasn't the same world (temple/village not where the control group coordinates indicate) and although the spawn points varied a lot, the differently generated world was consistent across the attempts.

![spat1](https://cloud.githubusercontent.com/assets/26056727/23361784/441688fc-fcea-11e6-955c-0339ed0ddd67.png)

![vanillaat1](https://cloud.githubusercontent.com/assets/26056727/23361785/467071ee-fcea-11e6-9e24-7b1623b92bc3.png)

![spigotat1](https://cloud.githubusercontent.com/assets/26056727/23361788/479bc6f4-fcea-11e6-8082-77fd0ee3a074.png)

![glowat1](https://cloud.githubusercontent.com/assets/26056727/23361791/4bcf153c-fcea-11e6-96b5-affa8405d7a6.png)

![glowat2](https://cloud.githubusercontent.com/assets/26056727/23361794/4ea90344-fcea-11e6-9643-f0257c699921.png)

![glowat3](https://cloud.githubusercontent.com/assets/26056727/23361797/5101722a-fcea-11e6-9b65-debcdf982673.png)

**Comment by gdude2002** [comment]
Our world generator doesn't match vanilla - the main reason for this is, well, it's almost impossible to do in a clean-room implementation. We can't use any Mojang code, and we can't use their source for inspiration - we do try to generate a vanilla-like world, but parity won't be possible.

**Comment by aramperes** [comment]
Hey, thanks for the bug report.

Unfortunately, since Glowstone consists of a complete rewrite, it is practically impossible to follow the same Random chain. A fix is therefore highly improbable, so I am closing this issue.
