### ISSUE TITLE
Fall Damage Calculations

### ISSUE THREAD

**Issue by adlradlr** [GlowstoneMC/Glowstone#432]
Glowstone build 361 

Fall damage taken differs from vanilla under the same conditions.

![untitled](https://cloud.githubusercontent.com/assets/26056727/23365857/8ee5a676-fcfc-11e6-828c-5dc977237c71.png)

After doing some testing it seems that only fallen damage taken when jumping differs from vanilla. I only went up to y+10 as it became linear at that point and should be easy to extrapolate.

**Comment by mastercoms** [comment]
Thank you for this well formatted issue! I love the table!

About this difference, vanilla does not measure displacement but total distance traveled in the air (so entities that fly up and down on a leash will have massive fall damage). But I think that it ignores player jumping going up. I'll see what I can do.
