### ISSUE TITLE
tellraw failed to parse JSON

### ISSUE THREAD

**Issue by AuroraLS3** [GlowstoneMC/Glowstone#433]
Glowstone build: 8a57f8a or 2017.2.0.20-SNAPSHOT-"8a57f8a"-MC1.11.2

JSON:
```
[
   "",
   {
      "text":"Click Me",
      "underlined":true,
      "clickEvent":{
         "action":"open_url",
         "value":"http://localhost:8804/bAkEd/player/Rsl1122"
      }
   }
]
```
Valid according to https://jsonformatter.curiousconcept.com/
In one line:
`["",{"text":"Click Me","underlined":true,"clickEvent":{"action":"open_url","value":"http://localhost:8804/bAkEd/player/Rsl1122"}}]`

I was testing whether or not my plugins work on glowstone, and few commands are using tellraw to give clickable links.

---

Ran a console command to test:
```
>tellraw Rsl1122 ["",{"text":"Click Me","underlined":true,"clickEvent":{"action":"open_url","value":"http://localhost:8804/bAkEd/player/Rsl1122"}}]
16:51:56 [INFO] Failed to parse JSON
```

**Comment by gdude2002** [comment]
Might be related to #406
