### ISSUE TITLE
Crafting table/Hot bar 

### ISSUE THREAD

**Issue by adlradlr** [GlowstoneMC/Glowstone#434]
Glowstone build 361 

The right-most slot on the hot bar turns items invisible when looking at the Crafting Table UI. It only seems to be this slot as well as only on the crafting table, other blocks with UIs seem to be fine. 

![2017-02-27_15 57 22](https://cloud.githubusercontent.com/assets/26056727/23368560/2bb2b7ba-fd06-11e6-92f6-dc007e5f4faa.png)

![2017-02-27_15 57 29](https://cloud.githubusercontent.com/assets/26056727/23368562/2cbe2644-fd06-11e6-828e-c9b4cd3ffab2.png)

Also the slots seemed to have a reversed priority compared to vanilla when shift-clicking items into the hot bar from any UI. They fill this right most slot on the hot bar first and work across to the left, compared to left to right on vanilla.

![2017-02-27_15 59 04](https://cloud.githubusercontent.com/assets/26056727/23368691/8822e402-fd06-11e6-9c17-8f3507e2075d.png)

This is log when you click the item in the invisible slot whilst using the Crafting Table.
```
15:56:31 [WARNING] pandanoir: illegal argument while handling click: java.lang.IllegalArgumentException: Slot out of range [0,46): -1
15:56:31 [INFO] pandanoir: [rejected] WindowClickMessage(id=0, slot=-1, button=1, transaction=29, mode=0, item=ItemStack{AIR x 0})
```

**Comment by mastercoms** [comment]
I think this has something to do with the offhand slot.

**Comment by mastercoms** [comment]
Vanilla is consistent with Glowstone with filling inventory slots. It starts with the right most slot in each row, then goes to the left.

**Comment by mastercoms** [comment]
Confirmed to have to do with the offhand slot. If you have an item in the offhand slot, it will appear in the right most slot in the crafting table inventory.

**Comment by mastercoms** [comment]
Is there any reason for Glowstone to separate armor and offhand from the rest of the player inventory?

**Comment by mastercoms** [comment]
Some progress has been made in https://github.com/GlowstoneMC/Glowstone/commit/daea24d2021e108d8656bfe719a25f6810b03d04.
