### ISSUE TITLE
Fire is not affected by rain

### ISSUE THREAD

**Issue by AuroraLS3** [GlowstoneMC/Glowstone#435]
Title: Fire is not affected by rain

Glowstone build: 8a57f8a

After setting Grass and Tallgrass on fire they stayed lit (while tunderstorm was raging).
http://puu.sh/umjzl/732b4553b8.png

Might be related to #130

**Comment by adlradlr** [comment]
Glowstone build 361 

Also appears that fire spread isn't working correctly 

![2017-02-27_17 32 44](https://cloud.githubusercontent.com/assets/26056727/23372331/0af000b6-fd13-11e6-996c-ba0d1bb5c902.png)

**Comment by mastercoms** [comment]
Hm, fire spread should be working. Maybe some upgrades to our tick system broke it.

**Comment by Christian7573** [comment]
![image](https://cloud.githubusercontent.com/assets/11007603/26025653/e8aee4e8-37b1-11e7-9578-331abe280055.png)
I'm not taking damage lol

**Comment by mastercoms** [comment]
That's an unrelated issue, it's just that we don't check if a player is in fire.

**Comment by Christian7573** [comment]
Oh

**Comment by mastercoms** [comment]
Will be fixed in this month's blocks update.
