### ISSUE TITLE
TNT Knockback 

### ISSUE THREAD

**Issue by adlradlr** [GlowstoneMC/Glowstone#438]
Glowstone build 361

- TNT still knocks you back much further than vanilla. #97 #396 

- TNT knockback does not affect the player if they are flying in Creative mode in vanilla, knockback still applied regardless if flying or not in Glowstone.

![2017-02-28_11 03 33](https://cloud.githubusercontent.com/assets/26056727/23403121/99126b52-fda6-11e6-82d5-6b42b2d0547f.png)

![2017-02-28_11 10 58](https://cloud.githubusercontent.com/assets/26056727/23403126/9f1883ba-fda6-11e6-80b9-fb57a276e086.png)

**Comment by mastercoms** [comment]
I've been wrestling with this one for a while. I'm still not sure if the explosion packet tells the client to be knocked back or not.
