### ISSUE TITLE
Furnace not work

### ISSUE THREAD

**Issue by jawaw** [GlowstoneMC/Glowstone#440]
Glowstone's bug. Furnace not work.

**Comment by mastercoms** [comment]
Hm, perhaps this has something to do with it not being updated for a newer tick system? Though last time I checked, it was working. I'll have to see what we changed that broke it.

**Comment by mastercoms** [comment]
Yep, it just doesn't register a tick rate, which is required for the new tick system. I'll fix that pretty soon.
