### ISSUE TITLE
Unfinalizing of some classes

### ISSUE THREAD

**Issue by DenAbr** [GlowstoneMC/Glowstone#442]
I really don't understand why bunch of classes in net.glowstone.entity package are final.
I'm working on HolographicDisplays port and own NPC plugin and I really need to create classes extending EntityBoundingBox, GlowItem, etc. but these classes are final.

**Comment by mastercoms** [comment]
Yeah I don't know why they're final either. I'll change them as soon as I finish up with my gpgpu work for the day.

**Comment by DenAbr** [comment]
I think GlowSession should be unfinalized too

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/7b708b2127d180ca18ecec0a4d041a22cf45346d
