### ISSUE TITLE
Stairs and slabs always place on the bottom half of the block

### ISSUE THREAD

**Issue by Pokechu22** [GlowstoneMC/Glowstone#443]
Title: **Stairs and slabs always place on the bottom half of the block**

Glowstone build: Manually compiled based off of 9e0e517c9051598b90de9a66ad443b759381edd7

Stairs and slabs seem to always place on the lower half of the block, even if the upper half of the block is clicked.  This looks like a recent regression, as it is clear that there _is_ code related to upside down slabs; it just never triggers.

To reproduce, simply grab a slab and attempt to place it against the upper half of the block; clientside it will place there, but then it will be "corrected" to the lower half.

---

Most likely, this happened when 1.11 support was added, as the slab code seems to be checking for placement positions at or above 8 pixels, but [in 16w39b the range used in Player Block Placement was changed to 0.0 to 1.0 from 0 to 15](http://wiki.vg/Protocol_History#16w39c).  Either the stair/slab code should be changed, or the packet handler for Player Block Placement increase the bounds to match the old ones.

**Comment by mastercoms** [comment]
Thanks for the detailed report. I'll fix this soon.

**Comment by mastercoms** [comment]
Should the protocol documentation be updated, then? http://wiki.vg/Protocol#Player_Block_Placement

**Comment by mastercoms** [comment]
I think it was changed the other way around: 0 - 15 to 0.0 - 1.0.

**Comment by mastercoms** [comment]
Oh, I just misread everything entirely. Please shame me forever.

**Comment by Pokechu22** [comment]
That fixes it for slabs, but it's still present for stairs (with more or less the same code).

**Comment by mastercoms** [comment]
I'm really sorry about these mistakes, I didn't sleep very well last night.

**Comment by mastercoms** [comment]
Alright, should be fixed now.

**Comment by Pokechu22** [comment]
No problem, and good morning!

I probably should have checked more completely before creating the issue, but it looks like there's one more block that's effected by this bug: trapdoors (which currently compare y to `7.5`).  I'm not sure if that's the right comparison height (it probably should have been `8` like the rest of the blocks before the 1.11 changes, so `.5` now), but in any case that also is broken.

**Comment by mastercoms** [comment]
Already fixed that one in https://github.com/GlowstoneMC/Glowstone/commit/789da9e18e03f641c8ea8cef9bed41a50e9834a4.

And thank you. Good morning to you too!
