### ISSUE TITLE
Entity physics overpredicts collision target

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#447]
The console seems to get spammed when the player doesn't have 5 blocks under him or when he is not standing on 5 blocks, and sometimes the player is getting kicked. For example, if the player is standing on 4 blocks (or below that), the console is getting spammed with the message "(Player) moved too quickly!" and the player is getting kicked sometimes.

This happened on Glowstone build [#398](https://bamboo.gserv.me/browse/GSPP-SRV-398) with 0 plugins, but i'm pretty sure it happened on earlier builds as well.

---

Standing on 5 blocks, no spamming/kicking.

![5 blocks](https://cloud.githubusercontent.com/assets/18402896/23931926/35224d5e-090b-11e7-90aa-899be6347393.jpg)

Standing on 4 blocks, console getting spammed and sometimes player getting kicked.

![4 blocks](https://cloud.githubusercontent.com/assets/18402896/23931952/641ef30a-090b-11e7-80d8-1977b58cd95e.jpg)

**Comment by mastercoms** [comment]
Does this happen on [#365](https://bamboo.gserv.me/browse/GSPP-SRV-365)? (before [entity physics](https://github.com/GlowstoneMC/Glowstone/commit/719a9396a558ab14eb2a49ae46084f5c8f1ba495#diff-1ee1f52992d31fbb1d1a66eebbf3c9cf))

**Comment by ghost** [comment]
No, the console is not getting spammed at all on [#365](https://bamboo.gserv.me/browse/GSPP-SRV-365), not even when standing on one block.

**Comment by mastercoms** [comment]
Does it happen on [#366](https://bamboo.gserv.me/browse/GSPP-SRV-366) (with entity physics)?

**Comment by ghost** [comment]
Yes, this is happening on [#366](https://bamboo.gserv.me/browse/GSPP-SRV-366).

**Comment by mastercoms** [comment]
Ok, I'll see what code path introduced in that commit caused this regression.

**Comment by mastercoms** [comment]
Entity physics is the problem. I am working on the [`physics-staging`](https://github.com/GlowstoneMC/Glowstone/tree/physics-staging) branch to fix this issue and also to add more accurate physics simulation.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/44ba17b6ce3f50a9f072cc038e95d4b01fa34992.
