### ISSUE TITLE
Incorrect hit knockback velocity

### ISSUE THREAD

**Issue by DenAbr** [GlowstoneMC/Glowstone#448]
[Video](https://youtu.be/_J44QsmVt3c)

**Comment by gdude2002** [comment]
Thanks for the report!

Wow, that's.. pretty wonky.

**Comment by mastercoms** [comment]
I haven't been able to reproduce this. @DenAbr could you confirm that the bug was fixed?

**Comment by DenAbr** [comment]
Checked with the latest build. Still not fixed.

**Comment by mastercoms** [comment]
Is this a player or human entity?

**Comment by DenAbr** [comment]
Real player

**Comment by DenAbr** [comment]
It also happens with mobs

**Comment by mastercoms** [comment]
Does the direction change if you are in a different x/z sign? For example, in the video you could have been in -220x and 200z, but does the direction of knockback change if you were to go to 220x and -200z, etc?

**Comment by DenAbr** [comment]
No, it doesn't. When I was checking this I've found 2 new issues: sometimes player respawn packet didn't send and head/body rotation is confused(you can see this in video)

**Comment by mastercoms** [comment]
Physics/knockback issues should be fixed in https://github.com/GlowstoneMC/Glowstone/commit/03d9e543a4e7b6e13671ab77680fae106af36be5.

**Comment by DenAbr** [comment]
[Still not fixed](https://youtu.be/kSxaF8pQIv4)

**Comment by mastercoms** [comment]
Ok, can you test with TNT knockback? Maybe this is an issue with head rotation.

**Comment by DenAbr** [comment]
TNT knockback is similar. Damage radius equals block break radius and TNT always kills player when he is inside damage area.

**Comment by mastercoms** [comment]
Can you test it in creative mode so you don't die?

**Comment by DenAbr** [comment]
[More interesting behaviour. ](https://youtu.be/qn5d4-WXuAE)

**Comment by aramperes** [comment]
Closing in favor of #501
