### ISSUE TITLE
SpongeAPI event implementations

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#45]
API: https://github.com/SpongePowered/SpongeAPI

Useful references:
Forge implementation: https://github.com/SpongePowered/Sponge
Vanilla Minecraft implementation: https://github.com/SpongePowered/SpongeVanilla
Shared code: https://github.com/SpongePowered/SpongeCommon
Discussion on multi-API coexistence (Bukkit+Sponge):  https://github.com/GlowstoneMC/Glowstone/issues/498
- [ ] org.spongepowered.api.event.AbstractEvent
- [ ] org.spongepowered.api.event.attribute.AttributeBaseChangedEvent
- [ ] org.spongepowered.api.event.attribute.AttributeEvent
- [ ] org.spongepowered.api.event.attribute.AttributeModifierAddedEvent
- [ ] org.spongepowered.api.event.attribute.AttributeModifierRemovedEvent
- [ ] org.spongepowered.api.event.ban.IpBanEvent
- [ ] org.spongepowered.api.event.ban.IpPardonEvent
- [ ] org.spongepowered.api.event.ban.PlayerBanEvent
- [ ] org.spongepowered.api.event.ban.PlayerPardonEvent
- [ ] org.spongepowered.api.event.ban.UserBanEvent
- [ ] org.spongepowered.api.event.ban.UserPardonEvent
- [x] org.spongepowered.api.event.block.BlockBreakEvent
- [ ] org.spongepowered.api.event.block.BlockBurnEvent
- [ ] org.spongepowered.api.event.block.BlockChangeEvent
- [ ] org.spongepowered.api.event.block.BlockDispenseEvent
- [x] org.spongepowered.api.event.block.BlockEvent
- [ ] org.spongepowered.api.event.block.BlockHarvestEvent
- [ ] org.spongepowered.api.event.block.BlockIgniteEvent
- [ ] org.spongepowered.api.event.block.BlockInteractEvent
- [ ] org.spongepowered.api.event.block.BlockMoveEvent
- [ ] org.spongepowered.api.event.block.BlockPlaceEvent
- [ ] org.spongepowered.api.event.block.BlockRandomTickEvent
- [ ] org.spongepowered.api.event.block.BlockRedstoneUpdateEvent
- [ ] org.spongepowered.api.event.block.BlockUpdateEvent
- [ ] org.spongepowered.api.event.block.BulkBlockEvent
- [ ] org.spongepowered.api.event.block.FloraGrowEvent
- [ ] org.spongepowered.api.event.block.FluidSpreadEvent
- [ ] org.spongepowered.api.event.block.LeafDecayEvent
- [ ] org.spongepowered.api.event.block.tile.BrewingStandBrewEvent
- [ ] org.spongepowered.api.event.block.tile.BrewingStandEvent
- [ ] org.spongepowered.api.event.block.tile.FurnaceConsumeFuelEvent
- [ ] org.spongepowered.api.event.block.tile.FurnaceEvent
- [ ] org.spongepowered.api.event.block.tile.FurnaceSmeltItemEvent
- [ ] org.spongepowered.api.event.block.tile.SignChangeEvent
- [ ] org.spongepowered.api.event.block.tile.SignEvent
- [ ] org.spongepowered.api.event.block.tile.TileEntityEvent
- [ ] org.spongepowered.api.event.entity.BulkEntityEvent
- [ ] org.spongepowered.api.event.entity.EntityAboutToConstructEvent
- [ ] org.spongepowered.api.event.entity.EntityBreakBlockEvent
- [ ] org.spongepowered.api.event.entity.EntityBreedEvent
- [ ] org.spongepowered.api.event.entity.EntityChangeBlockEvent
- [ ] org.spongepowered.api.event.entity.EntityChangeHealthEvent
- [ ] org.spongepowered.api.event.entity.EntityCollisionEvent
- [ ] org.spongepowered.api.event.entity.EntityCollisionWithBlockEvent
- [ ] org.spongepowered.api.event.entity.EntityCollisionWithEntityEvent
- [ ] org.spongepowered.api.event.entity.EntityConstructingEvent
- [ ] org.spongepowered.api.event.entity.EntityDeathEvent
- [ ] org.spongepowered.api.event.entity.EntityDismountEvent
- [ ] org.spongepowered.api.event.entity.EntityDisplaceEvent
- [ ] org.spongepowered.api.event.entity.EntityDropItemEvent
- [ ] org.spongepowered.api.event.entity.EntityEnterPortalEvent
- [ ] org.spongepowered.api.event.entity.EntityEquipmentChangeEvent
- [ ] org.spongepowered.api.event.entity.EntityEvent
- [ ] org.spongepowered.api.event.entity.EntityExitPortalEvent
- [ ] org.spongepowered.api.event.entity.EntityExpireEvent
- [ ] org.spongepowered.api.event.entity.EntityExplosionEvent
- [ ] org.spongepowered.api.event.entity.EntityHarvestBlockEvent
- [ ] org.spongepowered.api.event.entity.EntityIgniteEvent
- [ ] org.spongepowered.api.event.entity.EntityInteractBlockEvent
- [ ] org.spongepowered.api.event.entity.EntityInteractEntityEvent
- [ ] org.spongepowered.api.event.entity.EntityInteractEvent
- [ ] org.spongepowered.api.event.entity.EntityItemConsumeEvent
- [ ] org.spongepowered.api.event.entity.EntityLeashEvent
- [ ] org.spongepowered.api.event.entity.EntityMountEvent
- [ ] org.spongepowered.api.event.entity.EntityMoveEvent
- [ ] org.spongepowered.api.event.entity.EntityPickUpItemEvent
- [ ] org.spongepowered.api.event.entity.EntityPlaceBlockEvent
- [ ] org.spongepowered.api.event.entity.EntityPotionEffectChangeEvent
- [ ] org.spongepowered.api.event.entity.EntitySpawnEvent
- [ ] org.spongepowered.api.event.entity.EntityTameEvent
- [ ] org.spongepowered.api.event.entity.EntityTargetEntityEvent
- [ ] org.spongepowered.api.event.entity.EntityTeleportEvent
- [ ] org.spongepowered.api.event.entity.EntityUnleashEvent
- [ ] org.spongepowered.api.event.entity.EntityUpdateEvent
- [ ] org.spongepowered.api.event.entity.ExplosionPrimeEvent
- [ ] org.spongepowered.api.event.entity.living.human.fishing.HumanCastFishingLineEvent
- [ ] org.spongepowered.api.event.entity.living.human.fishing.HumanFishEvent
- [ ] org.spongepowered.api.event.entity.living.human.fishing.HumanHookedEntityEvent
- [ ] org.spongepowered.api.event.entity.living.human.fishing.HumanRetractFishingLineEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanBreakBlockEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanChangeBlockEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanChangeGameModeEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanChangeHealthEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanDeathEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanDropItemEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanEnterBedEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanEquipmentChangeEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanExpChangeEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanHarvestBlockEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanInteractBlockEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanInteractEntityEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanInteractEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanItemConsumeEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanLeaveBedEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanLevelChangeEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanMoveEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanPickUpItemEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanPlaceBlockEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanSleepEvent
- [ ] org.spongepowered.api.event.entity.living.human.HumanUpdateEvent
- [ ] org.spongepowered.api.event.entity.living.LivingAddPotionEffectEvent
- [ ] org.spongepowered.api.event.entity.living.LivingBreakBlockEvent
- [ ] org.spongepowered.api.event.entity.living.LivingChangeBlockEvent
- [ ] org.spongepowered.api.event.entity.living.LivingChangeHealthEvent
- [ ] org.spongepowered.api.event.entity.living.LivingDeathEvent
- [ ] org.spongepowered.api.event.entity.living.LivingDropItemEvent
- [ ] org.spongepowered.api.event.entity.living.LivingEquipmentChangeEvent
- [ ] org.spongepowered.api.event.entity.living.LivingEvent
- [ ] org.spongepowered.api.event.entity.living.LivingExpirePotionEffectEvent
- [ ] org.spongepowered.api.event.entity.living.LivingHarvestBlockEvent
- [ ] org.spongepowered.api.event.entity.living.LivingInteractBlockEvent
- [ ] org.spongepowered.api.event.entity.living.LivingInteractEntityEvent
- [ ] org.spongepowered.api.event.entity.living.LivingInteractEvent
- [ ] org.spongepowered.api.event.entity.living.LivingItemConsumeEvent
- [ ] org.spongepowered.api.event.entity.living.LivingMoveEvent
- [ ] org.spongepowered.api.event.entity.living.LivingPickUpItemEvent
- [ ] org.spongepowered.api.event.entity.living.LivingPlaceBlockEvent
- [ ] org.spongepowered.api.event.entity.living.LivingPotionEffectEvent
- [ ] org.spongepowered.api.event.entity.living.LivingRemovePotionEffectEvent
- [ ] org.spongepowered.api.event.entity.living.LivingUpdateEvent
- [ ] org.spongepowered.api.event.entity.living.player.PlayerResourcePackStatusEvent
- [ ] org.spongepowered.api.event.entity.minecart.MinecartEvent
- [ ] org.spongepowered.api.event.entity.player.fishing.PlayerCastFishingLineEvent
- [ ] org.spongepowered.api.event.entity.player.fishing.PlayerFishEvent
- [ ] org.spongepowered.api.event.entity.player.fishing.PlayerHookedEntityEvent
- [ ] org.spongepowered.api.event.entity.player.fishing.PlayerRetractFishingLineEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerBreakBlockEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerChangeBlockEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerChangeGameModeEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerChangeHealthEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerChangeWorldEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerChatEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerDeathEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerDropItemEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerEnterBedEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerEquipmentChangeEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerExpChangeEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerHarvestBlockEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerInteractBlockEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerInteractEntityEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerInteractEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerItemConsumeEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerJoinEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerKickEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerLeaveBedEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerLevelChangeEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerMoveEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerPickUpItemEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerPlaceBlockEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerQuitEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerRespawnEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerSleepEvent
- [ ] org.spongepowered.api.event.entity.player.PlayerUpdateEvent
- [ ] org.spongepowered.api.event.entity.player.UserEvent
- [ ] org.spongepowered.api.event.entity.ProjectileLaunchEvent
- [x] org.spongepowered.api.event.Event
- [x] org.spongepowered.api.event.ExperienceEvent
- [x] org.spongepowered.api.event.GameEvent
- [ ] org.spongepowered.api.event.inventory.BlockInventoryEvent
- [ ] org.spongepowered.api.event.inventory.BrewEvent
- [ ] org.spongepowered.api.event.inventory.BulkItemResultEvent
- [ ] org.spongepowered.api.event.inventory.ContainerEvent
- [ ] org.spongepowered.api.event.inventory.ContainerOpenEvent
- [ ] org.spongepowered.api.event.inventory.CraftItemEvent
- [ ] org.spongepowered.api.event.inventory.InventoryClickEvent
- [ ] org.spongepowered.api.event.inventory.InventoryCloseEvent
- [ ] org.spongepowered.api.event.inventory.InventoryEvent
- [ ] org.spongepowered.api.event.inventory.ItemDropEvent
- [ ] org.spongepowered.api.event.inventory.ItemEvent
- [ ] org.spongepowered.api.event.inventory.ItemExpireEvent
- [ ] org.spongepowered.api.event.inventory.ItemMergeEvent
- [ ] org.spongepowered.api.event.inventory.ItemResultEvent
- [ ] org.spongepowered.api.event.inventory.ViewerEvent
- [ ] org.spongepowered.api.event.message.CommandEvent
- [ ] org.spongepowered.api.event.message.MessageEvent
- [ ] org.spongepowered.api.event.net.PlayerConnectionEvent
- [ ] org.spongepowered.api.event.net.PlayerConnectionRegisterChannelEvent
- [ ] org.spongepowered.api.event.net.PlayerConnectionUnregisterChannelEvent
- [ ] org.spongepowered.api.event.rcon.RconCommandEvent
- [ ] org.spongepowered.api.event.rcon.RconEvent
- [ ] org.spongepowered.api.event.rcon.RconLoginEvent
- [ ] org.spongepowered.api.event.server.query.BasicQueryEvent
- [ ] org.spongepowered.api.event.server.query.FullQueryEvent
- [ ] org.spongepowered.api.event.server.query.QueryEvent
- [ ] org.spongepowered.api.event.server.StatusPingEvent
- [ ] org.spongepowered.api.event.SpongeEventFactory
- [x] org.spongepowered.api.event.state.ConstructionEvent
- [ ] org.spongepowered.api.event.state.InitializationEvent
- [ ] org.spongepowered.api.event.state.LoadCompleteEvent
- [ ] org.spongepowered.api.event.state.PostInitializationEvent
- [x] org.spongepowered.api.event.state.PreInitializationEvent
- [ ] org.spongepowered.api.event.state.ServerAboutToStartEvent
- [ ] org.spongepowered.api.event.state.ServerStartedEvent
- [ ] org.spongepowered.api.event.state.ServerStartingEvent
- [ ] org.spongepowered.api.event.state.ServerStoppedEvent
- [x] org.spongepowered.api.event.state.ServerStoppingEvent
- [x] org.spongepowered.api.event.state.StateEvent
- [ ] org.spongepowered.api.event.stats.AchievementEvent
- [ ] org.spongepowered.api.event.stats.StatisticChangeEvent
- [ ] org.spongepowered.api.event.weather.LightningStrikeEvent
- [ ] org.spongepowered.api.event.weather.WeatherChangeEvent
- [ ] org.spongepowered.api.event.weather.WeatherEvent
- [ ] org.spongepowered.api.event.world.ChunkEvent
- [ ] org.spongepowered.api.event.world.ChunkForcedEvent
- [ ] org.spongepowered.api.event.world.ChunkLoadEvent
- [ ] org.spongepowered.api.event.world.ChunkPostGenerateEvent
- [ ] org.spongepowered.api.event.world.ChunkPostPopulateEvent
- [ ] org.spongepowered.api.event.world.ChunkPreGenerateEvent
- [ ] org.spongepowered.api.event.world.ChunkPrePopulateEvent
- [ ] org.spongepowered.api.event.world.ChunkUnforcedEvent
- [ ] org.spongepowered.api.event.world.ChunkUnloadEvent
- [ ] org.spongepowered.api.event.world.GameRuleChangeEvent
- [ ] org.spongepowered.api.event.world.WorldCreateEvent
- [ ] org.spongepowered.api.event.world.WorldEvent
- [ ] org.spongepowered.api.event.world.WorldLoadEvent
- [ ] org.spongepowered.api.event.world.WorldUnloadEvent

**Comment by mastercoms** [comment]
So we use Bukkit imports unless we have to add Sponge stuff for plugin compatibility?

**Comment by deathcap** [comment]
Moved to https://github.com/deathcap/Bukkit2Sponge/issues/4 so Glowstone++ now is back to implementing Bukkit API, the SpongeAPI implementation is bridged to Bukkit with https://github.com/deathcap/Bukkit2Sponge which Glowstone++ integrates with
