### ISSUE TITLE
Players can't fly

### ISSUE THREAD

**Issue by euisuny** [GlowstoneMC/Glowstone#452]
I've set 
allow-flight: true
in glowstone.yml, but players can't fly in the Glowstone server.

**Comment by aramperes** [comment]
This is expected behavior. From the Minecraft wiki:

> 	Allows users to use flight on your server while in Survival mode, **if they have a mod that provides flight installed.**

This configuration entry will only allow modded clients to fly in survival mode (when turned off, players flying in survival will be kicked after 5 seconds). This does not affect vanilla clients.

If you want vanilla survival clients to fly, you will need to use plugins such as Essentials. (`/fly` command)

**Comment by euisuny** [comment]
I have the server on Creative mode, are users still not allowed to fly?

**Comment by mastercoms** [comment]
You don't need `allow-flight` for creative mode. How are your players trying to fly? Double tapping your jump button should work.

**Comment by euisuny** [comment]
Double tapping the jump button doesn't allow flight for all of my players. Some of my players could fly while others couldn't.

**Comment by mastercoms** [comment]
How did you obtain the world for your server? Was it generated by Glowstone, or imported from vanilla?

**Comment by euisuny** [comment]
It was generated by Glowstone.

**Comment by mastercoms** [comment]
Ok, could you import your world to Minecraft vanilla's server and see how people can fly there?

**Comment by mastercoms** [comment]
Just rename the `worlds` folder to `world` and move it to the Minecraft server folder.

**Comment by mastercoms** [comment]
Sorry, that's incorrect, copy the `world` folder inside the `worlds` folder to the Minecraft server folder.

**Comment by euisuny** [comment]
I reset all of my configurations and restarted the server and it fixed the problem. Thanks!

**Comment by mastercoms** [comment]
Glad you fixed the issue!
