### ISSUE TITLE
Entity#remove removes entity on server, but does not notify client

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#453]
When an `Entity`'s `.remove()` method is called, the entity is removed from the perspective of the server, but it persists on the client as a frozen entity.

Client attempts to attack log the message "tried to attack an entity that does not exist". Relogging clears the entity from the client. My guess is there is a packet missing from Glowstone to tell the client to delete the entity.

Glowstone build 444

**Comment by aramperes** [comment]
Does relogging make the entity disappear for the client?

**Comment by mastercoms** [comment]
From the original post:

> Relogging clears the entity from the client.

**Comment by aramperes** [comment]
Oh, whoops! 😁

**Comment by aramperes** [comment]
Can you test if this still happens with 6e38964?

**Comment by satoshinm** [comment]
Fixed with https://github.com/GlowstoneMC/Glowstone/commit/6e389649b9fc046e9f5ff18bf25afbc11471e429! (build 445 / version 2017.4.0.10) The entity is now deleted on the client. Thank you
