### ISSUE TITLE
EntityDeathEvent's getLastDamageCause() is null

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#456]
When an entity is killed, the `EntityDeathEvent` event fires, but `event.getLastDamageCause()` returns null (instead of the `EntityDamageEvent`), so you can't see the reason for an entity's death.

Glowstone 444

**Comment by mastercoms** [comment]
I'll look into this but I think it's just a matter of us not specifying the cause.

**Comment by aramperes** [comment]
Should be fixed by 120ce9a67c38e7eecf23ac6cb9f6cdd50a75fe63
