### ISSUE TITLE
List of found bugs in system. Suvival Based.

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#458]
Here is a short list of bugs I have found so far. Also technical suggestions based on YouTube Channels about oddities in Minecraft.

## Bugs
- [x] Hostile Mobs dont  move or attack
- [x] Endermen dont faze in and out from one spot to another. 
- [x] endermen dont appear in the end
- [x] Hostiles dont appear at all naturally.
- [x] Creepers dont explode
- [x] Fire does not work even with permissions on (This may be issues dependent on my settings)
- [x] The server throws you up into the air really high when loading from log in, death, or /spawn
- [x] When you get a head and place it the heads orientation is one direction.
- [x] Item frames will only place on the ground level block. If you try to place them above that, they slide down and stack up.
- [x] Dispensers dont put armor onto a player standing beside it. They throw the armor across the room.

## Suggestions
* A bucket of lava, when dropped as a ground item icon, should not burn. Its a contradiction.
* You should take damage when hitting stone, wood, or glass with an empty hand.
* A player in hardcore survival should not only get hungry but thirsty as well.

Again, I know you guys are very busy so I kept the suggestions list short. It also included dirt that gets wet should turn to gravel or sand and then obey gravity. 

Thanks for all you do!

---

*Edited by @gdude2002 for formatting*

**Comment by gdude2002** [comment]
Thanks for the contribution!

I've ticked off the stuff we already know about in your ticket. I'll create a set of tickets that encapsulate your other reported issues, so that we can keep track of them, and use this ticket as a story.

Please note that Glowstone aims to match the behaviour of vanilla Minecraft, and so the following suggestions don't really make sense.

> * You should take damage when hitting stone, wood, or glass with an empty hand.
> * A player in hardcore survival should not only get hungry but thirsty as well.

**Comment by mastercoms** [comment]
Child issues fixed.
