### ISSUE TITLE
CanaryMod API

### ISSUE THREAD

**Issue by Mstrodl** [GlowstoneMC/Glowstone#46]
I'm sorry if this is a stupid question but would it be possible to add support for the CanaryMod API? I'm not sure if there would be much purpose to it though but then again you're trying to add support for things right?

**Comment by mastercoms** [comment]
It's completely possible, though I'm going to say that we're going to wait until we have a mature way to support APIs.

**Comment by Mstrodl** [comment]
O.K. Cool! Also: How do you add labels?

**Comment by mastercoms** [comment]
Well _you_ can't, but collaborators, like me :smile:, can.

**Comment by Mstrodl** [comment]
*Oh...* OK. The world make so much sense to me now!

**Comment by mastercoms** [comment]
Glad I could enlighten you.

**Comment by Mstrodl** [comment]
:smile: Thanks!

**Comment by deathcap** [comment]
:+1: was also about to suggest this, Canary could be another good API to support. References:

http://canarymod.net
https://ci.visualillusionsent.net/job/CanaryLib/javadoc/
https://github.com/CanaryModTeam/CanaryLib

**Comment by mastercoms** [comment]
Thinking its better to discuss API problems in a mega thread, as they are very similar.
