### ISSUE TITLE
[#458] Server places you above the map when respawning

### ISSUE THREAD

**Issue by gdude2002** [GlowstoneMC/Glowstone#460]
This issue has been posted to separate the following ticket into smaller issues: #458

**Comment by Postremus** [comment]
Starting work on this

**Comment by Postremus** [comment]
Most likely cause for this is a strange PlayerPositionLookMessage send from the client.
Before killing myself, I was at x=71.0, y=68.0, z=80.0.
The spawn is also at x=71.0, y=68.0, z=80.0.  

`
2:32:43 [INFORMATION] Postremus issued command: /kill
22:32:50 [INFORMATION] received: PlayerPositionLookMessage(onGround=false, x=8.5, y=70.0, z=8.5, yaw=180.0, pitch=0.0)
`
This message basicly means, that the client is at x=8.5, y=70.0, z=8.5 after /kill.

After the respawn is completed however, the client is teleported to the correct spawn, but at y + 1.
`
22:32:50 [INFORMATION] send: PositionRotationMessage(x=71.0, y=69.0, z=80.0, rotation=0.0, pitch=0.0, flags=0, teleportID=0)
`
`
22:32:50 [INFORMATION] received: PlayerPositionLookMessage(onGround=false, x=71.0, y=69.0, z=80.0, yaw=0.0, pitch=0.0)  
`
`
22:32:50 [INFORMATION] received: PlayerPositionMessage(onGround=false, x=71.0, y=68.92159999847412, z=80.0)
`

Complete relevant log: https://gist.github.com/Postremus/c9c805d50ce64287c265aa0f34af2d28

**Comment by Postremus** [comment]
Did some more testing. 
Apperantly, we need to send the PositionRotationMessage before we send chunk data, when:
- the player joins
- the player respawns

otherwise, the client just sends garbage for hist first position update
