### ISSUE TITLE
[#458] Skull orientation is ignored on placement

### ISSUE THREAD

**Issue by gdude2002** [GlowstoneMC/Glowstone#461]
This issue has been posted to separate the following ticket into smaller issues: #458

**Comment by aramperes** [comment]
I cannot reproduce this locally. Skulls face the proper direction when I place them. Am I missing something @jasonstover9?

**Comment by ghost** [comment]
Because its notches head on a kit plugin I am assuming its a problem with the plugin and not glowstone.

**Comment by mastercoms** [comment]
Perhaps skulls with specific data are ignored for rotation?

**Comment by aramperes** [comment]
I have not been able to reproduce this at all, so I am closing it.
