### ISSUE TITLE
Make A god apple an Material.

### ISSUE THREAD

**Issue by Acyric** [GlowstoneMC/Glowstone#463]
So, I have only a suggestion, for us developers using glowstone I was curious if you guys would be able to make a God Apple (322:1) a material so we don't have to do constant round abouts or create methods to get them, that would be awesome!

Regards,
Jacop

**Comment by gdude2002** [comment]
That isn't really feasible, we have to support the Bukkit API correctly and that change doesn't really make any sense from a technical perspective.

Surely it isn't that hard to create an ItemStack of enchanted apples?

**Comment by MrPowerGamerBR** [comment]
```java
new ItemStack(Material.GOLDEN_APPLE, 1, (short) 1);
```

Come on, it isn't "that" hard...

Also, wouldn't that be a bit impossible? Since Materials are only mapped to IDs not IDs and item durability...
