### ISSUE TITLE
Chunk corruption

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#465]
![corrupted](https://cloud.githubusercontent.com/assets/27814186/25293955/0be83058-26ab-11e7-9108-053c331e47c4.png)

_jasonstover9 [commented](https://github.com/GlowstoneMC/Glowstone/issues/397#issuecomment-295876267) on Apr 20, 2017, 3:42 PM EDT_
> I lost an entire map because something went catastrophically wrong with any chunk that had been built on already. When we tried to reload the map there was a small island of chunks and nothing would load. Ill have the same problem with the random wild teleport plugin, Ill go far away and end up underground due to no chunks loading fast enough to catch my free fall.

**Comment by gdude2002** [comment]
Do we actually know what's causing this one? Do we need @jasonstover9 to upload their world files?

**Comment by aramperes** [comment]
Closing this as the original reporter deleted their account, and we've never been able to reproduce this.
