### ISSUE TITLE
GlowstonePE , new project?

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#468]
Hi.

Can you start one project GlowstonePE for MCPE? 👍

**Comment by gdude2002** [comment]
To my knowledge, we're not currently planning on supporting MCPE.

Why not keep an eye on ProtocolSupport instead?

**Comment by ghost** [comment]
@gdude2002 Because not work dude

**Comment by gdude2002** [comment]
Well, yeah, MCPE support isn't complete for it yet. It'll happen in time. That project only has one developer, after all.

**Comment by ghost** [comment]
@gdude2002 Dude, is abandonated. 23 days and no commit :(

**Comment by gdude2002** [comment]
It's not abandoned. There is a stall because of a required upcoming change in MCPE so that the inventory system will work in a sane way.

Either way, this is not the ProtocolSupport issue tracker, those complaints are best leveraged there.

**Comment by mastercoms** [comment]
How can we maintain yet another project when we are already having a hard time developing Glowstone?

**Comment by aramperes** [comment]
https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#support-for-minecraft-pocket-edition
