### ISSUE TITLE
SpongeAPI implementation in Glowstone++ vs Bukkit2Sponge?

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#47]
Both https://github.com/deathcap/GlowstonePlusPlus (in net.glowstone.shiny based on https://github.com/GlowstoneMC/ShinySponge) and https://github.com/deathcap/Bukkit2Sponge (based on Glowstone++) implement SpongeAPI, what to do about this duplication?

The downside of this duplication is of course extra work in maintaining two separate copies (https://github.com/deathcap/GlowstonePlusPlus/issues/45), but it may also be causing conflicts: https://github.com/deathcap/Bukkit2Sponge/issues/1

I'm thinking about removing the SpongeAPI in Glowstone++ in favor of Bukkit2Sponge, but a benefit of having it in Glowstone++ is that it's an all-in-one package, easier for server admins instead of having to download a separate plugin to load SpongeAPI plugins, plus the auto-detection of Bukkit/Sponge plugin types (Glowstone++ recognizes both types in the usual `plugins/` directory, Bukkit2Sponge currently only loads from its own `plugins/Bukkit2Sponge/plugins/` folder). 

Maybe keep the plugin type detection in Glowstone++ (and enhance for other plugin types, e.g. https://github.com/deathcap/GlowstonePlusPlus/issues/46), but defer to Bukkit2Sponge for loading the SpongeAPI plugins (possibly even embedding Bukkit2Sponge within Glowstone++? git subproject etc.)

There's also the possibility to consider as the projects advance that implementing SpongeAPI on top of the Bukkit API becomes less practical, than implementing it directly in the server implementation (to be determined).

**Comment by mastercoms** [comment]
Yeah I think it would be easier to maintain and make Glowstone++ lighter if we used bukkit2sponge.

**Comment by TekkitCommando** [comment]
So is the plan to add the api support to GlowstonePlusPlus and wait for people at glowstone to code the vanilla features xD? I know this is an experimental project but this could become a very popular one, I think after you get Bukkit2Sponge functioning to work on making Glowstone++ able to support a survival experience :)

**Comment by TekkitCommando** [comment]
Just a suggestion I know it's @deathcap's project and he might have a different plan of action then I would

**Comment by mastercoms** [comment]
Glowstone++'s initial goal was to add compatibility to plugins, since the main branch is refusing to support Spigot's continuation of Bukkit, which is what most plugins use. We then decided to add additional compatibility for Sponge. The features added was of course a side goal, but I think we will be adding more features as Glowstone++ seems more and more like the project that will finish what Glowstone started.

**Comment by TekkitCommando** [comment]
I agree :+1: I feel glowstone++ will be a very amazing project

**Comment by TekkitCommando** [comment]
and i want to contribute to and support glowstone++ in anyway possible :smile: I plan to try to start trying to make pull requests for Glowstone++ at some point but I am kind of busy with my hosting company but just tell me whenever you guys need servers and sponsorship from a server hosting company and i will be there :+1:
