### ISSUE TITLE
Armor Stands aren't functional

### ISSUE THREAD

**Issue by Christian7573** [GlowstoneMC/Glowstone#471]
Armor stands just don't work.

As I was programming in #470, I was having extreme trouble getting armor stands to work. A thought occurred to me that perhaps armor stands were broken in general. I placed one down, grabbed a diamond helmet and a diamond chestplate, and tried to equip them to the armor stand. It didn't equip nor take it out of my inventory.

Problems:
Equipping armor stands in game does not work.
Equipping armor using `Entity.getEquipment().setHelmet()` and similar methods do not work
Equipping armor using `ArmorStand.setHelmet()` do not work.

Tested in build 478 (2017.5.0.0)

**Comment by mastercoms** [comment]
Last time I checked, this worked, so there was a regression somewhere. Perhaps the inventory updates for armor and contents to be better in line with the Bukkit spec broke compatibility with armor stands.

**Comment by Postremus** [comment]
I will work on this
