### ISSUE TITLE
Burning furnace block not updated

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#474]
When you smelt something in a furnace, the GUI shows the smelting progress but the block does not update from Material.FURNACE to Material.BURNING_FURNACE.

Relogging does not update the furnace state either, so it is probably not (only) a missing update packet, but I'd suspect the block is not being replaced in the world at all. It should change to BURNING_FURNACE when smelting, then back to FURNACE after completing, and notify the client.

Glowstone build: 495

<img width="966" alt="screen shot 2017-05-19 at 9 31 22 pm" src="https://cloud.githubusercontent.com/assets/26856618/26273010/83b17f9a-3cdb-11e7-9f9d-fdf6a89f0e3f.png">
<img width="966" alt="screen shot 2017-05-19 at 9 31 24 pm" src="https://cloud.githubusercontent.com/assets/26856618/26273009/83a94488-3cdb-11e7-955b-7b14c8b5271c.png">

**Comment by mastercoms** [comment]
Should be an easy fix, but I'm going to refrain from fixing this until 1.12 is finished and mergable.
