### ISSUE TITLE
Config file config/glowstone.yml isn't valid: metrics-uuid-do-not-touch: !!java.util.UUID 'a2dc6f12-2439- ...

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#495]
Start Glowstone build 544, stop it, then rerun it again, it will invariably report an invalid configuration file:

```
+ /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java -Xms1G -Xmx1G -XX:+UseG1GC -XX:MaxGCPauseMillis=30 -jar glowstone.jar
21:40:52 [INFO] This server is running Glowstone version 2017.6.1-SNAPSHOT.b01b8fe-MC1.12 (Implementing API version 1.12-R0.1-SNAPSHOT)
21:40:52 [SEVERE] Config file config/glowstone.yml isn't valid! could not determine a constructor for the tag tag:yaml.org,2002:java.util.UUID
 in 'string', line 67, column 32:
        metrics-uuid-do-not-touch: !!java.util.UUID 'a2dc6f12-2439- ... 
                                   ^

21:40:52 [INFO] Recipes: 300 shaped, 63 shapeless, 26 furnace, 10 dynamic, 28 fuels.
```

If I delete config/glowstone.yml, then the program is fixed for the next time Glowstone runs, but when it is stopped and started again, the problem reoccurs again.

**Comment by mastercoms** [comment]
A faulty merge caused this regression. https://github.com/GlowstoneMC/Glowstone/commit/75cbccb8406aca6022936664374080b67037fc81#diff-5c884f616dd119177358e8e95a713dcc

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/e23f1c963b19347eb9680872bfc5d85a1ab924b2
