### ISSUE TITLE
Setting signs with API creates invalid block data

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#496]
Glowstone 544. When a plugin sets a sign, then reads it back, it may return invalid data: specifically, setting a block to the `WALL_SIGN` material causes `getItemType()` to instead see `SIGN_POST`, so org.bukkit.block.material.Sign getFacing() will return the wrong data, likely leading to a crash in a plugin:

```java
    public BlockFace getFacing() {
        byte data = getData();

        if (!isWallSign()) { // incorrectly returns false, since getItemType() is SIGN_POST not WALL_SIGN
            switch (data) {
...
            case 0xC: // expect to hit this switch case, data=0xC but it doesn't because !isWallSign()
                return BlockFace.EAST;

        } else { // enters this clause instead, but with wrong data
            BlockFace attachedFace = getAttachedFace();
            // This used to NPE here, but now returns null instead (added in https://github.com/GlowstoneMC/Glowkit/pull/12)
            if (attachedFace != null) {
                return attachedFace.getOppositeFace();
            }

            return null;
        }
    }
```

https://github.com/GlowstoneMC/Glowkit/pull/12 fixed the internal NPE, which is good, but there is still this bug where getFacing() will return null after a sign is programmatically created. Have not deeply looked into why this occurring but for comparison it works as expected on Spigot.

Test plugin: https://github.com/satoshinm/SignTestPlugin/releases/tag/v0.1

Usage: look at a block and type /signtest, this will try to create a sign at the block

* Glowstone: blockFace = null (used to NPE [before](https://github.com/GlowstoneMC/Glowkit/pull/12)) and no sign appears
* Spigot: blockFace = NORTH and the sign appears instantly

This only applies to signs created by plugins, signs placed by the player from the client have the correct data.

**Comment by aramperes** [comment]
@satoshinm I have implemented a fix for this in https://github.com/GlowstoneMC/Glowstone/commit/85f3e55ce16d26d3651c41d7845cc49a8d54b1fe, could you confirm if this matches the expected behavior?

e: Looks like this commit caused a regression when placing signs manually, I'm working on that now.
e2: reverted for now, I'll have to look more into this

**Comment by jhg023** [comment]
@satoshinm Your test plugin does not seem to work correctly on Spigot; the sign automatically drops 20 seconds after using the command.  Using `new Sign(Material.WALL_SIGN)` in your test plugin fixes the issue on both Spigot and Glowstone.

**Comment by Pr0methean** [comment]
Closing per https://github.com/GlowstoneMC/Glowstone/issues/496#issuecomment-359223281
