### ISSUE TITLE
Investigate supporting Spigot API additions (Bukkit-Patches)

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#5]
Glowstone++ integrates the updates to the [Bukkit API](https://github.com/Bukkit/Bukkit) from the Spigot team (i.e., from https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/README.md) but they also have an additional set of patches on top of the Bukkit API:

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/Bukkit-Patches

might be worth also supporting some of these APIs, although by their nature they are more experimental, and not all are necessarily applicable. 
- [ ] 0001-POM-Changes.patch
- [ ] 0002-Spigot-Timings.patch
- [ ] 0003-Add-PlayerItemDamageEvent.patch
- [ ] 0004-BungeeCord-Support.patch
- [ ] 0005-Add-Arrow-API.patch
- [x] 0006-Add-Particle-API.patch
- [ ] 0007-Define-EntitySpawnEvent-and-SpawnerSpawnEvent.patch
- [ ] 0008-Entity-Mount-and-Dismount-Events.patch
- [ ] 0009-InventoryClickEvent-getClickedInventory.patch
- [ ] 0010-Added-getAllSessionData-to-the-Conversation-API.patch
- [ ] 0011-Catch-Conversation-API-Errors.patch
- [ ] 0012-Player-Collision-API.patch
- [ ] 0013-Expand-Boolean-Prompt-Values.patch
- [ ] 0014-Add-Getter-for-Entity-Invulnerability.patch
- [ ] 0015-Add-respawn-API.patch
- [ ] 0016-Fix-Plugin-Message-API-Disconnects.patch
- [ ] 0017-Fix-Tab-Completion-for-Some-Commands.patch
- [ ] 0018-Implement-Locale-Getter-for-Players.patch
- [ ] 0019-Add-support-for-fetching-hidden-players.patch
- [ ] 0020-Silenceable-Lightning-API.patch
- [ ] 0021-Remove-deprecation-on-some-player-lookup-methods.patch
- [ ] 0022-Expand-team-API-to-allow-arbitrary-strings.patch
- [ ] 0023-Add-Score.isScoreSet-Z-API.patch
- [ ] 0024-Add-PlayerSpawnLocationEvent.patch
- [ ] 0025-Ease-ClassLoader-Deadlocks-Where-Possible.patch
- [ ] 0026-Fix-slow-tab-complete-for-some-commands.patch
- [ ] 0027-Undeprecate-Player-updateInventory-V.patch
- [x] 0028-Added-isUnbreakable-and-setUnbreakable-to-ItemMeta.patch
- [ ] 0029-BungeeCord-Chat-API.patch
##

**Comment by mastercoms** [comment]
I also agree to use the Spigot API. It allows us to both support even more plugins and add more features, while still retaining backwards compatibility.

I was also thinking about including the PaperSpigot API.

**Comment by deathcap** [comment]
Sounds good. Somewhat awkward how some of the Spigot API additions are added, onto a new `.spigot()` method returning an inner class part of the API extended by the implementation (wonder if Spigot will promote any of these APIs into their "Bukkit API" proper), but I suppose its not much different writing `.spigot()` than `org.bukkit.`, and I agree its worth it for Spigot plugin compatibility.

Looked into adding 0006-Add-Particle-API.patch, to replace Glowkit's existing API. Some progress but there are complications: https://github.com/deathcap/GlowstonePlusPlus/pull/7

**Comment by mastercoms** [comment]
I don't think Spigot will ever add these to the Bukkit API, as a lot of people just want to use vanilla Bukkit/CraftBukkit and not Spigot, with it just updated to the latest version.

Adding Spigot API events and changes to events sounds nice.

**Comment by mastercoms** [comment]
I believe this is done.
