### ISSUE TITLE
[#396] Entities: Implementation [$50 awarded]

### ISSUE THREAD

**Issue by gdude2002** [GlowstoneMC/Glowstone#504]
[![Bountysource bounty](https://api.bountysource.com/badge/issue?issue_id=46548049)](https://www.bountysource.com/issues/46548049-396-entities-implementation)

This issue is part of [this story](https://github.com/GlowstoneMC/Glowstone/issues/396), *Completing entities in Glowstone* (#396). To make the work easier and bounties fairer, we've split it into multiple issues.

Anyone can participate in the completion of this issue, which will be a major turning point in the development and the possible use-cases for Glowstone as a Minecraft server alternative.

---

**Before getting started!** If you are unfamiliar with Glowstone, please remember that Glowstone is a complete rewrite of the Minecraft vanilla server, aimed to be a better alternative to other software like Spigot. You are by no means allowed to push code to this repository based on Mojang's own platform (whether it be Forge, MCP, decompiled binaries, etc.) Doing so will cause in the rejection of your Pull Request. You are allowed to use other resources like the numerous wikis that exist on the Internet (Minecraft Wiki, wiki.vg, etc.) as well as trial-and-error.

---

Entities to be implemented
==================

Some entities are simply not implemented in Glowstone. Implementing an entity is a task split in multiple aspects, such as Metadata (networking), Storage (I/O), basic interactions, API implementation, etc.

These entities include:

* ~Armor Stand (need to be fixed, see #471)~ (done in #520)
* ~Boat (including steering and the networking behind it)~ (done in #529)
* ~Ender Crystal~ (done in #530)
* ~Experience Orb (and dropping them when killing entities, based on the loot tables that have been implemented in the past)~ (done in a7de3bda58b37dbee29e5e96d4e51e6da9f27017)
* ~Firework~ (done in #542)
* ~Leash (and leashing entities, preferably)~ (done in #538)
* ~Lightning~ (done in #546)
* ~Paintings~ (done in #535)
* Horses (mostly implemented, ~but the passenger system in completely broken and needs to be fixed~ (done in #524))

**Comment by gdude2002** [comment]
As @Postremus has done almost all of this ticket himself and the $20 bounty on it was placed by him originally, I've decided to double it. 

Since it looks like you're gonna get the bounty when this ticket is closed, Postremus, grats and thanks for contributing!

**Comment by aramperes** [comment]
Since all the tasks have been completed, the issue can be closed. The bounty will be awarded shortly to @Postremus.

*e: [bounty awarded](https://www.bountysource.com/issues/46548049-396-entities-implementation)*
