### ISSUE TITLE
Tool should affect block mining speed

### ISSUE THREAD

**Issue by satoshinm** [GlowstoneMC/Glowstone#506]
Implement http://minecraft.gamepedia.com/Breaking#Speed, to summarize:

* Tool types: 1.5x slower if can tool can mine the block, 5x slower if cannot
* Tool materials: 2x, 4x, 6x, 8x, or 12x faster for wood, stone, iron, diamond, gold tool materials
* Special cases: shears 15x (5x on wool) and sword 1.5x (15x on cobwebs)

https://github.com/GlowstoneMC/Glowstone/pull/473 added basic block hardness, but the tool type and material also needs to be taken into account. I started working on this in https://github.com/GlowstoneMC/Glowstone/pull/491 but ran out of time to finish it and test it so I am opening this issue instead for someone else to if anyone is interested.

To test, sign in with two accounts, have one player start digging a block and the other watching it. Use a hard block such as stone or obsidian, and try mining with each tool type and material (not only bare hands).

If implemented correctly, the block break animation in both windows should show identical breakage stages for all tools and materials.

**Comment by gdude2002** [comment]
> ran out of time to finish it and test it

You weren't that far behind, were you? Or did you mean personal time?

**Comment by satoshinm** [comment]
Ya, I just didn't have the time to put on the finishing touches, although it was very close. Could be a good start for someone to work on for a complete fix (including shears/swords and wool/cobwebs).
