### ISSUE TITLE
Explosions destroy to much blocks

### ISSUE THREAD

**Issue by Postremus** [GlowstoneMC/Glowstone#507]
Hello,

I tested around with tnt a bit. The destroyed blocks do not seem to match vanilla.

Steps to reproduce:
1) Create a 7x7 endstone platform
2) place a tnt in the middle
3) ignite it

In vanilla, only a 3x3 hole is created. In glowstone, the complete platform is destroyed.

![grafik](https://user-images.githubusercontent.com/1223135/27587738-c70df52e-5b45-11e7-8f36-6292aae02c0d.png)
(from vanilla)

server version:
`
This server is running Glowstone version 2017.6.1-SNAPSHOT.0826543-MC1.12 (Implementing API version 1.12-R0.1-SNAPSHOT)
`

java version:
`
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
`

I do not have any plugins installed.

best regards
Postremus

**Comment by mastercoms** [comment]
Blast resistance is not defined for end stone in https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/resources/builtin/materialValues.yml.

Could you try with cobblestone? If it is matched there, then it is just a matter of the blast resistance value not being defined, rather than an error in the actual calculations.

**Comment by Postremus** [comment]
Glowstone:
![grafik](https://user-images.githubusercontent.com/1223135/27593265-ffb655ae-5b56-11e7-9793-feabd11b7ce5.png)

Vanilla:
![grafik](https://user-images.githubusercontent.com/1223135/27593308-1eef6410-5b57-11e7-81ae-228dc73a7f96.png)

**Comment by gdude2002** [comment]
![](http://pix.toile-libre.org/upload/original/1498642821.png)
