### ISSUE TITLE
ExplosionMessage is only sent to players that get damaged

### ISSUE THREAD

**Issue by Postremus** [GlowstoneMC/Glowstone#508]
Hi,

Did some more testing. The explosion particles are not visible when you are not in the range of the explosion.
How to reproduce:
1) Place a tnt block
2) ignite it
3) Go a few block (20 or so) away

In vanilla, the explosion is visible from far away.

In glowstone, the explosion is not visible.
However, when you get damaged by the explosion, you will see the particles.

Version:
`
This server is running Glowstone version 2017.6.1-SNAPSHOT.0826543-MC1.12 (Implementing API version 1.12-R0.1-SNAPSHOT)
`

best regards
Postremus

**Comment by mastercoms** [comment]
Explosion play out and damage routines should be separated. https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/Explosion.java#L234
