### ISSUE TITLE
TrueCraft

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#51]
TrueCraft is a complete open source implementation of 1.7.3 beta.
http://truecraft.io/

It could help us in determining how to implement certain Minecraft features properly, such as fluids.

**Comment by TekkitCommando** [comment]
Awesome :D

**Comment by TekkitCommando** [comment]
I updated the github organizations picture with some glowstone xD

**Comment by deathcap** [comment]
Hacker News has some good discussion on TrueCraft: https://news.ycombinator.com/item?id=9469175

For the logo, best to use a custom asset (not based on or from Mojang's texture pack)

**Comment by mastercoms** [comment]
I'm working on a logo.

**Comment by mastercoms** [comment]
I changed the logo to the ProgrammerArt texture for glowstone for now, to avoid using Mojang's copyrighted textures.

**Comment by mastercoms** [comment]
Closing this as discussion has ceased, and nothing useful can be discussed further.
