### ISSUE TITLE
Can't kill myself in gamemode 1

### ISSUE THREAD

**Issue by Postremus** [GlowstoneMC/Glowstone#512]
Hey,

I can't kil myself when I am in gamemode 1.

Steps to reproduction:
1) /gamemode 1
2) /kill

In vanilla, I get killed.
In GlowStone, I get the chat message "Killed Postremus", but I'am still alive

Server version:
`
This server is running Glowstone version 2017.6.1-SNAPSHOT.a146dea-MC1.12 (Implementing API version 1.12-R0.1-SNAPSHOT)
`

regards
Postremus

**Comment by mastercoms** [comment]
Kill does damage, but players can't take damage in creative mode unless the damage cause is void. The canTakeDamage method in GlowHumanEntity should be updated to allow for suicide damage as well.
