### ISSUE TITLE
Investigate and Implement "Polyglot Maven"

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#514]
It has been suggested that we could use the [Polyglot Maven](https://github.com/takari/polyglot-maven) extension to replace our XML pom file.

This extension adds support for different dialects (Ruby, Groovy, etc.), and some of them allow the use of inline scripts/plugins when building.

**Comment by mastercoms** [comment]
Would this remove the need to switch to Gradle?

Also I think we should use the Ruby or Scala languages, since they have the most features.

**Comment by sgdc3** [comment]
> Would this remove the need to switch to Gradle?

What's the problem with maven?

**Comment by sgdc3** [comment]
Polyglot would break some integration with ci services and etc... XML is fine, what's the problem with it?

**Comment by mastercoms** [comment]
Nothing, I prefer Maven, too. But a few people have been talking about Gradle for a while now.

Well the inline scripts feature is very useful. Also XML is redundant/verbose for many cases, less readable and sometimes cumbersome. I'm not sure how it would break anything, though. Isn't Polyglot handled through Maven?

**Comment by sgdc3** [comment]
It depends, services like versioneye relies on directly parsable pom. Now idk the services you're using.

**Comment by sgdc3** [comment]
Maven is complex but it is still more powerful, glowstone has a simple lifecycle, but a project with many modules with strange lifecycles would be very difficult to manage with gradle.

**Comment by mastercoms** [comment]
pom.xml is deployed for Ruby and Scala polyglot. I'm not exactly sure how VersionEye works but if it access repositories to check for version info, then it would work. However, I don't believe we use VersionEye. We use CircleCI to build.

About Gradle, I agree that Maven is the superior choice, but still there are people who prefer Gradle. I feel like a lot of sentiments from the Gradle crowd would be answered with Polyglot Maven.

**Comment by smartboyathome** [comment]
Is this still something we want to look into? I don't see much of an advantage of this over Maven itself, other than requiring more specialized knowledge since one now needs to know both the implementing language and Maven itself. XML may be verbose, but what we're doing right now is pretty standardized.

**Comment by mastercoms** [comment]
I don't think we should dismiss the advantages of using a new markup.

Also, we can use inline scripting.

**Comment by mastercoms** [comment]
We are using Gradle now, see #1117.
