### ISSUE TITLE
IRC for Glowstone++

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#52]
I made an IRC channel for Glowstone++ on EsperNet to test it out. We can use this or Gitter.im its up to you guys but until we decide we can temporarily use EsperNet :smile: 

Link: https://webchat.esper.net/?channels=Glowstone++

**Comment by TekkitCommando** [comment]
I will give you guys ( @deathcap  and @mastercoms ) Operator when you guys join the irc :smiley:
