### ISSUE TITLE
Multiple passengers need to be implemented

### ISSUE THREAD

**Issue by Postremus** [GlowstoneMC/Glowstone#522]
Currently, Glowstone only supports one passenger. Since 15w41a, multiple are possible through the `Passengers` tag in vanilla.  
This tag needs to be implemented correctly, and the api implementation has to be adjusted.

See:
http://minecraft.gamepedia.com/15w41a
http://wiki.vg/Protocol#Set_Passengers
https://beta.glowstone.net/jd/glowkit/org/bukkit/entity/Entity.html#getPassengers--
https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/entity/GlowEntity.java#L1113

**Comment by Postremus** [comment]
Will work on this.

**Comment by mastercoms** [comment]
I think I remember working on this before, not sure what happened to the branch.
