### ISSUE TITLE
Crafting inventories don't support shift-clicking

### ISSUE THREAD

**Issue by puigru** [GlowstoneMC/Glowstone#525]
Hello,

While testing Glowstone on the test server, I noticed that if you attempt to retrieve an item from the result slot in a crafting inventory by shift-clicking, the item will disappear server-side.

Glowstone build: 983

**Comment by aramperes** [comment]
Are there any relevant error logs for this?

**Comment by puigru** [comment]
@momothereal I just tested the latest artifact (985) locally, as my tests were done on mc.glowstone.net, and there were no errors shown in the console.

**Comment by aramperes** [comment]
Fixed in 0ca671017009c8822a99bb88b6feb3fe53b85341
