### ISSUE TITLE
Glowstone++ Official Servers

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#53]
I can start working on the official Glowstone++ servers with my hosting company, and I will just post when they are ready, I can then send owner login info to @deathcap and another login to @mastercoms (deathcap can choose what level of access he wants mastercoms to have to the servers). I will post progress on the servers as well. Deathcap and Mastercoms can comment features they would like to have for the servers and i will see how much I can do :) (I can probably do all of the suggestions)

**Comment by TekkitCommando** [comment]
I am gonna take ideas from #39 :D

**Comment by mastercoms** [comment]
Discussion can be resumed on forums, once they are up.
