### ISSUE TITLE
Add checksum to library manager

### ISSUE THREAD

**Issue by yangm97** [GlowstoneMC/Glowstone#543]
Glowstone build: bf69637286e428c15955887c8683d661696f3050

Sometimes, library files might get corrupt (either because of an unfinished download, bit rot, god hating you, etc). Currently the library manager doesn’t check the validity of these files, which can lead to unexpected behaviour. I suggest adding checksum verification to these files, but there could be cheaper ways of achieving the same results (like checking the file size). Or a combination of both: checksum after downloading, checking size on server startup, maybe adding a runtime flag to force checksum on startup for the paranoids around (o/).

**Comment by aramperes** [comment]
On a technical perspective, it is possible to obtain the original SHA1 and MD5 hashes of a JAR directly from the repository (for example, https://repo.glowstone.net/service/local/repositories/central/content/org/apache/logging/log4j/log4j-core/2.8.2/log4j-core-2.8.2.jar.sha1)

**Comment by mastercoms** [comment]
But that requires downloading a file :)

**Comment by aramperes** [comment]
I guess we're going to have to hard-code the checksum too then.

**Comment by Foorack** [comment]
I don't think it is necessary to hard-code the checksum. It is extremely unlikely for the SHA1 to match if either of the files is corrupted.

**Comment by aramperes** [comment]
@Foorack Yes, but when it comes to file verification against threats like man-in-the-middle attacks, having the SHA downloaded from the internet defeats the purpose

**Comment by Foorack** [comment]
@momothereal I was more thinking of file corruption. If you are worrying about MITM attack then it should rather enforce HTTPS at download.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/825e5113f902fb5a3ebf1c6fbad3a32ad1f18411.
