### ISSUE TITLE
Regional difficulty needs to be implemented

### ISSUE THREAD

**Issue by Postremus** [GlowstoneMC/Glowstone#545]
Currently, Glowstone has no concept of regional difficulty. RD and Clamped RD affects how some entities should behave.
There does not seem to be any api which needs to be implemented for this.

See:
https://minecraft.gamepedia.com/Difficulty#Regional_difficulty
https://minecraft.gamepedia.com/Difficulty#Other_effects

**Comment by mastercoms** [comment]
Fixed in #1019.
