### ISSUE TITLE
/tp player toplayer does not work

### ISSUE THREAD

**Issue by Postremus** [GlowstoneMC/Glowstone#550]
Hello,

I tried to teleport myself to an test account of mine using `/tp Postremus otheraccount`.
This did not work.
As output in the chat I got `Teleported Postremus to Postremus`, and was, presumably, teleported to myself.

Expected behavior is that I can teleport to another account using this syntax.

regards,
Postremus

**Comment by Foorack** [comment]
@Postremus I find it weird that you were able to teleport a player to a player, as that does not seem to be implemented in the code. :thinking:

**Comment by Postremus** [comment]
Ah, most likely the other account just got ignored, and something which resembles `/tp Postremus` got executed.

**Comment by notourist** [comment]
Why are there two distinct teleport commands (/tp and /teleport)? Shouldn't they be the same?

**Comment by mastercoms** [comment]
https://minecraft.gamepedia.com/Commands#teleport

https://minecraft.gamepedia.com/Commands#tp

**Comment by aramperes** [comment]
Fixed in #554
