### ISSUE TITLE
Can't add Enchantment to ItemStack

### ISSUE THREAD

**Issue by notourist** [GlowstoneMC/Glowstone#559]
I'm currently trying to implement the enchant command.

Theoretically my [code](https://github.com/schweinefilet/Glowstone/blob/36420b6b77fb324db202e88d128a051b1abcdc8d/src/main/java/net/glowstone/command/minecraft/EnchantCommand.java#L78) *should* work but it doesn't. No errors or warnings are thrown but I can't seem to add an enchantment to the currently hold ItemStack. I checked the [GlowAnvilInventory](https://github.com/GlowstoneMC/Glowstone/tree/master/src/main/java/net/glowstone/inventory/GlowAnvilInventory.java#L105) but I'm not able to spot the difference. Any help is appreciated.

**Comment by mastercoms** [comment]
Hm, that is strange. I'll test your branch soon and see what's going on.

**Comment by mastercoms** [comment]
Wasn't able to test your branch yet due to time constraints, but try removing your filter statements to see if there's a bad filter. Then, try writing the logic to not use streams or lambdas. That's all I can really tell from just reading your code, sorry.

**Comment by notourist** [comment]
I just checked it again - and immediately found the problem:
 https://github.com/GlowstoneMC/Glowstone/blob/2f45cfcaeb1cbefd0b508be4ddc8acb557fa3184/src/main/java/net/glowstone/inventory/GlowPlayerInventory.java#L326

The Stack just gets cloned >.>
