### ISSUE TITLE
Server Connection Timeout: OutOfMemory Error

### ISSUE THREAD

**Issue by euisuny** [GlowstoneMC/Glowstone#565]
<img width="917" alt="screen shot 2017-09-05 at 11 33 08 am" src="https://user-images.githubusercontent.com/14916264/30324917-b793d0aa-9790-11e7-90d6-a09a6fc8a159.png">

I have been running a Glowstone server for about 2 weeks, and there hasn't been much use of the server during the time period.

However, when I tried to connect to the server, it gave me a time out error on the client side, and the above error message on the server log.

After I rebooted the server, it worked fine and I couldn't reproduce this error again.

Why might this be happening/what would be a fix for this issue? I want to be able to have the server running consistently for a long period of time.

**Comment by gdude2002** [comment]
Out of memory error. Seems like there's either a memory leak, or you had enough activity to blow past all the RAM you had assigned to the process.

Depending on how much RAM your machine has, you can change how much is assigned using the `-Xms` and `-Xmx` command-line switches.

For example, the recommended way to run Glowstone is as follows:

```
java -Xms1G -Xmx1G -XX:+UseG1GC -jar glowstone.jar
```

This allocates 1GB of RAM for the process. If you have enough RAM to spare, you could double this to 2GB.

```
java -Xms2G -Xmx2G -XX:+UseG1GC -jar glowstone.jar
```

**Comment by euisuny** [comment]
I will try that. Thank you!
