### ISSUE TITLE
Fishing isn't implemented

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#567]
Fishing is not currently implemented.

Required components:

 - [x] Fishing Hook entity & Fishing Rod implementation
 - [x] Fishing loot
 - [x] Fishing enchantments

**Comment by Cadiducho** [comment]
I was doing research about this, and implementing some stuff... but I think we should wait to get #614 merged, right? Or start working from this branch

**Comment by aramperes** [comment]
@Cadiducho Glad to see you're interested! Feel free to start working on stuff and submit a PR. I don't think the Projectiles PR is blocking development for fishing mechanics (does it?).

There is also a [branch](https://github.com/GlowstoneMC/Glowstone/tree/%23504-fishing) with some work done on this, so you can start off from there if you wish.

**Comment by Pr0methean** [comment]
I don't think the Projectiles PR is blocking either, although it wouldn't hurt to merge it this weekend.

**Comment by Cadiducho** [comment]
No, is not blocking, however @Pr0methean wrote some intersting methods (such as collide[s] ) that should be very useful for the fishing hook

**Comment by clabe45** [comment]
Hi, I'd like to help on this issue. Can I implement fishing rod enchantment mechanics?

**Comment by mastercoms** [comment]
@clabe45 Yes you may.

**Comment by clabe45** [comment]
Lure and Luck of the Sea are the only enchantments exclusive to fishing, right? Also, do I need to implement common ones such as Mending and Unbreaking?

**Comment by clabe45** [comment]
Nevermind, it's already implemented D:

**Comment by mastercoms** [comment]
@aramperes Do you know what's left over from #829?

**Comment by aramperes** [comment]
I don't; would need to be re-tested and perhaps split into more specific issues.

**Comment by mastercoms** [comment]
I will close this issue then, since it seems like the tasks listed out in this issue have been finished.
