### ISSUE TITLE
Java 9 support for downloaded libraries

### ISSUE THREAD

**Issue by TuxCoding** [GlowstoneMC/Glowstone#576]
Title: Java 9 support for downloaded libraries
Glowstone build: 4534b4a5

Java 9 changed the system class loader and therefore we can no longer call addURL to dynamically load the library files. [Paperclip](https://github.com/PaperMC/Paperclip) had the same issue and they solved it [by using a Java agent](https://github.com/PaperMC/Paperclip/blob/d0395f6304db49e4472dab9dbf247e994a1122b8/java9/src/main/java/com/destroystokyo/paperclip/Agent.java#L17).

```
[WARNING] java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
[WARNING] 	at net.glowstone.util.LibraryManager$LibraryDownloader.run(LibraryManager.java:101)
[WARNING] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[WARNING] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[WARNING] 	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by gdude2002** [comment]
Thanks for creating the ticket - we do actually know about this one. @mastercoms has some plans for it, I think.

**Comment by Pr0methean** [comment]
A temporary solution may be to use `ClassLoaders.AppClassLoader.appendToClassPathForInstrumentation`, although this will probably raise an illegal-reflection warning and be specific to Oracle and OpenJDK.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/536305cb88faad3d1b36c34b1b9ae145cc6c14e2.
