### ISSUE TITLE
List easily accessible builds of Glowstone on website

### ISSUE THREAD

**Issue by masrourmouad** [GlowstoneMC/Glowstone#580]
Can you please setup a Jenkins server, it will make troubleshooting  Glowstone easy and make it move accessible to users; thanks ;)

**Comment by mastercoms** [comment]
https://glowstone.net/#builds

It's a planned feature for our website, but I don't think we will use Jenkins, and rather just use CircleCI's API to list builds.

**Comment by mastercoms** [comment]
Closing as it is a duplicate of https://github.com/GlowstoneMC/Site/issues/1
