### ISSUE TITLE
Apply for Intellij IDEA Open Source License

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#59]
@deathcap, could you sign us up for a free Intellij IDEA Ultimate Open Source license?

https://www.jetbrains.com/shop/eform/opensource?product=II

**Comment by TekkitCommando** [comment]
Cool

**Comment by TekkitCommando** [comment]
@mastercoms are you American?

**Comment by mastercoms** [comment]
Uhh, yeah.

**Comment by TekkitCommando** [comment]
Ok i know that was a little weird but i was jw :P

**Comment by mastercoms** [comment]
Ok. No need to be embarrassed by curiosity.

**Comment by deathcap** [comment]
@mastercoms feel free to apply yourself on behalf of Glowstone++ if you'd like (I already have a personal license). While at it may also want to consider applying for an open source license to https://www.yourkit.com/purchase/ (if/when Glowstone++ meets the requirements of "an established and active community")

**Comment by mastercoms** [comment]
I signed up for the license.
