### ISSUE TITLE
PlayerInteractEvent is never fired with Action.RIGHT_CLICK_AIR

### ISSUE THREAD

**Issue by kaenganxt** [GlowstoneMC/Glowstone#595]
I tested some plugins with glowstone and realized that the PlayerInteractEvent is never fired with `Action.RIGHT_CLICK_AIR`.

The only place in the code where `RIGHT_CLICK_AIR` is used, is [when the right clicked blocked does not exist](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/net/handler/play/player/BlockPlacementHandler.java#L115), and even then the event is not fired most of the time because of the return.
There are two more problems here:
1. The `clicked.getLocation()` in [line 118](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/net/handler/play/player/BlockPlacementHandler.java#L118) might cause a null pointer because it is inside the `clicked == null` block
2. When placing a block against a non-existent block, the client places the new block successfully, but Glowstone only reverts the clicked block (line 118 again) and not the newly placed block.

I'm not completely sure where a `RIGHT_CLICK_AIR` should be fired, there are two cases I would consider:
1. [Here](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/net/handler/play/player/BlockPlacementHandler.java#L89)'s some code in a comment, which would fire a right click when the direction is -1, but I can't find documentation about this case on wiki.vg.
2. The [UseItem packet](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/net/handler/play/player/UseItemHandler.java), because currently there's no event fired.

**Comment by aramperes** [comment]
I fixed some of these issues in 9254c7488592729f4810ac260f3bea59075e23c8

- The null check was impossible, because `getBlockAt` never returns null
- Added newly placed block reversion
- Added the right-click-air event in UseItem.

Please check with your use-cases if this solves your issues. I'm not sure about the `-1` direction in the block placement packet either.

**Comment by kaenganxt** [comment]
`RIGHT_CLICK_AIR` now works as expected. I'm going to open a PR later to fix some other issues with the player interact event I found.
