### ISSUE TITLE
Implement tile tick format

### ISSUE THREAD

**Issue by SamNosliw** [GlowstoneMC/Glowstone#60]
At the moment, pulse requests are stored within the GlowWorld, and if the server shuts down while something is waiting for an update, then it will forget this. So if water is spreading or the pulse request is used for something else later (e.g. redstone) then if the server shuts down or the world unloads, when it reloads it will freeze in place and wont update until a player manually updates it.

This isn't a super high priority issue, but (as far as I can see), this can be fixed in 2 ways:

1) When the world unloads, save all of the active pulse requests in the world save.

2) When a chunk is loaded, force pulse request every block that would accept pulse requests. (Although, this wouldn't perfectly replicate vanilla behavior as floating water doesn't update itself when chunks load, and it might be a little in-efficient)
##

**Comment by mastercoms** [comment]
Include it in here? https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/GlowWorld.java#L491

**Comment by SamNosliw** [comment]
Erm, in regards to what? If you wanted to save all the active pulse requests in the world save, then you would do that here with a few lines in readWorldData() and a few lines in writeWorldData():

https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/io/nbt/NbtWorldMetadataService.java

**Comment by mastercoms** [comment]
For option 2.

**Comment by mastercoms** [comment]
In fact, I think we should replace receivePulse with updateBlock.

**Comment by SamNosliw** [comment]
If using option 1, it would still be cross-compatible with both and mimic vanilla behavior correctly.

Option 2 does not however mimic vanilla as blocks don't trigger those kind of physics updates when a chunk loads. If however you wanted to do it that way then I would put it in the loadChunk() for GlowWorld, or GlowChunk itself, although I haven't looked too deep into either. 

Also, the reason I use the receivePulse instead of updateBlock is blocks can be updated Async, but I want them to spread water and etc within server ticks. Also, its a very convenient way to prevent StackOverflow.

**Comment by mastercoms** [comment]
Wouldn't option 1 change the world save?

How does vanilla do liquid flow from an unloaded chunk (once it is loaded)?

> Also, the reason I use the receivePulse instead of updateBlock is blocks can be updated Async, but I want them to spread water and etc within server ticks. Also, its a very convenient way to prevent StackOverflow.

Sounds reasonable, but can it be integrated with updateBlock somehow, like an offshoot task of updateBlock?

**Comment by SamNosliw** [comment]
Option 1 would add something to the world NBT yes, but vanilla worlds will still be able to read it, and they would ignore the extra field, also glowstone would still be able to read vanilla worlds. Its a similar thing to Bukkit, they added a couple extras to the world NBT and no harm done. I've tried to lookup how vanilla does it, but I can't find the answer.. D:

An offshoot task? I'm not sure what you mean, I call receivePulse from within updateBlock when I need it to update on the next tick. So calling updateBlock should cause it to apply physics, just not instantly, but instead when the server next appropriately ticks, keeping nice timings ;D

**Comment by mastercoms** [comment]
So can we just call updateBlock, which then calls receivePulse when we schedule a chunk update in the world scheduler?

**Comment by SamNosliw** [comment]
Well, the receivePulse could be called, and then the server could shutdown before the world pulses. And if you attempt to call receivePulse straight away, then if its spreading a long distance, or an infinite redstone clock, then it will keep pulsing. There has to be delay. 

Yes, I have tested this by shutting down my server when I start the spread of liquid down a hill. When I start the server up again, the liquid is frozen. The same issue occurs on my test server with redstone, I have a basic clock running, which freezes when the server reboots.

**Comment by SamNosliw** [comment]
If you want, we can discuss this through a chat program rather than this comment system?

**Comment by mastercoms** [comment]
http://minecraft.gamepedia.com/Chunk_format#Tile_tick_format

**Comment by gdude2002** [comment]
This ticket needs categorization on the [waffle board](https://waffle.io/GlowstoneMC/Glowstone).

Has this ticket seen any movement or has there been any action expected since the previous comment?

**Comment by aramperes** [comment]
Done in #334
