### ISSUE TITLE
SLF4J Warning on startup

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#606]
Glowstone build: 89f3731 / `1407`

I'm getting this warning during server startup. This happens right after the configs are created and before binding the server.

```
[WARNING] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[WARNING] SLF4J: Defaulting to no-operation (NOP) logger implementation
[WARNING] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by mastercoms** [comment]
What's your JVM?

**Comment by aramperes** [comment]
Vendor is Oracle.

```
PS F:\Glowstone-4\target> java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by aramperes** [comment]
This issue is now resolved, but as mentioned [here](https://github.com/GlowstoneMC/Glowstone/pull/612#issuecomment-352260214), this issue will be kept open until the Library Manager is rewritten and the fix properly implemented.

**Comment by mastercoms** [comment]
Closing in favor of #451.
