### ISSUE TITLE
It seems that there is a thread safe problem

### ISSUE THREAD

**Issue by iamssx** [GlowstoneMC/Glowstone#621]
the field named "messageQueue" in GlowSession is ArrayDeque class which is not thread safe, but it's "add" method called in netty's thread, it's "poll" method called in antoher thread in GlowScheduler's executor.I don't know whether my understanding is wrong or not.

**Comment by mastercoms** [comment]
Yeah, it seems like your observation is correct. There's lots of thread safe issues in Glowstone right now that we need to fix.
