### ISSUE TITLE
PlayerDataFetcher should be disabled in offline mode?

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#65]
https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/0538fe37681a1fc680b539f286f4975ed84b28d8/src/main/java/net/glowstone/entity/meta/profile/PlayerDataFetcher.java

It is kind of useless for offline mode, so should we disable it?

**Comment by kamcio96** [comment]
BungeeCord? :smile:

**Comment by mastercoms** [comment]
Shouldn't there be a special proxied player mode?
