### ISSUE TITLE
Attachable Blocks are weird with tall grass

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#67]
![redstone torch on redstone torch](http://i.imgur.com/kJpGMO2.png)

I managed to get this beauty by placing one torch on tall grass, while pointing to tall grass behind it, and it replaced the tall grass like you would expect, but then it went on the tall grass behind it. So then, I replaced the tall grass with another torch placement and it placed itself on the face of the redstone torch that was already there.

**Comment by TekkitCommando** [comment]
That's not a bug it's an unexpected feature lol jk

**Comment by mastercoms** [comment]
This was tiring to fix. The torch code is so hacky. I don't want to call it bad, because it was made out of necessity, but it isn't the best solution.
