### ISSUE TITLE
Gson or JSON Simple?

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#68]
I'm looking to clean up the Glowstone++ code. What library should I use for JSON, gson or json simple?

**Comment by TekkitCommando** [comment]
I have looked at gson a little before but not json simple. I think gson would be useful but again I have no experience with json simple so I couldn't have an educated opinion of which one is better :/

**Comment by kamcio96** [comment]
gson ;)

**Comment by mastercoms** [comment]
Anyone know how to convert [this line](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/8dde1c55105d722c22daa46026aa340e69040ae4/src/main/java/net/glowstone/util/TextMessage.java#L193) to gson?

**Comment by kamcio96** [comment]
http://google-gson.googlecode.com/svn/tags/1.2.3/docs/javadocs/com/google/gson/JsonObject.html#addProperty(java.lang.String, java.lang.Number)
or .add("extra", new JsonPrimitive(...));

**Comment by mastercoms** [comment]
Well the value is a list, not a number.

**Comment by kamcio96** [comment]
ohhh
JsonArray array = new JsonArray();
for(JsonObject o : items){
    array.add(o);
}
object.put("extra", array);

**Comment by mastercoms** [comment]
Will the for loop affect performance?

**Comment by kamcio96** [comment]
I think no

**Comment by mastercoms** [comment]
Ok, I was just wondering if there was a alternative within gson for adding an array, but I guess there isn't. Thanks though.
