### ISSUE TITLE
Crafting is weird

### ISSUE THREAD

**Issue by DefinitlyEvil** [GlowstoneMC/Glowstone#76]
Hi there, this is a cool fork of Glowstone and our code switched to your code and we gave you credits in our read me. 
I found out some problems: 
- Crafting is weird(just like original Glowstone xD)
- Item dumplication when crafting(this is kinda serious) 

I really hope you can fix those problems, I tried my best but I can't find where the problem is. Thanks so much. ;D

**Comment by TekkitCommando** [comment]
Thank You! We know about the buggy crafting and we hope to have it fixed soon :smile:

**Comment by DefinitlyEvil** [comment]
Please keep on doing this great work! :D

**Comment by mastercoms** [comment]
This is a bug introduced when we added click logic. The problem is that we never handle shift clicking in the crafting inventory.

**Comment by mastercoms** [comment]
I'm also fixing an incomplete method that is supposed to remove items from the crafting table. This will prevent the dupe glitch accomplished by closing and opening the crafting inventory after a successful craft.

Then, I'll fix items staying in the crafting grid if you do not craft, and instead, they will drop.

**Comment by DefinitlyEvil** [comment]
Cool! :D

**Comment by mastercoms** [comment]
https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/cb28eb57864f6db67ab06f14dc0b761bace6ddfb fixes pretty much all crafting issues, except 1 minor, cosmetic bug, which is listed in the commit comments.

**Comment by mastercoms** [comment]
The window click handler was blocking some crafting because of an unnecessarily strict check. I will be fixing this in just a moment.
