### ISSUE TITLE
Minecraft 1.9

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#78]
You think it's a gonna be a lot of trouble on our part when 1.9 is released? It should change a lot shouldn't it?

**Comment by mastercoms** [comment]
Mojang promised us that 1.9 would not be as bad as 1.8, which had a lot of internal changes. Really, the only things that they're changing substantially is client stuff. 
So it wouldn't be hard at all  to update once Spigot updates to 1.9. Plus, we can do some minor protocol changes and some other stuff to immediately support 1.9 clients.

**Comment by mastercoms** [comment]
Also, 1.9 is being labeled as a far future update

**Comment by TekkitCommando** [comment]
Ok ;)
