### ISSUE TITLE
Glowstone++ versioned release

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Glowstone#79]
I was thinking to mark progress and stability, we should feature a build by versioning it.

This will be great to server owners because they don't know which build is good for their server, and instead have to risk stability and the server being in flux by updating every dev build.

Dev builds will not be versioned. Versioning will just be a way of featuring/marking a build as recommended.

For our first version (0.0.1), I was thinking we should release it once liquid physics and redstone are redone/more complete, we add the new world manager, and add a config for the library manager so people can set to have more libraries download.

**Comment by TekkitCommando** [comment]
I like that idea then 0.0.2 can be released when I add damage :)

**Comment by mastercoms** [comment]
I feel like that should be included in 0.0.1.

**Comment by mastercoms** [comment]
However, we might want to do it like CraftBukkit like, 1.8.7-R0, which links the Minecraft version to the CraftBukkit release version.

**Comment by TekkitCommando** [comment]
Sounds good to me :)

**Comment by mastercoms** [comment]
So first release would be 1.8.7-v0.0.1.

If we happen to become backwards compatible with multiple Minecraft versions, the Mincraft version string should be the latest version we support in that release.

Also, the Glowstone++ version string would be reset to v0.0.1 every time the Minecraft version updates.

**Comment by TekkitCommando** [comment]
Ok :D
