### ISSUE TITLE
Creative inventory actions broken in build 45

### ISSUE THREAD

**Issue by deathcap** [GlowstoneMC/Glowstone#8]
`/gamemode 1`, open inventory, click an item to pick it up then drop in the player inventory, close inventory = item disappears. Same results if shift-click to pickup a stack. At least shift-clicking between inventories now works =). Creative inventory worked in builds before 45. Fallout from:

https://circleci.com/gh/deathcap/GlowstonePlusPlus/45
merge commit: https://github.com/deathcap/GlowstonePlusPlus/commit/d0b16cf248ae8964f98ae3fdfe18ecfbc5228d63
original PR (not isolated - might be a bad merge on my end):
https://github.com/GlowstoneMC/Glowstone/pull/484 Fixed window click logic

**Comment by mastercoms** [comment]
deathcap, would you like me to set up a dedicated GlowstonePlusPlus test server?

**Comment by TekkitCommando** [comment]
I have a hosting company, I think i could get you guys setup with 1 gig of ram on a good box for free if you ever want, unless you can get something better for free @mastercoms @deathcap lol

**Comment by mastercoms** [comment]
Thank you for this generous offer! You might want to talk with deathcap mainly because he is in charge. But that would be great!

**Comment by TekkitCommando** [comment]
Control Panel is what people prefer but might can work something out

**Comment by TekkitCommando** [comment]
We can work something out* ;) lol
