### ISSUE TITLE
Added an Account to the Hosting

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#80]
I added an account to the hosting for Glowstone++ I made the email for the account your public email on github, idk if thatts the email you wanted but if you get a random email its PROBABLY from me :)

Just confirm thats the email you want or tell me the new email you would like and i will give you the login details :)

**Comment by mastercoms** [comment]
Yep, that is the email I want.

Thanks!

**Comment by TekkitCommando** [comment]
Ok I will add your free gig plan when I get home in 30 Mins to an Hour

**Comment by mastercoms** [comment]
How will I pay $4/month extra? Should I just order the $4/month plan?

**Comment by TekkitCommando** [comment]
You can Upgrade your plan, a support manager will help you with that if you cant figure it out once the product is assigned to your account, Also I will talk with the CTO and see if SSH or Automatic Builds for Glowstone++ can be setup for you :)

**Comment by TekkitCommando** [comment]
There you should get an Email where you can login and upload the latest Glowstone++ Jar through FTP while we get SSH/Automatic Building worked out :)

**Comment by TekkitCommando** [comment]
Everything work out?

**Comment by mastercoms** [comment]
Yes, thank you!
