### ISSUE TITLE
Cannot run on ARM device (Raspberry Pi 2), java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Cocosushi6** [GlowstoneMC/Glowstone#839]
Title: Cannot launch glowstone.jar on raspberry pi 2 (raspbian stretch), java.lan.UnstatisfiedLinkError when loading jansi (apparently a dependency from Jline)

Glowstone build: glowstone-2018.1.0-20180201.145750-210 

Hello,
Lately, I have been trying to run Glowstone on a little raspberry pi 2, but I'm facing an error when launching Glowstone.jar (see log below).

The error apparently comes from jansi, which is apparently a dependency of Jline (which, as far as I can see, is used to pretify Glowstone's output). It fails to load its native library, apparently because jansi provides only x86 (IA 32) natives, which are not compatible with ARM ones. I already tried to install `libjansi-java` and `libjansi-java-native` but this will not solve any problem, as the libraries are bundled in the jars :/.
This issue was apparently already solved in jansi [here](https://github.com/fusesource/jansi/pull/65), but jline2 (or at least the version used here) does not take the latest version (1.12 instead of 1.16), which I think could solve the problem. 

Any ideas ?

Thanks in advance for your help :)

---
```Feb 03, 2018 10:21:13 AM net.glowstone.GlowServer main
SEVERE: Error during server startup.
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi32-2018.1.0-SNAPSHOT.c53014f in java.library.path, no jansi-2018.1.0-SNAPSHOT.c53014f in java.library.path, no jansi in java.library.path, /tmp/libjansi-32-2018-8859770119432880512.1: /tmp/libjansi-32-2018-8859770119432880512.1: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
	at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
	at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
	at net.glowstone.ConsoleManager.<init>(ConsoleManager.java:78)
	at net.glowstone.GlowServer.<init>(GlowServer.java:224)
	at net.glowstone.GlowServer.createFromArguments(GlowServer.java:477)
	at net.glowstone.GlowServer.main(GlowServer.java:437)
```

**Comment by smartboyathome** [comment]
Even though jline does not depend on the latest version, you can try overriding it by adding a dependencyManagement section containing the newer dependency to the the pom. Find a description of how to do this here: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management

**Comment by Cocosushi6** [comment]
By "adding", you mean to Glowstone's pom ? Or JLine ? I'm sorry, I'm not very familiar with maven :/

**Comment by Pr0methean** [comment]
@Cocosushi6 Could you please try this version on your Pi? https://601-119324238-gh.circle-artifacts.com/0/glowstone.jar

**Comment by Cocosushi6** [comment]
Ok, server launches, everything works, thanks :+1:
