### ISSUE TITLE
Grass decays in all Biomes except Ocean

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#84]
##

**Comment by mastercoms** [comment]
Why was this closed? Was the bug report invalid?

**Comment by mastercoms** [comment]
I have also noticed this bug.

**Comment by jimmikaelkael** [comment]
I've checked the code and don't see why it happens... Maybe a matter of light values ?
I'll dig it more deeply.

**Comment by mastercoms** [comment]
I'm not seeing this bug anymore.

**Comment by mastercoms** [comment]
I'm seeing this again. It seems to only happen when the world has been generated using the vanilla server.

**Comment by jimmikaelkael** [comment]
Somehow we are unable to get block light level or light opacity when the world was generated with vanilla ?

**Comment by mastercoms** [comment]
But wouldn't it generate the values if they were missing? Maybe there is a read error and it assumes the values are 0 as a default value.

**Comment by mastercoms** [comment]
Fixed in https://github.com/GlowstoneMC/GlowstonePlusPlus/commit/b4cccef350227fa7d334b823423c9c72520b8907.
