### ISSUE TITLE
Add missing Attributes

### ISSUE THREAD

**Issue by Selebrator** [GlowstoneMC/Glowstone#840]
The `AttributeManager$Key`s for `generic.luck` and `generic.flyingSpeed` are missing (at commit c53014f)
Relates to #837 because `generic.luck` has a negative minimum value.

**Comment by Pr0methean** [comment]
#837 is now fixed, and `generic.luck` now has a key.

**Comment by VaiTon** [comment]
This can be closed as from 01e1a4a4b13fc254dc95febd177f42b950856565 this is now implemented.
