### ISSUE TITLE
Boat item isn't consumed on the server-side.

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#847]
The boat item (`ItemBoat`) isn't consumed when placing a boat.

The item appears to be consumed on the client-side, but by updating the inventory view (such as clicking the slot, leaving a vehicle, or simply re-logging) will show that the item is still there.

This is a duplication issue because breaking the boat will drop a new boat item, resulting in 2 boats in the player's inventory.

Reported by `jokbon` on Discord.

**Comment by Pr0methean** [comment]
Unassigning myself because I can't understand why the bug survives #849 nor, given that it does, why the unit tests added in #849 still pass. #849 is probably a partial fix, but I can't find the missing pieces, because everything I know tells me that there should *be* no missing pieces.
