### ISSUE TITLE
Glowstone's Inactivity

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#85]
Glowstone hasn't has any sort of updates at all in at least 6 months, you think they are gonna remain inactive?

**Comment by mastercoms** [comment]
I'm not sure what's going on, but it does not concern us. We're happy to work with Glowstone's developers on merging some of our changes if it becomes active again, and we would appreciate increased support for our fork until that time.

**Comment by TekkitCommando** [comment]
Agreed
