### ISSUE TITLE
Digging snow doesn't produce snowballs

### ISSUE THREAD

**Issue by KiuIras** [GlowstoneMC/Glowstone#852]
Digging snow with a stone (or better) shovel doesn't produce snowballs as expected. It only works with a wooden showel.

When I use a shovel of stone or better, it needs only "one ticks" to break the snow. The only message received from the "handle" method in DiggingHandler class says:
DiggingMessage(state=0, x=-114, y=70, z=94, face=1)

where state=0 stays for "START_DIGGING".
When I use the wooden shovel it takes two ticks and I get both state 0 and state 2 (FINISH_DIGGING) message.

I suppose that messages are sent by clients to the server, maybe the problem is with the managment of message queue?

**Comment by KiuIras** [comment]
I think that digging needs more investigation.
The problem isn't limited to snow digging but affects all the digging actions that is "instantaneous"
(e.g. digging sand or dirt with a efficiency V diamond shovel).
We trust client message "FINISH_DIGGING" but it seems to be unreliable ([wiki](http://wiki.vg/Protocol#Player_Digging) says that client sends the finish message when it _thinks_ digging is finished).
Maybe we should move the responsibility to the server to avoid errors (and malicious clients).

A side note: when client breaks item and Glowstone doesn't see it a inconsistency is created (player chokes if walks where blocks are destroyed by clients but aren't by server)

**Edit:** I don't know if name of this issue should change to describe a more generic problem, feel free to change it!

**Comment by aramperes** [comment]
So from what I understand, the client never sends a `FINISH_DIGGING` state for instantaneous block digging?

**Comment by KiuIras** [comment]
Exactly.

**Comment by Pr0methean** [comment]
What's the purpose of the `FINISH_DIGGING` message, given that we can calculate on the server side when digging finishes? Given that our plan for this bug amounts to just ignoring it, it'd be good to know.

**Comment by KiuIras** [comment]
I can suppose that is useful for let us know the state of the client and restore it in case of inconsistency.
(client sends a FINISH_DIGGING but the block is not really broken -> restore the block on the client)
