### ISSUE TITLE
Server.createProfile(String name) should not trigger an UUID lookup

### ISSUE THREAD

**Issue by stephan-gh** [GlowstoneMC/Glowstone#881]
Problematic code:

https://github.com/GlowstoneMC/Glowstone/blob/911ba9ea99a4750d6ca2f99065fd7fd08a7f77dd/src/main/java/net/glowstone/GlowServer.java#L1689-L1697

This should not lookup the UUID for the given name. `PlayerProfile` is defined to have at least **either** the UUID or name defined, but not necessarily both. This code may be used with names that don't really exist, and therefore shouldn't trigger an UUID lookup.

An example for such usage is the new `PaperServerListPingEvent` added in https://github.com/PaperMC/Paper/pull/980. Fake `PlayerProfile`s may be used to display custom messages in the list of players displayed when hovering the player count in the server list.

I've ported `PaperServerListPingEvent` to Glowstone in #880, and running [ServerListPlus](https://www.spigotmc.org/resources/serverlistplus.241/) on it then results in a significant delay and the following error: https://gist.github.com/Minecrell/448ad637b2e9d033b1864f522da8d773 because it is looking up the fake profile.

It seems like this was done in #817 because `GlowPlayerProfile` doesn't support having no UUID defined (see https://github.com/GlowstoneMC/Glowstone/pull/817#discussion_r162812665). However, it should be refactored to support this to match the API specifications.

This is needed for #880.

**Comment by Pr0methean** [comment]
@Minecrell Could you please test #882 as a fix? If it doesn't fix, then it probably at least mitigates the delay. To get a version with the change, go to https://circleci.com/gh/Pr0methean/Glowstone/tree/uuid, click the newest build, then it's under Artifacts.

**Comment by stephan-gh** [comment]
@Pr0methean The issue title was correct: it should not trigger an UUID lookup at all. It doesn't matter if it's blocking or not.

Your fix improves the situation somewhat, because it no longer throws an exception if the UUID cannot be found. But it's not the correct fix: It will still block for ~250ms on the first run because the code in `PaperServerListPingEvent` calls `getId()` on the added profiles (and expects them to return `null` eventually).

```
09:35:32 [WARNING] Couldn't get UUID due to IO error: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.mojang.com/profiles/minecraft
```

The `PlayerProfile` shouldn't be (partially) completed in a potentially blocking operation unless one of the `complete()` methods is called. If it was created without UUID/without name, the getters should return `null`, until it gets completed manually by calling `complete()`.

**Comment by stephan-gh** [comment]
Please re-open this issue. As mentioned above, the issue is not fixed in #882.

**Comment by Pr0methean** [comment]
@Minecrell Is there some reason not to do the lookup eagerly, once getId() is made non-blocking? The worst case is that we waste a few bytes of bandwidth and, if fully utilizing the CPU, slightly delay another async task on `ForkJoinPool.commonPool()` (which is where the UUID lookups run, since they use `CompletableFuture.supplyAsync`).

**Comment by mastercoms** [comment]
@Pr0methean I believe it's for fake players where this is no point to looking it up. As stated, `complete()` can be called if the profile needs to be looked up and completed.

**Comment by stephan-gh** [comment]
@mastercoms is right, but in this case, the usage doesn't really matter. This is just about implementing the API correctly (granted, the Javadocs on some methods could be more clear).

`Server.createProfile(...)` should take the given parameters and create a `PlayerProfile` with them. No lookup or anything, just create a profile with the given values.

`PlayerProfile.complete()` (blocking) or `PlayerProfile.completeCached()` (not blocking, should only use cached values) can then be called additionally by plugins to complete the remaining parts, i.e. UUID/name, textures etc.

The main question is if having `GlowPlayerProfile.getId()` nullable will cause problems in other places of the Glowstone code. If that is the case, it might be necessary to add some checks and eventually call `.complete()` where necessary. This is why I didn't create a PR to fix this, I'm not familiar with all the other usages of `GlowPlayerProfile` in Glowstone.

**Comment by Pr0methean** [comment]
I'll overload `GlowServer.createProfile()` so that the async completion is optional, and modify the existing calls to enable it.
