### ISSUE TITLE
Use of SHA-1 in EncryptionKeyResponseHandler.java

### ISSUE THREAD

**Issue by ptsankov** [GlowstoneMC/Glowstone#898]
EncryptionKeyResponseHandler.java uses SHA-1:

```
MessageDigest digest = MessageDigest.getInstance("SHA-1");
```

SHA-1 is considered insecure and should be replaced by the successor (e.g. SHA-256).

**Comment by DaMatrix** [comment]
Mojang uses SHA-1 for that, so it can't really be changed. (AFAIK)

plus, how secure does a block game need to be?

EDIT: looking at your profile, are you just running a script that searches for "SHA-1" in repositories and reports that as an issue?

**Comment by DaMatrix** [comment]
Update: it is something used by mojang, so no that can't be changed.

![screenshot_2018-04-11-12-18-30](https://user-images.githubusercontent.com/11216106/38610923-9f3e6568-3d82-11e8-9e36-77cfc1e4b954.png)

**Comment by aramperes** [comment]
Consider submitting this to Mojang on their issue tracker.
