### ISSUE TITLE
Chunk Generation Errors

### ISSUE THREAD

**Issue by MrSnowGlobe** [GlowstoneMC/Glowstone#93]
Getting Chunk generations when starting the server.

Using Glowstone++ Build #401

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Logs - http://pastebin.com/fqEju2zQ

I couldn't post the full log because it exceeds the file size limit of pastebins free offering. I included the start and end of the logs with some middle cut out. 

Will provide full logs if required (:

**Comment by mastercoms** [comment]
Thanks for the bug report. I couldn't reproduce this bug, so I am not sure it is fixed with this new version. If it does not fix it, please reopen this issue.

**Comment by MrSnowGlobe** [comment]
Thanks for the quick response!

The issue is fixed (:

**Comment by mastercoms** [comment]
You're welcome!  I'm glad you reported this bug.

**Comment by TekkitCommando** [comment]
Not all plugins are tested to work on Glowstone++ yet, but mastercoms would know the compatibility of plugins generating worlds more then me :P

**Comment by MrSnowGlobe** [comment]
Totally understand that Tekkit (:

It's why I am testing a few plugins I use against Glowstone++

**Comment by TekkitCommando** [comment]
@MrSnowGlobe How often do you check github?

**Comment by MrSnowGlobe** [comment]
Daily. I also get email notifications for issue conversations etc, So I try to respond when I can (: Why?

**Comment by TekkitCommando** [comment]
I have a donation system plugin that i wanted to test against glowstone++ in the future, if you are doing exactly that, I was wondering if you would test it for me when its ready :)

**Comment by mastercoms** [comment]
I am not sure what causes those errors. I have been trying to figure out for some time now. Could you create a separate issue for it?
