### ISSUE TITLE
Breaking blocks doesn't work in Survival mode

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowstone#940]
Affects the 2018.5.0 release.

Breaking a block with hands or with tools while in Survival will be rejected. The block will simply re-appear immediately, and stays as such.

It appears that an entity colliding with the block after breaking it was attempted successfully destroys the block. For example, attempting to break a block and later jumping on it will cause it to break.

Re-logging does not appear to break the block, so this is not a client-side issue.

This was most likely introduced in #910.

**Comment by jhg023** [comment]
Can verify #910 is the cause.
