### ISSUE TITLE
Bed bug in inventory. (no pun)

### ISSUE THREAD

**Issue by jaydenSPC** [GlowstoneMC/Glowstone#947]
I found an area of beds and decided to excavate them. But I noticed some unusual behaviour. They were breaking into half-blocks, and giving me 2 beds. Also they went into illegal item slots:

![2018-06-24_16 12 38](https://user-images.githubusercontent.com/30561822/41815826-02f54032-77ca-11e8-8350-382309edd41f.png)

Here's pictures of half-beds:

![2018-06-24_16 17 26](https://user-images.githubusercontent.com/30561822/41815830-25302982-77ca-11e8-9df1-8de0436ea92e.png)
![2018-06-24_16 17 37](https://user-images.githubusercontent.com/30561822/41815831-256501e8-77ca-11e8-890d-5d86ac5f1b1d.png)

Edit:

I found a bug with animal behaviour, if you punch it, they just get moved backwards:

![2018-06-24_16 21 35](https://user-images.githubusercontent.com/30561822/41815855-cb9ba1d4-77ca-11e8-9085-64a6e1d60b9c.png)

And with item physics:

![2018-06-24_16 21 44](https://user-images.githubusercontent.com/30561822/41815857-d4a53416-77ca-11e8-99b1-df75855a1c85.png)

**Comment by VaiTon** [comment]
Sorry if I don't undertand correctly, have you found an area full of bed blocks?
