### ISSUE TITLE
/target/classes/net/glowstone/util/UuidUtils.class Virus

### ISSUE THREAD

**Issue by josephworks** [GlowstoneMC/Glowstone#953]
Title: [ERROR] Bad class file /var/lib/jenkins/workspace/Glowstone/target/classes/net/glowstone/util/UuidUtils.class

Glowstone build: `Any`

My antivirus keeps on deleting ./target/classes/net/glowstone/util/UuidUtils.class causing the build to fail

It says the virus is called Java_Kryptik.GF

http://www.virusradar.com/en/Java_Kryptik.GF/detail

---

Windows 10 Pro
ESET Internet Security 11
Built with Maven on Ubuntu 18.04
Built on Private jenkins: 174.17.184.170:8080/job/Glowstone/2/console

**Comment by josephworks** [comment]
![](https://cdn.discordapp.com/attachments/201529692979855360/465380988839657472/unknown.png)

**Comment by josephworks** [comment]
i am requesting to get the threat removed

**Comment by WesleyVanNeck** [comment]
@josephworks  there is no virus in glowstone am 100% sure

**Comment by WesleyVanNeck** [comment]
and your antivirus well first there no data on the virus second one the devs dont do that

**Comment by mikroskeem** [comment]
> i am requesting to get the threat removed

[If you take look at the code](https://github.com/GlowstoneMC/Glowstone/blob/702bc20c6d15672ee14928a54a4047285fcace60/src/main/java/net/glowstone/util/UuidUtils.java), then can you see anything weird there? No.

Conclusion - get rid of your silly antivirus software =)

**Comment by Logics4** [comment]
That's what happens when you use an antivirus that even I haven't heard of.
If you want something free that you don't have to re-install all the time to get a new free trial, at least get Avast.

**Comment by josephworks** [comment]
The antivirus is good but it made an error. I am not going to uninstall it or anything like that. @mikroskeem @Logics4 The antivirus is one of the best antiviruses as you can see
![image](https://user-images.githubusercontent.com/18745823/42420721-bb989666-827e-11e8-8ed8-1b0af9999fbc.png)
You are obviously not an IT Professional if you are telling me to uninstall my antivirus.

**Comment by aramperes** [comment]
This is not the right place to argue about antivirus software.
