### ISSUE TITLE
Detection of Java/Kryptik.GF

### ISSUE THREAD

**Issue by liberodark** [GlowstoneMC/Glowstone#959]
Hi,

All glowstone version downloaded is detected : 
glowstone.jar - une variante de Java/Kryptik.GF cheval de troie.
Please remove your malicious code.

Cordialy

**Comment by aramperes** [comment]
Glowstone is open-source, and does not contain any viruses.

If you are concerned about the package you downloaded, consider building Glowstone yourself.

Duplicate of #953.
