### ISSUE TITLE
TNT does not detect entities after a world save

### ISSUE THREAD

**Issue by nerlu** [GlowstoneMC/Glowstone#98]
now you will get no tnt knockback at all.
see #97

**Comment by mastercoms** [comment]
Do you get damaged?

**Comment by Luki110998** [comment]
Nope.

**Comment by mastercoms** [comment]
Ok, then it is a problem with the entity gathering logic I made.

**Comment by mastercoms** [comment]
I looked into it, and it is not a problem with the entity gathering logic, but rather, the tnt knockback was too small, and damaging with tnt skipped over players for some reason.

**Comment by mastercoms** [comment]
Curiouser and curioser. I have found the "problem." Once a world is saved once, TNT entity detection no longer works.

**Comment by mastercoms** [comment]
I think this was fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/82b11a22fda36221e3bea6f4fa446925e176af55
