### ISSUE TITLE
Glowstone++ and Dragonet Sponsorship

### ISSUE THREAD

**Issue by ethsmith** [GlowstoneMC/Glowstone#99]
I am MC Server Bank's COO as I have told you before probably that's how I gave @mastercoms and @DragonetMC a sponsorship for Minecraft Server's, but I am creating a software/game development LLC and so I will have less time to look after the sponsored accounts, you should be good but if you have any trouble you guys can always comment here or email me at tekkitcommando@gmail.com

**Comment by mastercoms** [comment]
I had to cancel my subscription because they would not give a discount anymore.

**Comment by TekkitCommando** [comment]
MC Server Bank took away your discount?

**Comment by mastercoms** [comment]
Yes.

**Comment by TekkitCommando** [comment]
Ok I will fix that :)

**Comment by TekkitCommando** [comment]
No one messes with my clients xD
