### ISSUE TITLE
Players moves at wrong positions

### ISSUE THREAD

**Issue by niansa** [GlowstoneMC/Glowstone#993]
If a player is connected over a longer time then the clients player position will just get desyncronized to the server and other client. That causes bugs on the desyncronized client.

How to reproduce: Just start a unconfigured glowstone server and let two clients connect and move around and teleport and so on. I don't exactly know how to reproduce that.

**Comment by Pr0methean** [comment]
Probably duplicated by #1006, but I recommend that 1006 be the canonical number for this bug, since the report at #1006 has clearer steps to reproduce. (Don't take it personally; it's the kind of report only a plugin developer can provide.)

**Comment by niansa** [comment]
It's okay, I close this. :+1:
